### ISSUE TITLE
missing module (phply)

### ISSUE THREAD

**Issue by kaswaraa** [andresriancho/w3af#10388]
Hello,
I am trying to install w3af n ubuntu 14.04 LTS. I am facing a common issue when i am running w3af_console or w3af_gui:
Your python installation needs the following modules to run w3af:
    phply
I executed fix script (/tmp/w3af_dependency_install.sh), executed command (sudo pip install phply==0.9.1) also i tested workaround listed in issue (#2766) without any success. Kindly help me to resolve this issue:

pip --version
pip 7.0.3 from /usr/local/lib/python2.7/dist-packages (python 2.7)

uname -a
Linux Hunter 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

adium-theme-ubuntu==0.3.4
apt-xapian-index==0.45
BeautifulSoup==3.2.1
chardet==2.1.1
clamd==1.0.1
cluster==1.1.1b3
colorama==0.2.5
command-not-found==0.3
darts.util.lru==0.5
debtagshw==0.1
defer==1.0.6
defusedxml==0.4.1
dirspec==13.10
dnspython==1.11.1
docutils==0.12
duplicity==0.6.23
esmre==0.3.1
fpconst==0.7.2
futures==2.1.5
gitdb==0.6.4
GitPython==0.3.2rc1
graphviz==0.4.2
guess-language==0.2
halberd==0.2.4
html5lib==0.999
httplib2==0.8
Jinja2==2.7.3
lockfile==0.8
lxml==3.4.4
Markdown==2.6.1
MarkupSafe==0.23
msgpack-python==0.4.4
ndg-httpsclient==0.3.3
nltk==3.0.1
oauthlib==0.6.1
oneconf==0.3.7
PAM==0.4.2
pdfminer==20140328
pexpect==3.1
-e git://github.com/ramen/phply.git@ff6a567f84b4f7011be28dcc630d37d1a5d878c4#egg=phply-master
Pillow==2.3.0
piston-mini-client==0.7.5
ply==3.4
psutil==2.2.1
pyasn1==0.1.3
pybloomfiltermmap==0.3.14
pycrypto==2.6.1
pycups==1.9.66
pycurl==7.19.3
PyGithub==1.21.0
pygobject==3.12.0
pyOpenSSL==0.13.1
pyPdf==1.13
pyserial==2.6
pysmbc==1.0.14.1
python-apt===0.9.3.5ubuntu1
python-debian===0.1.21-nmu2ubuntu2
python-ntlm==1.0.1
pyxdg==0.25
PyYAML==3.11
reportlab==3.0
requests==2.2.1
ruamel.ordereddict==0.4.8
scapy-real==2.2.0.dev0
sessioninstaller==0.0.0
six==1.5.2
smmap==0.9.0
SOAPpy==0.12.22
software-center-aptd-plugins==0.0.0
stopit==1.1.0
system-service==0.1.6
tblib==0.2.0
Twisted-Core==13.2.0
Twisted-Web==13.2.0
unity-lens-photos==1.0
urllib3==1.7.1
virtualenv==12.0.5
vulndb==0.0.17
wapiti==2.3.0
wheel==0.24.0
wstools==0.4.3
xdiagnose===3.6.3build2
xdot==0.6
zope.interface==4.0.5

**Comment by andresriancho** [comment]
What happens if you run this in a python console?

```python
import pip
[dist.project_name.lower() for dist in pip.get_installed_distributions() if 'phply' in dist.project_name.lower()]
```

This is something I don't like: `-e git://github.com/ramen/phply.git@ff6a567f84b4f7011be28dcc630d37d1a5d878c4#egg=phply-master`

Maybe try to remove that package and install it again using `pip install phply==0.9.1`
