### ISSUE TITLE
Add basic authentication to REST API

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#10615]
## Looking for contributor!
Want to improve the w3af framework? This is your chance! This task is looking for a contributor, just add a message to this issue saying: "I'll do it!" and start with the fun :+1: 

## User story
As a user I want to restrict access to the REST API in order to be able to access it over the network without any risk of others accessing it

## Conditions of satisfaction
 - [x] Decorate all routes with the basic authentication checker
 - [x] Let the user define username and password using command line arguments and a yaml configuration file (to prevent "password sniffing using `ps auxf`). The yaml file can also be used to configure bind port and address
 - [x] Store SHA-512 password hashes in yaml
 - [x] Require the user to enter SHA-512 hash of the password in command line
 - [x] Answer with a 401 for all requests which don't have the right credentials
 - [x] Write documentation on how to provide authentication, consume authenticated service, etc.
 - [ ] Allow the user to start API without authentication

## Limitations
 - [x] Only one user is allowed

**Comment by OwenTuz** [comment]
I'll do this one :)

**Comment by andresriancho** [comment]
@OwenTuz amazing, thanks!

**Comment by andresriancho** [comment]
I just added some comments to the code, please also remember to add the user documentation to https://github.com/andresriancho/w3af/blob/master/doc/sphinx/api/index.rst explaining how to start the API with auth

**Comment by andresriancho** [comment]
Your code looks really good for now!

**Comment by OwenTuz** [comment]
I've attached an initial pull request #10857 above (please ignore 10856, was for the wrong branch - sorry), with some notes. Let me know if you want me to change anything, or spot any bugs/problems.

Thanks!

**Comment by andresriancho** [comment]
@OwenTuz amazing code! A couple of fixes and it will be ready to merge
