### ISSUE TITLE
'NoneType' object has no attribute 'url_string' (w3af Rest Api)

### ISSUE THREAD

**Issue by Ahiknsr** [andresriancho/w3af#10835]
I used w3af rest api to perform  a scan,  after completing the scan i have sent a GET request to knowledge base to view the vulnerabilities  identified. the request is throwing a error .

$curl -X GET http://localhost:5000/scans/0/kb/
{
  "code": 500,
  "exception_type": "AttributeError",
  "filename": "kb.py",
  "function_name": "finding_to_json",
  "line_number": 145,
  "message": "'NoneType' object has no attribute 'url_string'",
  "please": "https://github.com/andresriancho/w3af/issues/new"
}

w3af version details 
$curl -X GET http://localhost:5000/version
{
  "branch": "master",
  "dirty": "No",
  "revision": "f91a13ca69 - 24 Jun 2015 20:09",
  "version": "1.7.2"
}

**Comment by andresriancho** [comment]
@Ahiknsr thanks for the bug report!

Fixed in the latest develop commit
