### ISSUE TITLE
Is there any way to tell scaner use IPv4 or IPv6 only?

### ISSUE THREAD

**Issue by kyprizel** [andresriancho/w3af#10934]
For example if target domain has AAAA records and does not handle IPv6 connections but still accessible via IPv4 w3af is working very slowly on such a domain b/c of timeouts.

**Comment by andresriancho** [comment]
Not sure if this works but... maybe edit /etc/hosts to point to ipv4?

**Comment by kyprizel** [comment]
I think local_ip_address is a solution.
