### ISSUE TITLE
Cross Site WebSocket Hijacking check

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#1123]
Is there a way to check for this vulnerability in an automated way? Maybe for a subset of the cases?

http://www.christian-schneider.net/CrossSiteWebSocketHijacking.html

**Comment by andresriancho** [comment]
Finally working on this at Websockets stuff from nixwizard #10395

**Comment by cschneider4711** [comment]
Great! Let me know if I can help by testing it in some environments...

**Comment by andresriancho** [comment]
@cschneider4711 not sure if you get the alerts on [this issue](https://github.com/andresriancho/w3af/issues/10395) but there is a comment there for you
