### ISSUE TITLE
/tmp/w3af_dependency_install.sh  install failure

### ISSUE THREAD

**Issue by Tiffenny** [andresriancho/w3af#11357]
I'm a beginning at CentOS7.

I tried to follow the document of installation of W3af..

It failed all the time at running " /tmp/w3af_dependency_install.sh " step..

I got the different error message everytime when I run it. How can i do to fix it?

Error Message

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hcWwPj/netlib
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-8FECO2/netlib
python version Python-2.7.5

**Comment by andresriancho** [comment]
Could you copy+paste the whole error? The one you're showing is not enough for me to help

**Comment by Tiffenny** [comment]
Thanks for your help and this is the whole message when I start running /tmp/w3af_dependency_install.sh


[root@localhost tiff]# . /tmp/w3af_dependency_install.sh
Collecting clamd==1.0.1
/usr/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached clamd-1.0.1.zip
Collecting PyGithub==1.21.0
  Using cached PyGithub-1.21.0.tar.gz
Collecting GitPython==0.3.2.RC1
  Using cached GitPython-0.3.2.RC1.tar.gz
Collecting pybloomfiltermmap==0.3.14
  Using cached pybloomfiltermmap-0.3.14.tar.gz
Collecting esmre==0.3.1
  Using cached esmre-0.3.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): phply==0.9.1 in /usr/lib/python2.7/site-packages
Collecting nltk==3.0.1
  Using cached nltk-3.0.1.tar.gz
Collecting chardet==2.1.1
  Using cached chardet-2.1.1.tar.gz
Collecting tblib==0.2.0
  Using cached tblib-0.2.0-py2-none-any.whl
Collecting pdfminer==20140328
  Using cached pdfminer-20140328.tar.gz
Collecting futures==2.1.5
  Using cached futures-2.1.5-py2.py3-none-any.whl
Collecting pyOpenSSL==0.15.1
  Using cached pyOpenSSL-0.15.1-py2.py3-none-any.whl
Collecting ndg-httpsclient==0.3.3
  Using cached ndg_httpsclient-0.3.3.tar.gz
Collecting pyasn1==0.1.7
  Using cached pyasn1-0.1.7.tar.gz
Collecting lxml==3.4.4
  Using cached lxml-3.4.4.tar.gz
Collecting scapy-real==2.2.0-dev
  Using cached scapy-real-2.2.0-dev.tar.gz
Collecting guess-language==0.2
  Using cached guess-language-0.2.tar.gz
Collecting cluster==1.1.1b3
  Using cached cluster-1.1.1b3.tar.gz
Collecting msgpack-python==0.4.4
  Using cached msgpack-python-0.4.4.tar.gz
Collecting python-ntlm==1.0.1
  Using cached python-ntlm-1.0.1.tar.gz
Collecting halberd==0.2.4
  Using cached halberd-0.2.4.tar.gz
Collecting darts.util.lru==0.5
  Using cached darts.util.lru-0.5.tar.gz
Collecting Jinja2==2.7.3
  Using cached Jinja2-2.7.3.tar.gz
Collecting vulndb==0.0.17
  Using cached vulndb-0.0.17.tar.gz
Collecting markdown==2.6.1
  Using cached Markdown-2.6.1.tar.gz
Collecting psutil==2.2.1
  Using cached psutil-2.2.1.tar.gz
Collecting mitmproxy==0.12.1
  Using cached mitmproxy-0.12.1.tar.gz
Collecting ruamel.ordereddict==0.4.8
  Using cached ruamel.ordereddict-0.4.8.tar.gz
Collecting Flask==0.10.1
  Using cached Flask-0.10.1.tar.gz
Collecting xdot==0.6
  Using cached xdot-0.6.tar.gz
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg (from clamd==1.0.1)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/site-packages (from clamd==1.0.1)
Collecting gitdb>=0.5.1 (from GitPython==0.3.2.RC1)
  Using cached gitdb-0.6.4.tar.gz
Requirement already satisfied (use --upgrade to upgrade): ply in /usr/lib/python2.7/site-packages (from phply==0.9.1)
Collecting cryptography>=0.7 (from pyOpenSSL==0.15.1)
  Using cached cryptography-0.9.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /usr/lib64/python2.7/site-packages (from Jinja2==2.7.3)
Collecting pyperclip>=1.5.8 (from mitmproxy==0.12.1)
  Using cached pyperclip-1.5.11.zip
Collecting tornado>=4.0.2 (from mitmproxy==0.12.1)
  Using cached tornado-4.2.tar.gz
Collecting netlib<0.13,>=0.12 (from mitmproxy==0.12.1)
  Using cached netlib-0.12.1.tar.gz
    Complete output from command python setup.py egg_info:
    warning: no files found matching 'OpenSSL/RATIONALE'
    warning: no previously-included files found matching 'leakcheck'
    warning: no previously-included files matching '*.py' found under directory 'leakcheck'
    warning: no previously-included files matching '*.pem' found under directory 'leakcheck'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    no previously-included directories found matching 'doc/_build'
    zip_safe flag not set; analyzing archive contents...
    
    Installed /tmp/pip-build-zruMZG/netlib/.eggs/pyOpenSSL-0.15.1-py2.7.egg
    Searching for cffi
    Reading https://pypi.python.org/simple/cffi/
    Best match: cffi 1.1.2
    Downloading https://pypi.python.org/packages/source/c/cffi/cffi-1.1.2.tar.gz#md5=ca6e6c45b45caa87aee9adc7c796eaea
    Processing cffi-1.1.2.tar.gz
    Writing /tmp/easy_install-mkDWbP/cffi-1.1.2/setup.cfg
    Running cffi-1.1.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-mkDWbP/cffi-1.1.2/egg-dist-tmp-ev4WHo
    creating /tmp/pip-build-zruMZG/netlib/.eggs/cffi-1.1.2-py2.7-linux-x86_64.egg
    Extracting cffi-1.1.2-py2.7-linux-x86_64.egg to /tmp/pip-build-zruMZG/netlib/.eggs
    
    Installed /tmp/pip-build-zruMZG/netlib/.eggs/cffi-1.1.2-py2.7-linux-x86_64.egg
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-zruMZG/netlib/setup.py", line 87, in <module>
        "install": CFFIInstall,
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 268, in __init__
      File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 313, in fetch_build_eggs
      File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 836, in resolve
      File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1074, in best_match
      File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 711, in find
    pkg_resources.VersionConflict: (six 1.3.0 (/usr/lib/python2.7/site-packages), Requirement.parse('six>=1.5.2'))
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zruMZG/netlib
[root@localhost tiff]#

**Comment by andresriancho** [comment]
Seems to be a problem with a dependency conflict, try installing inside a virtualenv
http://docs.w3af.org/en/latest/advanced-install.html#installing-using-virtualenv

**Comment by Tiffenny** [comment]
Cool !!!  It works...  Thanks...

**Comment by Tiffenny** [comment]
I try to reinstall it again... but it i didn't work....


(venv)[root@localhost w3af]# . /tmp/w3af_dependency_install.sh
Collecting clamd==1.0.1
/home/tiff/w3af/venv/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached clamd-1.0.1.zip
Collecting PyGithub==1.21.0
  Using cached PyGithub-1.21.0.tar.gz
Collecting GitPython==0.3.2.RC1
  Using cached GitPython-0.3.2.RC1.tar.gz
Collecting pybloomfiltermmap==0.3.14
  Using cached pybloomfiltermmap-0.3.14.tar.gz
Collecting esmre==0.3.1
  Using cached esmre-0.3.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): phply==0.9.1 in /usr/local/lib/python2.7/site-packages
Collecting nltk==3.0.1
  Using cached nltk-3.0.1.tar.gz
Collecting chardet==2.1.1
  Using cached chardet-2.1.1.tar.gz
Collecting tblib==0.2.0
  Using cached tblib-0.2.0-py2-none-any.whl
Collecting pdfminer==20140328
  Using cached pdfminer-20140328.tar.gz
Collecting futures==2.1.5
  Using cached futures-2.1.5-py2.py3-none-any.whl
Collecting pyOpenSSL==0.15.1
  Using cached pyOpenSSL-0.15.1-py2.py3-none-any.whl
Collecting ndg-httpsclient==0.3.3
  Using cached ndg_httpsclient-0.3.3.tar.gz
Collecting pyasn1==0.1.7
  Using cached pyasn1-0.1.7.tar.gz
Collecting lxml==3.4.4
  Using cached lxml-3.4.4.tar.gz
Collecting scapy-real==2.2.0-dev
  Using cached scapy-real-2.2.0-dev.tar.gz
Collecting guess-language==0.2
  Using cached guess-language-0.2.tar.gz
Collecting cluster==1.1.1b3
  Using cached cluster-1.1.1b3.tar.gz
Collecting msgpack-python==0.4.4
  Using cached msgpack-python-0.4.4.tar.gz
Collecting python-ntlm==1.0.1
  Using cached python-ntlm-1.0.1.tar.gz
Collecting halberd==0.2.4
  Using cached halberd-0.2.4.tar.gz
Collecting darts.util.lru==0.5
  Using cached darts.util.lru-0.5.tar.gz
Collecting Jinja2==2.7.3
  Using cached Jinja2-2.7.3.tar.gz
Collecting vulndb==0.0.17
  Using cached vulndb-0.0.17.tar.gz
Collecting markdown==2.6.1
  Using cached Markdown-2.6.1.tar.gz
Collecting psutil==2.2.1
  Using cached psutil-2.2.1.tar.gz
Collecting mitmproxy==0.12.1
  Using cached mitmproxy-0.12.1.tar.gz
Collecting ruamel.ordereddict==0.4.8
  Using cached ruamel.ordereddict-0.4.8.tar.gz
Collecting Flask==0.10.1
  Using cached Flask-0.10.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./venv/lib/python2.7/site-packages (from clamd==1.0.1)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/site-packages (from clamd==1.0.1)
Collecting gitdb>=0.5.1 (from GitPython==0.3.2.RC1)
  Using cached gitdb-0.6.4.tar.gz
Requirement already satisfied (use --upgrade to upgrade): ply in /usr/local/lib/python2.7/site-packages (from phply==0.9.1)
Collecting cryptography>=0.7 (from pyOpenSSL==0.15.1)
  Using cached cryptography-0.9.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /usr/lib64/python2.7/site-packages (from Jinja2==2.7.3)
Collecting pyperclip>=1.5.8 (from mitmproxy==0.12.1)
  Using cached pyperclip-1.5.11.zip
Collecting tornado>=4.0.2 (from mitmproxy==0.12.1)
  Using cached tornado-4.2.1.tar.gz
Collecting netlib<0.13,>=0.12 (from mitmproxy==0.12.1)
  Using cached netlib-0.12.1.tar.gz
    Complete output from command python setup.py egg_info:
    warning: no files found matching 'OpenSSL/RATIONALE'
    warning: no previously-included files found matching 'leakcheck'
    warning: no previously-included files matching '*.py' found under directory 'leakcheck'
    warning: no previously-included files matching '*.pem' found under directory 'leakcheck'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    no previously-included directories found matching 'doc/_build'
    zip_safe flag not set; analyzing archive contents...
    
    Installed /tmp/pip-build-38Dx6r/netlib/.eggs/pyOpenSSL-0.15.1-py2.7.egg
    Searching for cffi
    Reading https://pypi.python.org/simple/cffi/
    Best match: cffi 1.1.2
    Downloading https://pypi.python.org/packages/source/c/cffi/cffi-1.1.2.tar.gz#md5=ca6e6c45b45caa87aee9adc7c796eaea
    Processing cffi-1.1.2.tar.gz
    Writing /tmp/easy_install-2aW6nJ/cffi-1.1.2/setup.cfg
    Running cffi-1.1.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-2aW6nJ/cffi-1.1.2/egg-dist-tmp-yJIId3
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-38Dx6r/netlib/setup.py", line 87, in <module>
        "install": CFFIInstall,
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/tiff/w3af/venv/lib/python2.7/site-packages/setuptools/dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/tiff/w3af/venv/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/tiff/w3af/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 836, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/tiff/w3af/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1081, in best_match
        return self.obtain(req, installer)
      File "/home/tiff/w3af/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1093, in obtain
        return installer(requirement)
      File "/home/tiff/w3af/venv/lib/python2.7/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/tiff/w3af/venv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 629, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/tiff/w3af/venv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 659, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/tiff/w3af/venv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 842, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/tiff/w3af/venv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1070, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/tiff/w3af/venv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1058, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-38Dx6r/netlib

It's so weird...
