### ISSUE TITLE
Handling of Multipart forms with GET method

### ISSUE THREAD

**Issue by kyprizel** [andresriancho/w3af#11998]
Here is example form with leads to "Unsupported URL" error when parsed by w3af.
http://dvwa.people.yandex.net/mgform.php

Should we add condition if enctype="multipart/form-data forms" was set then use POST?

**Comment by andresriancho** [comment]
Thanks for the bug report.

For now all I can say is that Chrome forces POST when multipart/form is specified, so it might make sense to do the same in w3af

**Comment by andresriancho** [comment]
Oh, wait... I just saw the javascript stuff:

```html
<form action="" method="get" enctype="multipart/form-data" target="_self" id="tricky_form">
<input type="text" name="test" value="тест">
<input type="submit" name="submit" onclick="document.forms[0].method='POST'; return true;">
</form>
```

**Comment by andresriancho** [comment]
Ok, so it gets stranger/more complex than I expected. Let's see the new HTML I've created:

```html
<html>
<head>
<meta charset="UTF-8">
</head>
<body>

<h3>JS trick</h3>
<form action="" method="get" enctype="multipart/form-data">
<input type="text" name="test" value="тест">
<input type="submit" name="submit" onclick="document.forms[0].method='POST'; return true;">
</form>

<h3>No JS trick</h3>
<form action="" method="get" enctype="multipart/form-data">
<input type="text" name="test" value="тест">
<input type="submit" name="submit">
</form>

</body>
</html>
```

## Analysis
### Chrome
 * JS trick: It will run the javascript which changes the form method and then send the request using POST
 * No JS trick: It finds two attributes which can't be satisfied together, `method="get"` and `enctype="multipart/form-data"`. It decides that it's a good idea to send the request using a GET method and uses the query string (and url encoding)

## Firefox
 * No JS trick: Same as Chrome, it decides to send the request as GET with data as query string

### w3af
 * JS trick: Is unable to run javascript, thus it will (not tested, but from what I believe the code will do) send a GET request with a multipart encoded post-data
 * No JS trick: Same as `JS trick`


## Expected results
 * Overall, `w3af` should behave just like a browser
 * Running the javascript is hard and will be done at some point in time, added a different issue to do it: JavaScript run form.onclick change form method #11999
 * `w3af` needs to be changed to behave like Firefox/Chrome for `No JS trick` case
