### ISSUE TITLE
Developer's Guide is outdated

### ISSUE THREAD

**Issue by plizonczyk** [andresriancho/w3af#12029]
Hi!
Today I tried to setup docker test containers in order to run tests of my new plugin. Trying to follow [Developer's Guide paragraph on running test suite](https://github.com/andresriancho/w3af/wiki/Developer's-Guide#running-the-test-suite), I failed to locate test-compose.yml. After some digging in git history I found out that was moved to w3af/tests/docker-compose.yml
Also, it should be noted, that those changes are not in master yet (even the test-compose.yml file).

Cheers,
Piotrek

**Comment by andresriancho** [comment]
Updated! Thanks for noticing

https://github.com/andresriancho/w3af/wiki/Developer's-Guide

**Comment by andresriancho** [comment]
For wappalizer plugin test I believe the best would be to create a couple of tests with `MOCK_RESPONSES`, see https://github.com/andresriancho/w3af/search?utf8=%E2%9C%93&q=MOCK_RESPONSES
