### ISSUE TITLE
typo in fingerprint_404.py?

### ISSUE THREAD

**Issue by Twi1ight** [andresriancho/w3af#12264]
w3af/core/controllers/core_helpers/fingerprint_404.py
line 141:  handlers = {'py', 'php', 'asp', 'aspx', 'do', 'jsp', 'rb', 'do',
there are two 'do' here, does one of them supposed to be 'action'?

**Comment by andresriancho** [comment]
Good find :+1: 

At the end it was just a typo since it's a set and duplicates are removed, but I took your advise and added the `action`
