### ISSUE TITLE
Dependency install script fails.

### ISSUE THREAD

**Issue by macubergeek** [andresriancho/w3af#12348]
On mac osx 10.10.5
---------------------------------------
When I try to run wf_console
I get:
Your python installation needs the following modules to run w3af:
    pyclamd github git.util pybloomfilter esmre phply nltk chardet tblib pdfminer concurrent.futures OpenSSL ndg pyasn1 lxml scapy.config guess_language cluster msgpack ntlm Halberd darts.lib.utils jinja2 vulndb markdown psutil mitmproxy ruamel.ordereddict Flask yaml

After installing any missing operating system packages, use pip to install the remaining modules:
    sudo pip install pyClamd==0.3.15 PyGithub==1.21.0 GitPython==0.3.2.RC1 pybloomfiltermmap==0.3.14 esmre==0.3.1 phply==0.9.1 nltk==3.0.1 chardet==2.1.1 tblib==0.2.0 pdfminer==20140328 futures==2.1.5 pyOpenSSL==0.15.1 ndg-httpsclient==0.3.3 pyasn1==0.1.8 lxml==3.4.4 scapy-real==2.2.0-dev guess-language==0.2 cluster==1.1.1b3 msgpack-python==0.4.4 python-ntlm==1.0.1 halberd==0.2.4 darts.util.lru==0.5 Jinja2==2.7.3 vulndb==0.0.19 markdown==2.6.1 psutil==2.2.1 mitmproxy==0.13 ruamel.ordereddict==0.4.8 Flask==0.10.1 PyYAML==3.11

A script with these commands has been created for you at /var/folders/7q/xm5qd4qs14l_y9zh6c6nn_400000gp/T/w3af_dependency_install.sh
----------------------------------------------------------
When I try and run /var/folders/7q/xm5qd4qs14l_y9zh6c6nn_400000gp/T/w3af_dependency_install.sh
I get:
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 9, in <module>
    load_entry_point('pip==7.1.1', 'console_scripts', 'pip')()
  File "/Library/Python/2.7/site-packages/pip-7.1.1-py2.7.egg/pip/__init__.py", line 217, in main
    return command.main(cmd_args)
  File "/Library/Python/2.7/site-packages/pip-7.1.1-py2.7.egg/pip/basecommand.py", line 182, in main
    for name in ["pip._vendor", "distlib", "requests", "urllib3"]
  File "/Library/Python/2.7/site-packages/pip-7.1.1-py2.7.egg/pip/compat/dictconfig.py", line 565, in dictConfig
    dictConfigClass(config).configure()
  File "/Library/Python/2.7/site-packages/pip-7.1.1-py2.7.egg/pip/compat/dictconfig.py", line 332, in configure
    del logging._handlerList[:]
AttributeError: 'module' object has no attribute '_handlerList'

I'm at a loss for understanding what the above means and what it's complaining about.

This is the contents of /usr/bin/pip
```
#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'pip==7.1.1','console_scripts','pip'
__requires__ = 'pip==7.1.1'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('pip==7.1.1', 'console_scripts', 'pip')()
    )
```

Any help would be appreciates.

**Comment by andresriancho** [comment]
This sounds a python/pip issue, not a w3af problem. Google for your pip bug

**Comment by anonusr** [comment]
Sounds like a simple issue with downloading and installing pip and python (prerequisites for w3af).  Here are instructions for convenience of others on teh internet:

#How to download & install pip: 
https://pip.pypa.io/en/stable/installing/

#Installing prerequisites for w3af: 
http://docs.w3af.org/en/latest/install.html
