### ISSUE TITLE
Any way to get vulnerabilities before scan finished?

### ISSUE THREAD

**Issue by kyprizel** [andresriancho/w3af#12443]
If we scan some huge service process can last for a long time, but what if we need to analayze results in real-time. Is there some way to stream scan results somewhere during the scan?
Thanks.

**Comment by andresriancho** [comment]
I believe this was recently implemented here https://github.com/andresriancho/w3af/issues/6726

**Comment by andresriancho** [comment]
Another way would be to write your own output plugin where you can do whatever you want. 

Yet another approach would be to write a https://github.com/andresriancho/w3af/blob/master/w3af/core/data/kb/kb_observer.py subclass (search for those in the code for examples)
