### ISSUE TITLE
Exception in thread GTKDraw

### ISSUE THREAD

**Issue by witnesone** [andresriancho/w3af#12682]
Exception in thread GTKDraw:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/w3af/w3af/core/ui/gui/scanrun.py", line 419, in _draw_real
    raise ValueError(msg % args)
ValueError: A ValueError exception with message "invalid literal for int() with base 10: '224.88'" was found while trying to render a new dotcode. Please create a new bug report at https://github.com/andresriancho/w3af/issues/new including the following info:

['"<GtkTreeIter at 0x3e5dee0>" [label="http://www.hillstone.com.au"]']

Running kali linux 2

root@aj:~# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 42
Model name:            Intel(R) Pentium(R) CPU G620 @ 2.60GHz
Stepping:              7
CPU MHz:               2599.898
CPU max MHz:           2600.0000
CPU min MHz:           1600.0000
BogoMIPS:              5188.07
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              3072K
NUMA node0 CPU(s):     0,1

**Comment by witnesone** [comment]
['"<GtkTreeIter at 0x3e5dee0>" [label="http://www.hillstone.com.au"]']

**Comment by andresriancho** [comment]
Dup https://github.com/andresriancho/w3af/issues/12906
