### ISSUE TITLE
NEED HELP CONFIGURING MY W3AF SET UP AND INSTALATION TICKET

### ISSUE THREAD

**Issue by marv-the-beast** [andresriancho/w3af#12691]
1.linux distribution
DISTRIB_ID=Kali
DISTRIB_RELEASE=2.0
DISTRIB_CODENAME=sana
DISTRIB_DESCRIPTION="Kali GNU/Linux 2.0"

2. The contents of the /tmp/w3af_dependency_install.sh file
Collecting lxml==3.4.4
  Using cached lxml-3.4.4.tar.gz
Collecting scapy-real==2.2.0-dev
Collecting vulndb==0.0.19
Collecting markdown==2.6.1
Collecting psutil==2.2.1
Building wheels for collected packages: lxml
  Running setup.py bdist_wheel for lxml
  Complete output from command /usr/bin/python -c "import setuptools;__file__='/tmp/pip-build-PLpWGl/lxml/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpSUSVAGpip-wheel-:
  /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
    warnings.warn(msg)
  Building lxml version 3.4.4.
  Building without Cython.
  ERROR: /bin/sh: 1: xslt-config: not found
  
  ** make sure the development packages of libxml2 and libxslt are installed **
  
  Using build configuration of libxslt
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-i686-2.7
  creating build/lib.linux-i686-2.7/lxml
  copying src/lxml/builder.py -> build/lib.linux-i686-2.7/lxml
  copying src/lxml/sax.py -> build/lib.linux-i686-2.7/lxml
  copying src/lxml/cssselect.py -> build/lib.linux-i686-2.7/lxml
  copying src/lxml/ElementInclude.py -> build/lib.linux-i686-2.7/lxml
  copying src/lxml/doctestcompare.py -> build/lib.linux-i686-2.7/lxml
  copying src/lxml/usedoctest.py -> build/lib.linux-i686-2.7/lxml
  copying src/lxml/__init__.py -> build/lib.linux-i686-2.7/lxml
  copying src/lxml/_elementpath.py -> build/lib.linux-i686-2.7/lxml
  copying src/lxml/pyclasslookup.py -> build/lib.linux-i686-2.7/lxml
  creating build/lib.linux-i686-2.7/lxml/includes
  copying src/lxml/includes/__init__.py -> build/lib.linux-i686-2.7/lxml/includes
  creating build/lib.linux-i686-2.7/lxml/html
  copying src/lxml/html/builder.py -> build/lib.linux-i686-2.7/lxml/html
  copying src/lxml/html/clean.py -> build/lib.linux-i686-2.7/lxml/html
  copying src/lxml/html/_html5builder.py -> build/lib.linux-i686-2.7/lxml/html
  copying src/lxml/html/usedoctest.py -> build/lib.linux-i686-2.7/lxml/html
  copying src/lxml/html/__init__.py -> build/lib.linux-i686-2.7/lxml/html
  copying src/lxml/html/html5parser.py -> build/lib.linux-i686-2.7/lxml/html
  copying src/lxml/html/ElementSoup.py -> build/lib.linux-i686-2.7/lxml/html
  copying src/lxml/html/_diffcommand.py -> build/lib.linux-i686-2.7/lxml/html
  copying src/lxml/html/soupparser.py -> build/lib.linux-i686-2.7/lxml/html
  copying src/lxml/html/_setmixin.py -> build/lib.linux-i686-2.7/lxml/html
  copying src/lxml/html/formfill.py -> build/lib.linux-i686-2.7/lxml/html
  copying src/lxml/html/defs.py -> build/lib.linux-i686-2.7/lxml/html
  copying src/lxml/html/diff.py -> build/lib.linux-i686-2.7/lxml/html
  creating build/lib.linux-i686-2.7/lxml/isoschematron
  copying src/lxml/isoschematron/__init__.py -> build/lib.linux-i686-2.7/lxml/isoschematron
  copying src/lxml/lxml.etree.h -> build/lib.linux-i686-2.7/lxml
  copying src/lxml/lxml.etree_api.h -> build/lib.linux-i686-2.7/lxml
  copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-i686-2.7/lxml/includes
  copying src/lxml/includes/config.pxd -> build/lib.linux-i686-2.7/lxml/includes
  copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-i686-2.7/lxml/includes
  copying src/lxml/includes/c14n.pxd -> build/lib.linux-i686-2.7/lxml/includes
  copying src/lxml/includes/tree.pxd -> build/lib.linux-i686-2.7/lxml/includes
  copying src/lxml/includes/xpath.pxd -> build/lib.linux-i686-2.7/lxml/includes
  copying src/lxml/includes/xinclude.pxd -> build/lib.linux-i686-2.7/lxml/includes
  copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-i686-2.7/lxml/includes
  copying src/lxml/includes/xslt.pxd -> build/lib.linux-i686-2.7/lxml/includes
  copying src/lxml/includes/uri.pxd -> build/lib.linux-i686-2.7/lxml/includes
  copying src/lxml/includes/relaxng.pxd -> build/lib.linux-i686-2.7/lxml/includes
  copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-i686-2.7/lxml/includes
  copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-i686-2.7/lxml/includes
  copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-i686-2.7/lxml/includes
  copying src/lxml/includes/schematron.pxd -> build/lib.linux-i686-2.7/lxml/includes
  copying src/lxml/includes/lxml-version.h -> build/lib.linux-i686-2.7/lxml/includes
  copying src/lxml/includes/etree_defs.h -> build/lib.linux-i686-2.7/lxml/includes
  creating build/lib.linux-i686-2.7/lxml/isoschematron/resources
  creating build/lib.linux-i686-2.7/lxml/isoschematron/resources/rng
  copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-i686-2.7/lxml/isoschematron/resources/rng
  creating build/lib.linux-i686-2.7/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-i686-2.7/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-i686-2.7/lxml/isoschematron/resources/xsl
  creating build/lib.linux-i686-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-i686-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-i686-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-i686-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-i686-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-i686-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-i686-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  running build_ext
  building 'lxml.etree' extension
  creating build/temp.linux-i686-2.7
  creating build/temp.linux-i686-2.7/src
  creating build/temp.linux-i686-2.7/src/lxml
  i586-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/tmp/pip-build-PLpWGl/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-i686-2.7/src/lxml/lxml.etree.o -w
  In file included from src/lxml/lxml.etree.c:239:0:
  /tmp/pip-build-PLpWGl/lxml/src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: No such file or directory
   #include "libxml/xmlversion.h"
                                 ^
  compilation terminated.
  error: command 'i586-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for lxml
Failed to build lxml
Installing collected packages: lxml, scapy-real, vulndb, markdown, psutil
  Found existing installation: lxml 3.4.0
    Uninstalling lxml-3.4.0:
      Successfully uninstalled lxml-3.4.0
  Running setup.py install for lxml
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-PLpWGl/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-CP0MyW-record/install-record.txt --single-version-externally-managed --compile:
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    Building lxml version 3.4.4.
    Building without Cython.
    ERROR: /bin/sh: 1: xslt-config: not found
    
    ** make sure the development packages of libxml2 and libxslt are installed **
    
    Using build configuration of libxslt
    running install
    running build
    running build_py
    copying src/lxml/includes/lxml-version.h -> build/lib.linux-i686-2.7/lxml/includes
    running build_ext
    building 'lxml.etree' extension
    i586-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/tmp/pip-build-PLpWGl/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-i686-2.7/src/lxml/lxml.etree.o -w
    In file included from src/lxml/lxml.etree.c:239:0:
    /tmp/pip-build-PLpWGl/lxml/src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: No such file or directory
     #include "libxml/xmlversion.h"
                                   ^
    compilation terminated.
    error: command 'i586-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of lxml
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-PLpWGl/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-CP0MyW-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-PLpWGl/lxml

3. The output of pip freeze
adns-python==1.2.1
apsw==3.8.6.post1
argcomplete==0.8.1
async==0.6.1
BBQSQL==1.0
BeautifulSoup==3.2.1
beautifulsoup4==4.3.2
binwalk==2.0.0
BlindElephant==1.0
blinker==1.3
capstone==3.0
certifi==2015.4.28
cffi==0.8.6
characteristic==0.1.0
chardet==2.1.1
Cheetah==2.4.4
chirp==0.4.0
clamd==1.0.1
cluster==1.1.1b3
colorama==0.3.2
ConfigArgParse==0.9.3
configobj==5.0.6
configparser==3.3.0.post2
cryptography==0.9.3
cssselect==0.9.1
ctypeslib==0.5.6
d2to1==0.2.11
darts.util.lru==0.5
decorator==3.4.0
defusedxml==0.4.1
dicttoxml==1.6.6
dissy==9
distorm3==3
dnspython==1.12.0
docutils==0.12
easygui==0.96
ecdsa==0.11
Elixir==0.7.1
enum34==1.0.3
esmre==0.3.1
feedparser==5.1.3
Flask==0.10.1
flickrapi==1.2
funkload==1.16.1
fuse-python==0.2.1
futures==2.1.5
GeoIP==1.3.2
gevent==1.0.1
gitdb==0.5.4
github3.py==0.9.4
GitPython==0.3.2rc1
greenlet==0.4.2
guess-language==0.2
halberd==0.2.4
hpack==1.1.0
html2text==2015.6.21
html5lib==0.999
httplib2==0.9
idna==2.0
impacket==0.9.12
ipaddress==1.0.14
IPy==0.81
ipython==0.13.1
itsdangerous==0.24
Jinja2==2.7.3
jsonpickle==0.8.0
jsonrpclib==0.1.3
keepnote==0.7.8
killerbee==1.0
logilab-astng==0.23.1
logilab-common==0.58.0
lxml==3.4.0
M2Crypto==0.21.1
Magic-file-extensions==0.2
Mako==1.0.0
Markdown==2.5.1
MarkupSafe==0.23
matplotlib==1.4.2
mechanize==0.2.5
mercurial==3.1.2
metaconfig==0.1.4a1
mitmproxy==0.13
mock==1.0.1
msgpack-python==0.4.4
MySQL-python==1.2.3
ndg-httpsclient==0.3.3
netaddr==0.7.12
netlib==0.13.1
networkx==1.9
NfSpy==1.0
nltk==3.0.1
nose==1.3.4
numpy==1.8.2
oauth==1.0.1
openpyxl==1.7.0
PAM==0.4.2
paramiko==1.15.1
passlib==1.6.1
pcapy==0.10.8
pdfminer==20140328
pefile==1.2.9.1
pep8==1.2
pexpect==3.2
phply==0.9.1
Pillow==2.6.1
ply==3.4
prettytable==0.7.2
psutil==2.1.1
psycopg2==2.5.4
pyasn1==0.1.8
pyasn1-modules==0.0.5
pybloomfiltermmap==0.3.14
PyBluez==0.18
pyClamd==0.3.15
pycparser==2.10
pycrypto==2.6.1
pycryptopp==0.6.0.1206569328141510525648634803928199668821045408958
pycups==1.9.63
pycurl==7.19.5
pydns==2.3.6
pyflakes==0.5.0
PyGithub==1.21.0
Pygments==2.0.1
pygobject==3.14.0
pygraphviz==1.3rc2
pyinotify==0.9.4
pylint==0.25.1
pymssql==1.0.2
PyOpenGL==3.0.2
pyOpenSSL==0.15.1
pyparsing==2.0.3
pyPdf==1.13
pyperclip==1.5.11
pyqtgraph==0.0.0
pyregfi==99.99.99.277
pyrit==0.4.0
pyrtlsdr==0.1.1
pyscard==1.6.14
pyserial==2.6
pysmbc==1.0.15.3
pysnmp==4.2.5
pysnmp-apps==0.3.2
pysnmp-mibs==0.1.3
PySocks==1.5.0
pysqlite==2.6.3
python-apt==0.9.3.11
python-dateutil==2.2
python-debian==0.1.27
python-debianbts==1.11
python-Levenshtein==0.11.2
python-ntlm==1.0.1
pytidylib==0.2.1
pytz==2012rc0
pyusb==1.0.0a3
PyX==0.12.1
pyxdg==0.25
PyYAML==3.11
pyzmq==14.4.0
queuelib==1.4.2
reportbug==6.6.3
requests==2.7.0
rfidiot==1.0
roman==2.0.0
rope==0.9.2
ruamel.ordereddict==0.4.8
scapy==2.2.0
scipy==0.14.0
Scrapy==1.0.3
service-identity==1.0.0
simplegeneric==0.8.1
simplejson==3.6.5
six==1.8.0
slowaes==0.1a1
smmap==0.8.2
SOAPpy==0.12.22
spyder==2.1.10
SQLAlchemy==0.9.8
stopit==1.1.0
tblib==0.2.0
tornado==4.2
tweepy==2.3
Twisted==14.0.2
Twisted-Conch==14.0.2
Twisted-Core==14.0.2
Twisted-Lore==14.0.2
Twisted-Mail==14.0.2
Twisted-Names==14.0.2
Twisted-News==14.0.2
Twisted-Runner==14.0.2
Twisted-Web==14.0.2
Twisted-Words==14.0.2
uritemplate.py==0.3.0
urllib3==1.10.4
urwid==1.3.0
uTidylib==0.2
volatility==2.4
vulndb==0.0.17
w3lib==1.12.0
wapiti==2.3.0
webunit==1.3.10
Werkzeug==0.9.6
wheel==0.24.0
wstools==0.4.3
wxPython==3.0.1.1
wxPython-common==3.0.1.1
xdot==0.5
XlsxWriter==0.5.2
xsser==1.6
Yapsy==1.10.423
yara-python==3.1
zenmap==6.49b4
zim==0.62
zope.interface==4.1.1

4. the output of python --version
Python 2.7.9

PLEASE HELP,  YOUR FEEDBACK WILL HIGHLY BE APPRECIATED

**Comment by andresriancho** [comment]
libxml/xmlversion.h is missing

solution:

apt-get install libxml2-dev libxslt1-dev python-dev
