### ISSUE TITLE
w3af still says I have missing operating system dependencies

### ISSUE THREAD

**Issue by ahmarcia** [andresriancho/w3af#12707]
Mac OS X Yosemite 10.10.5

./w3af_gui 
Your python installation needs the following modules to run w3af:
    pyclamd github git.util pybloomfilter esmre phply nltk chardet tblib pdfminer concurrent.futures OpenSSL ndg pyasn1 lxml scapy.config guess_language cluster msgpack ntlm Halberd darts.lib.utils jinja2 vulndb markdown psutil mitmproxy ruamel.ordereddict Flask yaml xdot

After installing any missing operating system packages, use pip to install the remaining modules:
    sudo pip install pyClamd==0.3.15 PyGithub==1.21.0 GitPython==0.3.2.RC1 pybloomfiltermmap==0.3.14 esmre==0.3.1 phply==0.9.1 nltk==3.0.1 chardet==2.1.1 tblib==0.2.0 pdfminer==20140328 futures==2.1.5 pyOpenSSL==0.15.1 ndg-httpsclient==0.3.3 pyasn1==0.1.8 lxml==3.4.4 scapy-real==2.2.0-dev guess-language==0.2 cluster==1.1.1b3 msgpack-python==0.4.4 python-ntlm==1.0.1 halberd==0.2.4 darts.util.lru==0.5 Jinja2==2.7.3 vulndb==0.0.19 markdown==2.6.1 psutil==2.2.1 mitmproxy==0.13 ruamel.ordereddict==0.4.8 Flask==0.10.1 PyYAML==3.11 xdot==0.6

A script with these commands has been created for you at /var/folders/ff/cfj54p2118532hb9yc2b1nwm0000gn/T/w3af_dependency_install.sh
The GTK package requirements are not met, please make sure your system meets these requirements:
    - PyGTK >= 2.12
    - GTK >= 2.12

/tmp/w3af_dependency_install.sh

sudo pip install pyClamd==0.3.15 PyGithub==1.21.0 GitPython==0.3.2.RC1 pybloomfiltermmap==0.3.14 esmre==0.3.1 phply==0.9.1 nltk==3.0.1 chardet==2.1.1 tblib==0.2.0 pdfminer==20140328 futures==2.1.5 pyOpenSSL==0.15.1 ndg-httpsclient==0.3.3 pyasn1==0.1.8 lxml==3.4.4 scapy-real==2.2.0-dev guess-language==0.2 cluster==1.1.1b3 msgpack-python==0.4.4 python-ntlm==1.0.1 halberd==0.2.4 darts.util.lru==0.5 Jinja2==2.7.3 vulndb==0.0.19 markdown==2.6.1 psutil==2.2.1 mitmproxy==0.13 ruamel.ordereddict==0.4.8 Flask==0.10.1 PyYAML==3.11
Password:
The directory '/Users/aang/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/aang/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): pyClamd==0.3.15 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): PyGithub==1.21.0 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): GitPython==0.3.2.RC1 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pybloomfiltermmap==0.3.14 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): esmre==0.3.1 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): phply==0.9.1 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): nltk==3.0.1 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): chardet==2.1.1 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): tblib==0.2.0 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pdfminer==20140328 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): futures==2.1.5 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pyOpenSSL==0.15.1 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): ndg-httpsclient==0.3.3 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pyasn1==0.1.8 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): lxml==3.4.4 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): scapy-real==2.2.0-dev in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): guess-language==0.2 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): cluster==1.1.1b3 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): msgpack-python==0.4.4 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): python-ntlm==1.0.1 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): halberd==0.2.4 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): darts.util.lru==0.5 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.7.3 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): vulndb==0.0.19 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): markdown==2.6.1 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): psutil==2.2.1 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): mitmproxy==0.13 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): ruamel.ordereddict==0.4.8 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): Flask==0.10.1 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): PyYAML==3.11 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): gitdb>=0.5.1 in /Library/Python/2.7/site-packages (from GitPython==0.3.2.RC1)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from esmre==0.3.1)
Requirement already satisfied (use --upgrade to upgrade): ply in /Library/Python/2.7/site-packages (from phply==0.9.1)
Requirement already satisfied (use --upgrade to upgrade): six in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from tblib==0.2.0)
Requirement already satisfied (use --upgrade to upgrade): cryptography>=0.7 in /Library/Python/2.7/site-packages (from pyOpenSSL==0.15.1)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /Library/Python/2.7/site-packages (from Jinja2==2.7.3)
Requirement already satisfied (use --upgrade to upgrade): pyperclip>=1.5.8 in /Library/Python/2.7/site-packages (from mitmproxy==0.13)
Requirement already satisfied (use --upgrade to upgrade): tornado>=4.0.2 in /Library/Python/2.7/site-packages (from mitmproxy==0.13)
Requirement already satisfied (use --upgrade to upgrade): netlib<0.14,>=0.13 in /Library/Python/2.7/site-packages (from mitmproxy==0.13)
Requirement already satisfied (use --upgrade to upgrade): urwid>=1.3 in /Library/Python/2.7/site-packages (from mitmproxy==0.13)
Requirement already satisfied (use --upgrade to upgrade): blinker>=1.3 in /Library/Python/2.7/site-packages (from mitmproxy==0.13)
Requirement already satisfied (use --upgrade to upgrade): Pillow>=2.3.0 in /Library/Python/2.7/site-packages (from mitmproxy==0.13)
Requirement already satisfied (use --upgrade to upgrade): pyparsing>=1.5.2 in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from mitmproxy==0.13)
Requirement already satisfied (use --upgrade to upgrade): configargparse>=0.9.3 in /Library/Python/2.7/site-packages (from mitmproxy==0.13)
Requirement already satisfied (use --upgrade to upgrade): html2text>=2015.4.14 in /Library/Python/2.7/site-packages (from mitmproxy==0.13)
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /Library/Python/2.7/site-packages (from Flask==0.10.1)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /Library/Python/2.7/site-packages (from Flask==0.10.1)
Requirement already satisfied (use --upgrade to upgrade): smmap>=0.8.5 in /Library/Python/2.7/site-packages (from gitdb>=0.5.1->GitPython==0.3.2.RC1)
Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in /Library/Python/2.7/site-packages (from cryptography>=0.7->pyOpenSSL==0.15.1)
Requirement already satisfied (use --upgrade to upgrade): enum34 in /Library/Python/2.7/site-packages (from cryptography>=0.7->pyOpenSSL==0.15.1)
Requirement already satisfied (use --upgrade to upgrade): ipaddress in /Library/Python/2.7/site-packages (from cryptography>=0.7->pyOpenSSL==0.15.1)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.1.0 in /Library/Python/2.7/site-packages (from cryptography>=0.7->pyOpenSSL==0.15.1)
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname in /Library/Python/2.7/site-packages (from tornado>=4.0.2->mitmproxy==0.13)
Requirement already satisfied (use --upgrade to upgrade): certifi in /Library/Python/2.7/site-packages (from tornado>=4.0.2->mitmproxy==0.13)
Requirement already satisfied (use --upgrade to upgrade): passlib>=1.6.2 in /Library/Python/2.7/site-packages (from netlib<0.14,>=0.13->mitmproxy==0.13)
Requirement already satisfied (use --upgrade to upgrade): hpack>=1.0.1 in /Library/Python/2.7/site-packages (from netlib<0.14,>=0.13->mitmproxy==0.13)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /Library/Python/2.7/site-packages (from cffi>=1.1.0->cryptography>=0.7->pyOpenSSL==0.15.1)

pip freeze
altgraph==0.10.2
backports.ssl-match-hostname==3.4.0.2
bdist-mpkg==0.5.0
blinker==1.4
bonjour-py==0.3
certifi==2015.9.6.2
cffi==1.2.1
chardet==2.1.1
clamd==1.0.1
cluster==1.1.1b3
ConfigArgParse==0.9.3
cryptography==1.0.1
darts.util.lru==0.5
enum34==1.0.4
esmre==0.3.1
Flask==0.10.1
futures==2.1.5
gitdb==0.6.4
GitPython==0.3.2rc1
guess-language==0.2
halberd==0.2.4
hpack==1.1.0
html2text==2015.6.21
idna==2.0
ipaddress==1.0.14
itsdangerous==0.24
Jinja2==2.7.3
lxml==3.4.4
macholib==1.5.1
Markdown==2.6.1
MarkupSafe==0.23
matplotlib==1.3.1
mitmproxy==0.13
modulegraph==0.10.4
msgpack-python==0.4.4
ndg-httpsclient==0.3.3
netlib==0.13.1
nltk==3.0.1
numpy==1.8.0rc1
passlib==1.6.5
pdfminer==20140328
phply==0.9.1
Pillow==2.9.0
ply==3.6
psutil==2.2.1
py2app==0.7.3
pyasn1==0.1.8
pybloomfilter==1.0
pybloomfiltermmap==0.3.14
pyClamd==0.3.15
pycparser==2.14
PyGithub==1.21.0
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==0.15.1
pyparsing==2.0.1
pyperclip==1.5.12
python-dateutil==1.5
python-ntlm==1.0.1
pytz==2013.7
PyYAML==3.11
ruamel.ordereddict==0.4.8
scapy-real==2.2.0.dev0
scipy==0.13.0b1
six==1.4.1
smmap==0.9.0
tblib==0.2.0
tornado==4.2.1
Twisted==13.2.0
urwid==1.3.0
vboxapi==1.0
vulndb==0.0.19
Werkzeug==0.10.4
xattr==0.6.4
xdot==0.6
zope.interface==4.1.1

python --version
Python 2.7.10

**Comment by andresriancho** [comment]
Let me know if http://docs.w3af.org/en/latest/install.html#installation-in-mac-osx still works.

If it doesn't, please re-open this issue and I'll modify the docs

**Comment by cbrody** [comment]
Installation does not want to work on Mac OSX 10.13.1 (High Sierra). w3af_gui and w3af_console both state that the following modules are needed:

pyclamd github git.util pybloomfilter esmre phply nltk chardet tblib pdfminer concurrent.futures OpenSSL ndg pyasn1 lxml scapy.config guess_language cluster msgpack ntlm Halberd darts.lib.utils jinja2 vulndb markdown psutil termcolor mitmproxy ruamel.ordereddict Flask yaml tldextract pebble

But running the w3af_dependency_install.sh script results in "Requirement already satisfied" for all of them. Any tips?

**Comment by bellinom** [comment]
I have the same issue on Kali Linux, but the only module it says is still needed is psutil==2.2.1, which is already installed.

**Comment by Mohammed-Nawazuddin** [comment]
I also get this same problem, can someone help me?

mds-macbook-pro:w3af mdnawazuddin$ ./w3af_console
. /tmp/w3af_dependency_install.sh
Your python installation needs the following modules to run w3af:
    pyclamd github git.util pybloomfilter esmre phply nltk chardet tblib pdfminer concurrent.futures OpenSSL ndg pyasn1 lxml scapy.config guess_language cluster msgpack ntlm Halberd darts.lib.utils jinja2 vulndb markdown psutil termcolor mitmproxy ruamel.ordereddict Flask yaml tldextract pebble


After installing any missing operating system packages, use pip to install the remaining modules:
    sudo pip install pyClamd==0.3.15 PyGithub==1.21.0 GitPython==2.1.3 pybloomfiltermmap==0.3.14 esmre==0.3.1 phply==0.9.1 nltk==3.0.1 chardet==3.0.4 tblib==0.2.0 pdfminer==20140328 futures==2.1.5 pyOpenSSL==0.15.1 ndg-httpsclient==0.3.3 pyasn1==0.2.3 lxml==3.4.4 scapy-real==2.2.0-dev guess-language==0.2 cluster==1.1.1b3 msgpack-python==0.4.4 python-ntlm==1.0.1 halberd==0.2.4 darts.util.lru==0.5 Jinja2==2.7.3 vulndb==0.0.19 markdown==2.6.1 psutil==2.2.1 termcolor==1.1.0 mitmproxy==0.13 ruamel.ordereddict==0.4.8 Flask==0.10.1 PyYAML==3.12 tldextract==1.7.2 pebble==4.3.2

A script with these commands has been created for you at /var/folders/py/ff6s1nm93l3d26d2bb2f403m0000gn/T/w3af_dependency_install.sh

**Comment by adojaan** [comment]
Kind of similar dependency problem here - pip cannot install webkit. 
I installed OS dependencies and then ran the script. 
Traceback (most recent call last):
  File "./w3af_gui", line 110, in <module>
    _main()
  File "./w3af_gui", line 106, in _main
    sys.exit(main())
  File "./w3af_gui", line 100, in main
    from w3af.core.ui.gui.main import main as gui_main
  File "/home/kristjan/bin/w3af/w3af/core/ui/gui/main.py", line 54, in <module>
    from w3af.core.ui.gui import scanrun, helpers, profiles, compare
  File "/home/kristjan/bin/w3af/w3af/core/ui/gui/scanrun.py", line 27, in <module>
    import webkit
ImportError: No module named webkit

and when I try to pip install it manually
Collecting webkit
  Could not find a version that satisfies the requirement webkit (from versions: )
No matching distribution found for webkit
