### ISSUE TITLE
There's no response for w3af gui when running xss test on kali 2 platform.

### ISSUE THREAD

**Issue by xjtulg** [andresriancho/w3af#12712]
Exception in thread GTKDraw:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/w3af/w3af/core/ui/gui/scanrun.py", line 419, in _draw_real
    raise ValueError(msg % args)
ValueError: A ValueError exception with message "invalid literal for int() with base 10: '198.88'" was found while trying to render a new dotcode. Please create a new bug report at https://github.com/andresriancho/w3af/issues/new including the following info:

['"<GtkTreeIter at 0x48af940>" [label="http://xxxxx"]']

GET http://xxxxx/ returned HTTP code "200" (id=34,from_cache=0,grep=0)
xss plugin is testing: "Method: GET | http://xxxxx/"
Starting plugin: audit.xss
Created 0 mutants for "Method: GET | http://xxxx/" ()
GET http://xxxxxx/ returned HTTP code "200" (id=35,from_cache=0,grep=0)
Scan finished in 5 seconds.
Stopping the core...
Exception in thread GTKDraw:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/w3af/w3af/core/ui/gui/scanrun.py", line 419, in _draw_real
    raise ValueError(msg % args)
ValueError: A ValueError exception with message "invalid literal for int() with base 10: '198.88'" was found while trying to render a new dotcode. Please create a new bug report at https://github.com/andresriancho/w3af/issues/new including the following info:

['"<GtkTreeIter at 0x48af940>" [label="http://xxxxx"]']

GET http://xxxxx/ returned HTTP code "200" (id=34,from_cache=0,grep=0)
xss plugin is testing: "Method: GET | http://xxxxx/"
Starting plugin: audit.xss
Created 0 mutants for "Method: GET | http://xxxxx/" ()
GET http://xxxxxx/ returned HTTP code "200" (id=35,from_cache=0,grep=0)
Scan finished in 5 seconds.
Stopping the core...

**Comment by andresriancho** [comment]
Dup https://github.com/andresriancho/w3af/issues/12906
