### ISSUE TITLE
running on Kali 2.0 amd64 app freezes

### ISSUE THREAD

**Issue by deepgray** [andresriancho/w3af#12776]
started a simple scan (OWASP 10 against OWASP Broken Web Apps Gruyere site and got to the "The page is written in "en" then froze.

**Comment by andresriancho** [comment]
What about the console UI? Did you try with that?

When running with the GUI, does it use 100% CPU? How long did the UI froze?

**Comment by deepgray** [comment]
python shows to be using 111% of CPU in top..and stays there.

on Kali 1.1.0a it varies around 130 % of CPU but continues working.

the UI froze for a while...i gave up at 5 minutes...there was no freeze on kali 1.

**Comment by andresriancho** [comment]
Is this the same w3af version in different Kali versions? Which w3af version?

**Comment by deepgray** [comment]
both platforms have w3af version 1.6.54

**Comment by deepgray** [comment]
the only difference is most likely the kernel that Kali 2 uses versus Kali 1.

**Comment by andresriancho** [comment]
I believe this is not an issue with kali or it's packaging, its an issue with the "old" w3af version packaged in kali. I'll work on this soon at https://github.com/andresriancho/w3af/issues/10821
