### ISSUE TITLE
Install w3af on centos 7 error

### ISSUE THREAD

**Issue by chomyeong** [andresriancho/w3af#12782]
My linux distribution:
CentOS Linux release 7.1.1503 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.1.1503 (Core) 
CentOS Linux release 7.1.1503 (Core) 

[root@chomyeong w3af]# . /tmp/w3af_dependency_install.sh
Requirement already satisfied (use --upgrade to upgrade): xdot==0.6 in /usr/lib/python2.7/site-packages
pip freeze:
backports.ssl-match-hostname==3.4.0.2
Beaker==1.5.4
blinker==1.4
blivet==0.61.0.26
Brlapi==0.6.0
certifi==2015.9.6.2
cffi==1.2.1
chardet==2.1.1
cluster==1.1.1b3
ConfigArgParse==0.9.3
configobj==4.7.2
configshell-fb==1.1.14
coverage==3.6b3
cryptography==1.0.2
cupshelpers==1.0
darts.util.lru==0.5
decorator==3.4.0
di==0.3
dnspython==1.11.1
enum34==1.0.4
esmre==0.3.1
ethtool==0.8
firstboot==19.5
Flask==0.10.1
freeipa==2.0.0a0
fros==1.0
futures==2.1.5
gitdb==0.6.4
GitPython==0.3.2rc1
glusterfs-api==3.6.0.29
guess-language==0.2
halberd==0.2.4
hpack==1.1.0
html2text==2015.6.21
idna==2.0
iniparse==0.4
initial-setup==0.3.9.23
ipaddress==1.0.14
ipaplatform==4.1.0
ipapython==4.1.0
IPy==0.75
itsdangerous==0.24
javapackages==1.0.0
Jinja2==2.7.3
kerberos==1.1
kitchen==1.1.1
kmod==0.1
langtable==0.0.13
lxml==3.4.4
Mako==0.8.1
Markdown==2.6.1
MarkupSafe==0.11
mitmproxy==0.13
msgpack-python==0.4.4
ndg-httpsclient==0.3.3
netaddr==0.7.5
netlib==0.13.1
nltk==3.0.1
passlib==1.6.5
Paste==1.7.5.1
pdfminer==20140328
phply==0.9.1
Pillow==2.9.0
ply==3.6
policycoreutils-default-encoding==0.1
psutil==2.2.1
pyasn1==0.1.8
pybloomfiltermmap==0.3.14
pyClamd==0.3.15
pycparser==2.14
pycups==1.9.63
pycurl==7.19.0
PyGithub==1.21.0
pygobject==3.8.2
pygpgme==0.3
pyinotify==0.9.4
pykickstart==1.99.43.17
pyliblzma==0.5.3
pyOpenSSL==0.15.1
pyparsing==1.5.6
pyparted==3.9
pyperclip==1.5.13
python-augeas==0.4.1
python-dateutil==1.5
python-default-encoding==0.1
python-dmidecode==3.10.13
python-ldap==2.4.15
python-meh==0.25.2
python-nss==0.16.0
python-ntlm==1.0.1
python-yubico==1.2.1
pytz===2012d
pyudev==0.15
pyusb==1.0.0b1
pyxattr==0.5.1
PyYAML==3.11
qrcode==5.0.1
rtslib-fb==2.1.50
ruamel.ordereddict==0.4.8
scapy-real==2.2.0.dev0
seobject==0.1
sepolicy==1.1
setroubleshoot==1.1
six==1.9.0
slip==0.4.0
slip.dbus==0.4.0
smmap==0.9.0
SSSDConfig==1.12.2
targetcli-fb===2.1.fb37
tblib==0.2.0
Tempita==0.5.1
tornado==4.2.1
urlgrabber==3.10
urwid==1.3.0
vulndb==0.0.19
Werkzeug==0.10.4
wheel==0.26.0
xdot==0.6
yum-langpacks==0.4.2
yum-metadata-parser==1.1.4

My python version:
Python 2.7.5

When I run w3af get the error,
[root@chomyeong w3af]# ./w3af_gui 
Traceback (most recent call last):
  File "./w3af_gui", line 110, in <module>
    _main()
  File "./w3af_gui", line 106, in _main
    sys.exit(main())
  File "./w3af_gui", line 100, in main
    from w3af.core.ui.gui.main import main as gui_main
  File "/home/chomyeong/w3af/w3af/core/ui/gui/main.py", line 54, in <module>
    from w3af.core.ui.gui import scanrun, helpers, profiles, compare
  File "/home/chomyeong/w3af/w3af/core/ui/gui/scanrun.py", line 27, in <module>
    import webkit
ImportError: No module named webkit
What can I do? help me ,thanks!

**Comment by andresriancho** [comment]
Did you try to install a RPM that provides webkit?

**Comment by chomyeong** [comment]
I didn't,but how can i do it?
