### ISSUE TITLE
XML Report - null byte being used in XML 

### ISSUE THREAD

**Issue by zmetcalf** [andresriancho/w3af#12924]
When the LFI plugin generates errors and the report is generated in XML, the errors listed in the XML contain null bytes.

**Comment by andresriancho** [comment]
@zmetcalf thanks for the bug report. Which w3af version are you using? I remember we fixed some null byte bugs in the xml output a while ago.

**Comment by andresriancho** [comment]
[This is the code related to handling null bytes](https://github.com/andresriancho/w3af/blob/master/w3af/plugins/output/xml_file.py#L242-L257) in the xml output, but it only seems to affect http response bodies

**Comment by andresriancho** [comment]
Do you have a way for me to reproduce this issue?

**Comment by zmetcalf** [comment]
No problem and thank you for the great project. I encountered the error using the most recent commit. I received the errors as an HTTP timeout error; the test that I was running was the OWASP Top 10
```
<error caller="threading">The lfi plugin got an error while requesting &quot;http://192.168.33.10/DVWA/vulnerabilities/?mode=../../../../../../../../../../../../../../../boot.ini

null byte

.html&quot;. Reason: &quot;HTTP timeout error&quot;</error>
```

Are you able to slow down a VM target to create the HTTP timeout errors? The target I used was simply ScotchIO's LAMP stack with DVWA loaded on it.

**Comment by andresriancho** [comment]
With that info I'll be able to fix, thanks!

> Are you able to slow down a VM target to create the HTTP timeout errors?

Not related to this issue, but for timeout testing we use custom made (broken) web servers, see https://github.com/andresriancho/w3af/blob/master/w3af/core/data/url/tests/test_xurllib_timeout.py
