### ISSUE TITLE
TypeError exception in auth.generic

### ISSUE THREAD

**Issue by LocutusOfBorg** [andresriancho/w3af#12967]
A "TypeError" exception was found while running auth.generic on "None". The exception was: "The uri parameter of ExtendedUrllib.POST() must be of url.URL type." at extended_urllib.py:POST():649. The scan will continue but some vulnerabilities might not be identified.

A "TypeError" exception was found while running auth.generic on "None". The exception was: "The uri parameter of ExtendedUrllib.POST() must be of url.URL type." at extended_urllib.py:POST():649.The full traceback is:
```pytb
  File "/home/user/w3af/w3af/core/controllers/core_helpers/consumers/auth.py", line 94, in _login
    plugin.login()
  File "/home/user/w3af/w3af/plugins/auth/generic.py", line 52, in login
    return self.do_user_login()
  File "/home/user/w3af/w3af/plugins/auth/generic.py", line 73, in do_user_login
    self._uri_opener.POST(self.auth_url, data=data)
  File "/home/user/w3af/w3af/core/controllers/plugins/plugin.py", line 278, in url_opener_proxy
    return attr(*args, **kwargs)
  File "/home/user/w3af/w3af/core/data/url/extended_urllib.py", line 649, in POST
    raise TypeError('The uri parameter of ExtendedUrllib.POST() must'
```
this comes from Debian w3af (development branch) with the Debian dependencies.

differences in versions are listed below
pygithub 1.21.0 1.25.2
gitpython 0.3.2rc1 1.0.1
nltk 3.0.1 3.1
chardet 2.1.1 2.3.0
tblib 0.2.0 1.1.0
futures 2.1.5 3.0.3
ndg-httpsclient 0.3.3 0.4.0
pyasn1 0.1.8 0.1.9
scapy-real 3.4.4 3.4.4
guess-language 3.4.4 3.4.4
msgpack-python 0.4.4 0.4.6
jinja2 2.7.3 2.8
markdown 2.6.1 2.6.3
ruamel.ordereddict 0.4.8 0.4.9

thanks.

**Comment by andresriancho** [comment]
@LocutusOfBorg this sounds familiar, I believe I've fixed this, are you using the latest w3af from github repo?

**Comment by LocutusOfBorg** [comment]
I was using the latest git snapshot of 6 days ago. but I can try again

**Comment by andresriancho** [comment]
The uri parameter of ExtendedUrllib.POST() must be of url.URL type #2349

**Comment by andresriancho** [comment]
I believe this issue was fixed but the code didn't make it to master yet
https://github.com/andresriancho/w3af/commit/ebb10d31036ea9bc3b6b3a3fc10931ec99b8848b
