### ISSUE TITLE
Change w3af_console / w3af_gui shebang to 2.7

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#13012]
See https://github.com/andresriancho/w3af/pull/13005#issuecomment-155129588 where @matthew9012 says:

> If Python 2.7 is required, why not make the top line
#!/usr/bin/env python2.7
rather than
#!/usr/bin/env python

>python is usually symbolically linked to the latest python version (3.5.0 in my case).

> Just for people like me that don't read :P

My only doubt is if all linux/mac systems have python2.7

**Comment by andresriancho** [comment]
https://github.com/sqlmapproject/sqlmap/pull/1246

**Comment by andresriancho** [comment]
Solving issue the best possible way:
 * w3af runs ok when python2.7 is the default
 * w3af shows this message when python3 is used:
```
It seems that you are running w3af using Python3, which is not officially supported by the w3af team.
To force w3af to be run using python2.7 run it as follows (depending on your OS):

 * python2.7 w3af_console
 * python2 w3af_console

To make this change permanent modify the shebang line in the w3af_console, w3af_gui and w3af_api scripts.
```

PS: @matthew9012 please review

**Comment by matthew9012** [comment]
That solution is fine.
