### ISSUE TITLE
mac os x10.11.1 (15B42), w3af is always asking me to install the modules!

### ISSUE THREAD

**Issue by lendh327** [andresriancho/w3af#13016]
mac os x10.11.1
The contents of the /tmp/w3af_dependency_install.sh file:
```bash
sudo pip install pyClamd==0.3.15 PyGithub==1.21.0 GitPython==0.3.2.RC1 pybloomfiltermmap==0.3.14 esmre==0.3.1 phply==0.9.1 nltk==3.0.1 chardet==2.1.1 tblib==0.2.0 pdfminer==20140328 futures==2.1.5 pyOpenSSL==0.15.1 ndg-httpsclient==0.3.3 lxml==3.4.4 scapy-real==2.2.0-dev guess-language==0.2 cluster==1.1.1b3 msgpack-python==0.4.4 python-ntlm==1.0.1 halberd==0.2.4 darts.util.lru==0.5 Jinja2==2.7.3 vulndb==0.0.19 markdown==2.6.1 psutil==2.2.1 mitmproxy==0.13 ruamel.ordereddict==0.4.8 Flask==0.10.1 PyYAML==3.11
```
The output of pip freeze: futures==2.1.5
The output of python --version:Python 2.7.10
I have installed all the modules, but I still con't run ./w3af_console

**Comment by andresriancho** [comment]
If pip freeze output is just the futures module, then you have a problem: you're not installing the dependencies in the right way.

Something that I've heard is that in mac there are two python versions, make sure you install the dependencies in the same python you use to run w3af
