### ISSUE TITLE
Expected scan_profile in JSON object

### ISSUE THREAD

**Issue by ashwinreddymekala** [andresriancho/w3af#13323]
when I post request to /scans/ result look like this.

Data : 
{
    "target_urls":["https://google.com"],
    "scan_profile": "[grep.strange_headers]\n\n[crawl.web_spider]\nonly_forward = False\nfollow_regex = .*\nignore_regex = \n\n"
}

Output :
{
    "message": "Expected scan_profile in JSON object",
    "code": 400
}

I followed http://docs.w3af.org/en/latest/api/scans.html#starting-a-scan & used Postman extension on chrome. No where in docs says to post scan_profile in JSON, is there any thing wrong data I've posted?

![image](https://cloud.githubusercontent.com/assets/9305040/12222646/b3346348-b787-11e5-8d80-fae298abd1f7.png)

**Comment by ashwinreddymekala** [comment]
My bad I didn't add JSON headers. issue solved!

**Comment by andresriancho** [comment]
To make things easier for other users, the error message should be clearer. Something like: "Content-Type header must be application/json"
