### ISSUE TITLE
XSS plugin in devel branch generates a lot of false positives

### ISSUE THREAD

**Issue by kyprizel** [andresriancho/w3af#13359]
New version of module  desides that echoing ``:`` leads to XSS, but it'll generate false positive in all the cases except when ``:`` used in href schema. ``" ="`` token also does not look dangerous.
May be we should add more checks to the parser?

Example target generating false positives:
https://dvwa.people.yandex.net/xss.php

**Comment by andresriancho** [comment]
Could you show us a set of HTML responses which generate false positives?

**Comment by kyprizel** [comment]
http://dvwa.people.yandex.net/xss.php?test=xczab%3Axczab

**Comment by andresriancho** [comment]
@kyprizel I just fixed this in develop branch. Added a test to make sure things work, but never tested against a real life app/run a scan. Could you confirm the fix in your environment? Thanks!
