### ISSUE TITLE
url_parameter configuration ignored for HTTPS urls

### ISSUE THREAD

**Issue by kyprizel** [andresriancho/w3af#13357]
Config directive "url_paremeter" now only effective for HTTP requests b/c
URLParameterHandler class has only method http_request configured.
My first try to fix it was https_request = http_request but it breaks everything b/c then default "timeout" value will be set to socket._GLOBAL_DEFAULT_TIMEOUT which is instance of object() but treated as float in ssl wrapper.

At first sight fixed handler looks like (sorry for not sending a patch or PR - too many changes in my branch)
```python
class URLParameterHandler(urllib2.BaseHandler):
    """
    Appends a user configured URL parameter to the request URL.
    e.g.: http://www.myserver.com/index.html;jsessionid=dd18fa45014ce4fc?id=5

    See Section 2.1 URL Syntactic Components of RFC 1808
        <scheme>://<net_loc>/<path>;<params>?<query>#<fragment>
    See Section 3.2.2 of RFC 1738

    :author: Kevin Denver ( muffysw@hotmail.com )
    """

    def __init__(self, url_param):
        self._url_parameter = url_param

    def http_request(self, req):
        url_instance = URL(req.get_full_url())
        url_instance.set_param(self._url_parameter)

        new_request = HTTPRequest(url_instance, headers=req.headers,
                                  origin_req_host=req.get_origin_req_host(),
                                  unverifiable=req.is_unverifiable(),
                                  retries=req.retries_left,
                                  timeout=req.get_timeout())
        return new_request

    https_request = http_request
```

**Comment by andresriancho** [comment]
Confirmed, the bug is in https://github.com/andresriancho/w3af/blob/master/w3af/core/data/url/handlers/url_parameter.py

**Comment by kyprizel** [comment]
I've a question - should this functionality be part of the core or should be moved to mangle plugin?
I need to add some specific parameter to every request and made QueryParameterHandler() class for myself, but what is the best way?

**Comment by andresriancho** [comment]
Hmmm... both ways are correct I believe. When this code was added it felt like a good idea to do it as a url handler and I believe its a good place for that to be in; I don't regret it.

**Comment by andresriancho** [comment]
@kyprizel do you know if the web_spider extracts URLs with `<params>` and forwards them correctly to the audit plugins? If that's not happening, then we have another bug there to fix.

**Comment by kyprizel** [comment]
Just noticed that using url_parameter breaks auth modules.

**Comment by andresriancho** [comment]
@kyprizel could you please report a different bug, with all the details to reproduce?

**Comment by andresriancho** [comment]
Ok, bug fixed! Please test and re-open if the bug still exists.

**Comment by kyprizel** [comment]
Enabling url_parameter still loose requests Host header

**Comment by kyprizel** [comment]
correct call
```
        new_request = HTTPRequest(url_instance,
                                   headers=req.get_headers(),
                                   origin_req_host=req.get_origin_req_host(),
                                   unverifiable=req.is_unverifiable(),
                                  retries=req.retries_left,
                                  cookies=req.cookies,
                                  cache=req.get_from_cache,
                                  new_connection=req.new_connection,
                                  follow_redirects=req.follow_redirects,
                                  use_basic_auth=req.use_basic_auth,
                                  use_proxy=req.use_proxy,
                                  timeout=req.timeout)
         return new_request

    https_request = http_request
```

**Comment by andresriancho** [comment]
Strange.

The only difference between the code I put after the fix and the one you propose is:
 * Yours: `headers=req.get_headers(),` vs.
 * Mine: `headers=req.headers`

And the unittest is passing.

How are you testing this? Are you sure you're testing the latest version with the fix?

**Comment by kyprizel** [comment]
by some reason req.headers does not containt Host header (try to print it).

**Comment by kyprizel** [comment]
also it loose request method and request body

**Comment by andresriancho** [comment]
Added your proposed changes without much testing nor thinking. Sorry, got no time to do it before.
