### ISSUE TITLE
Headers parser will raise exception if None value passed for some header

### ISSUE THREAD

**Issue by kyprizel** [andresriancho/w3af#13358]
Example:

```
headers_inst = Headers([(u'Host', None)])
```

**Comment by andresriancho** [comment]
And why is this a bug? If you want an empty header value then use an empty string. Closing, please re-open if I'm missing something important.

**Comment by kyprizel** [comment]
Looks like this issue is linked with issue 13357, no Host value set for HTTPS requests.

**Comment by andresriancho** [comment]
Not sure how these are related :cry:

**Comment by kyprizel** [comment]
If we create HTTPS request manually, for example:

```
        new_request = HTTPRequest(url_instance, headers=req.headers,
                                  origin_req_host=req.get_origin_req_host(),
                                  unverifiable=req.is_unverifiable(),
                                  retries=req.retries_left,
                                  timeout=req.get_timeout())
```

then Host header will be empty in this request. Yes, may be better to fix it in HTTPRequest() class.
Ugly fix:
```
class HTTPRequest(RequestMixIn, urllib2.Request):

    def __init__(self, url, data=None, headers=Headers(),
                 origin_req_host=None, unverifiable=False,
                 cookies=True, cache=False, method=None,
                 error_handling=True, retries=MAX_HTTP_RETRIES,
                 timeout=socket._GLOBAL_DEFAULT_TIMEOUT,
                 new_connection=False, follow_redirects=False,
                 use_basic_auth=True, use_proxy=True):
...
        headers = dict(headers)
        if not headers.get('Host'):
            headers['Host'] = origin_req_host
```

**Comment by andresriancho** [comment]
Ok, now I believe I understand. One last question, does the url handler at https://github.com/andresriancho/w3af/blob/master/w3af/core/data/url/handlers/url_parameter.py actually work for HTTP, or will it fail because of this issue?

**Comment by kyprizel** [comment]
Ah, looks like it doesn't work even for HTTP.

**Comment by andresriancho** [comment]
@kyprizel check the latest develop, I made some changes to that handler.
