### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by macyas** [andresriancho/w3af#13388]
Starting w3af, running on:
  Python version: 2.7.9 (default, Mar  1 2015, 18:22:53) [GCC 4.9.2]
  GTK version: 2.24.25
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6.54
    Distribution: Kali Linux
    Author: Andres Riancho and the w3af team.
Enabling preg_replace's dependency error_500
Enabling redos's dependency server_header
Enabling dav's dependency allowed_methods
Enabling frontpage's dependency frontpage_version
Called w3afCore.start()
Enabling _dns_cache()
DNS response from DNS server for domain: localhost
GET http://localhost/ returned HTTP code "200" (id=1,from_cache=0,grep=1)
GET http://localhost/ returned HTTP code "200" (id=2,from_cache=0,grep=1)
GET http://localhost/ returned HTTP code "200" (id=3,from_cache=0,grep=1)
GET http://localhost/ returned HTTP code "200" (id=4,from_cache=0,grep=1)
GET http://localhost/ returned HTTP code "200" (id=5,from_cache=0,grep=1)
GET http://localhost/ returned HTTP code "200" (id=6,from_cache=0,grep=1)
GET http://localhost/ returned HTTP code "200" (id=7,from_cache=0,grep=1)
GET http://localhost/ returned HTTP code "200" (id=8,from_cache=0,grep=1)
GET http://localhost/ returned HTTP code "200" (id=9,from_cache=0,grep=1)
GET http://localhost/ returned HTTP code "200" (id=10,from_cache=0,grep=1)
GET http://localhost/ returned HTTP code "200" (id=11,from_cache=0,grep=1)
GET http://localhost/ returned HTTP code "200" (id=12,from_cache=0,grep=1)
GET http://localhost/ returned HTTP code "200" (id=13,from_cache=0,grep=1)
GET http://localhost/ returned HTTP code "200" (id=14,from_cache=0,grep=1)
GET http://localhost/ returned HTTP code "200" (id=15,from_cache=0,grep=1)
GET http://localhost/ returned HTTP code "200" (id=16,from_cache=0,grep=1)
GET http://localhost/ returned HTTP code "200" (id=17,from_cache=0,grep=1)
Called _setup_audit()
GET http://localhost/ returned HTTP code "200" (id=18,from_cache=1,grep=1)
GET http://localhost/3OOrnr2l.rb returned HTTP code "404" (id=23,from_cache=0,grep=0)
GET http://localhost/HFEFj7Hn.htm returned HTTP code "404" (id=24,from_cache=0,grep=0)
GET http://localhost/eQjK0KVK.aspx returned HTTP code "404" (id=26,from_cache=0,grep=0)
GET http://localhost/wluHlFEl.xhtml returned HTTP code "404" (id=27,from_cache=0,grep=0)
GET http://localhost/5tQwSygF.pl returned HTTP code "404" (id=28,from_cache=0,grep=0)
GET http://localhost/O7HdyiUy.asp returned HTTP code "404" (id=29,from_cache=0,grep=0)
GET http://localhost/iZ7rSr79.do returned HTTP code "404" (id=30,from_cache=0,grep=0)
GET http://localhost/L5jvNzp1.cgi returned HTTP code "404" (id=31,from_cache=0,grep=0)
GET http://localhost/Quil6RUL.jsp returned HTTP code "404" (id=32,from_cache=0,grep=0)
GET http://localhost/gQ0rARGU.php returned HTTP code "404" (id=25,from_cache=0,grep=0)
GET http://localhost/DKMxKzBW.foobar returned HTTP code "404" (id=22,from_cache=0,grep=0)
GET http://localhost/yV3izSRb.htmls returned HTTP code "404" (id=21,from_cache=0,grep=0)
GET http://localhost/IJIKsMHE.gif returned HTTP code "404" (id=20,from_cache=0,grep=0)
GET http://localhost/TWqIfQBZ.py returned HTTP code "404" (id=19,from_cache=0,grep=0)
The 404 body result database has a length of 1.
"http://localhost/" (id:18) is NOT a 404 [similarity_index < 0.75 with sample path in 404 DB].
GET http://localhost/ returned HTTP code "200" (id=33,from_cache=1,grep=1)
GET http://localhost/ returned HTTP code "200" (id=34,from_cache=0,grep=0)
file_upload plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.file_upload
eval plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.eval
un_ssl plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.un_ssl
os_commanding plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.os_commanding
server_header plugin is testing: "Method: GET | http://localhost/"
allowed_methods plugin is testing: "Method: GET | http://localhost/"
frontpage_version plugin is testing: "Method: GET | http://localhost/"
Called _discover_worker(server_header,http://localhost/)
Starting plugin: crawl.server_header
server_header is testing "http://localhost/"
Called _discover_worker(allowed_methods,http://localhost/)
Starting plugin: crawl.allowed_methods
allowed_methods is testing "http://localhost/"
Called _discover_worker(frontpage_version,http://localhost/)
Starting plugin: crawl.frontpage_version
frontpage_version is testing "http://localhost/"
lfi plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.lfi
sqli plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.sqli
preg_replace plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.preg_replace
mx_injection plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.mx_injection
generic plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.generic
format_string plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.format_string
shell_shock plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.shell_shock
memcachei plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.memcachei
ldapi plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.ldapi
buffer_overflow plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.buffer_overflow
redos plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.redos
global_redirect plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.global_redirect
xpath plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.xpath
cors_origin plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.cors_origin
htaccess_methods plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.htaccess_methods
dav plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.dav
Created 0 mutants for "Method: GET | http://localhost/" ()
Created 0 mutants for "Method: GET | http://localhost/" ()
GET http://localhost/ returned HTTP code "200" (id=35,from_cache=1,grep=1)
The server header for the remote web server is: "Apache/2.4.10 (Debian)". This information was found in the request with id 35.
GET http://localhost/_vti_inf.html returned HTTP code "404" (id=36,from_cache=0,grep=1)
OPTIONS http://localhost/ returned HTTP code "200" (id=37,from_cache=0,grep=1)
Created 0 mutants for "Method: GET | http://localhost/" ()
Created 0 mutants for "Method: GET | http://localhost/" ()
Created 0 mutants for "Method: GET | http://localhost/" ()
GET http://localhost/ returned HTTP code "200" (id=38,from_cache=1,grep=0)
Created 0 mutants for "Method: GET | http://localhost/" ()
Created 0 mutants for "Method: GET | http://localhost/" ()
Created 0 mutants for "Method: GET | http://localhost/" ()
Created 0 mutants for "Method: GET | http://localhost/" ()
Created 0 mutants for "Method: GET | http://localhost/" ()
ssi plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.ssi
csrf plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.csrf
xss plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.xss
ssl_certificate plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.ssl_certificate
xst plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.xst
blind_sqli plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.blind_sqli
Created 0 mutants for "Method: GET | http://localhost/" ()
Created 0 mutants for "Method: GET | http://localhost/" ()
Created 0 mutants for "Method: GET | http://localhost/" ()
phishing_vector plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.phishing_vector
response_splitting plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.response_splitting
rfd plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.rfd
rfi plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.rfi
frontpage plugin is testing: "Method: GET | http://localhost/"
Starting plugin: audit.frontpage
Created 0 mutants for "Method: GET | http://localhost/" ()
Created 0 mutants for "Method: GET | http://localhost/" ()
ARGENTINA http://localhost/ returned HTTP code "501" (id=39,from_cache=0,grep=1)
Created 0 mutants for "Method: GET | http://localhost/" ()
GET http://localhost/ returned HTTP code "200" (id=42,from_cache=1,grep=1)
GET http://localhost/ returned HTTP code "200" (id=41,from_cache=0,grep=1)
GET http://localhost/ returned HTTP code "200" (id=43,from_cache=1,grep=1)
DNS response from DNS server for domain: localhost
GET http://localhost/ returned HTTP code "200" (id=40,from_cache=0,grep=1)
Created 0 mutants for "Method: GET | http://localhost/" ()
Created 0 mutants for "Method: GET | http://localhost/" ()
Updating socket timeout for localhost from 6 to 0.731589175934 seconds
Created 0 mutants for "Method: GET | http://localhost/" ()
GET http://localhost/ returned HTTP code "200" (id=44,from_cache=0,grep=1)
PROPFIND http://localhost/ with data: "<?xml version='1.0'?>  <a:propfind xmlns:a='DAV:'>  <a:prop>  <a:displaynam..." returned HTTP code "405" (id=47,from_cache=0,grep=1)
Unknown post-data. Content-type: "application/xml; charset="utf-8"" and/or post-data "<?xml version='1.0'?>
<a:propfind xmlns:a='DAV:'>"
SEARCH http://localhost/ with data: "<?xml version='1.0'?>  <g:searchrequest xmlns:g='DAV:'>  <g:sql>  Select 'D..." returned HTTP code "405" (id=46,from_cache=0,grep=1)
Unknown post-data. Content-type: "application/xml; charset="utf-8"" and/or post-data "<?xml version='1.0'?>
<g:searchrequest xmlns:g='D"
GET http://localhost/ returned HTTP code "200" (id=45,from_cache=0,grep=1)
TRACE http://localhost/ returned HTTP code "405" (id=49,from_cache=0,grep=1)
PUT http://localhost/MEkUw with data: "oX7Dxt" returned HTTP code "405" (id=48,from_cache=0,grep=1)
Unknown post-data. Content-type: "text/plain" and/or post-data "oX7Dxt"
GET http://localhost/ returned HTTP code "200" (id=50,from_cache=0,grep=1)
INDEX http://localhost/ returned HTTP code "501" (id=52,from_cache=0,grep=1)
URL "http://localhost/" is not vulnerable to RFD because response content-type is "text/html" and content-disposition header is missing, response id 34
GET http://localhost/rPpPs.html returned HTTP code "404" (id=53,from_cache=0,grep=1)
Created 0 mutants for "Method: GET | http://localhost/" ()
Created 0 mutants for "Method: GET | http://localhost/" ()
Created 0 mutants for "Method: GET | http://localhost/" ()
GET http://localhost/MEkUw returned HTTP code "404" (id=51,from_cache=0,grep=1)
GET http://localhost/ returned HTTP code "200" (id=54,from_cache=0,grep=1)
Raising HTTP error "GET" "https://localhost/". Reason: "Unable to create a SSL connection using protocols: 3, 2". Error handling was disabled for this request.
DNS response from DNS server for domain: localhost
RFI using local web server for URL: http://localhost/
INVOKE http://localhost/ returned HTTP code "501" (id=55,from_cache=0,grep=1)
POST http://localhost/_vti_bin/_vti_aut/author.dll with data: "method=put document:4.0.2.4715&service_name=&document=[document_name=/rPpPs..." returned HTTP code "404" (id=56,from_cache=0,grep=1)
Created 0 mutants for "Method: GET | http://localhost/" ()
GET http://localhost/ returned HTTP code "200" (id=57,from_cache=0,grep=1)
MKCOL http://localhost/ returned HTTP code "405" (id=58,from_cache=0,grep=1)
GET http://localhost/rPpPs.html returned HTTP code "404" (id=59,from_cache=0,grep=1)
The file that was uploaded using the POST method is not present on the remote web server at "http://localhost/rPpPs.html".
MOVE http://localhost/ returned HTTP code "405" (id=60,from_cache=0,grep=1)
GET http://localhost/ returned HTTP code "200" (id=61,from_cache=0,grep=1)
(Test id: 2653788204) 6.12474542856 > 0.00946593284607 > 2.98613939683
(Test id: 2653788204) Failed to control HTTP response delay for URL http://localhost/ - parameter "User-Agent" for 3 seconds using <Command (OS: unix, Separator: "", Command: "() { test; }; ping -c %s 127.0.0.1")>, response wait time was: 0.00946593284607 seconds.
HEAD http://localhost/ returned HTTP code "200" (id=62,from_cache=0,grep=1)
GET http://localhost/ returned HTTP code "200" (id=63,from_cache=0,grep=1)
ACL http://localhost/ returned HTTP code "501" (id=64,from_cache=0,grep=1)
GET http://localhost/ returned HTTP code "200" (id=65,from_cache=0,grep=1)
LINK http://localhost/ returned HTTP code "501" (id=66,from_cache=0,grep=1)
GET http://localhost/ returned HTTP code "200" (id=67,from_cache=0,grep=1)
RMDIR http://localhost/ returned HTTP code "501" (id=68,from_cache=0,grep=1)
REPLY http://localhost/ returned HTTP code "501" (id=69,from_cache=0,grep=1)
GET http://localhost/ returned HTTP code "200" (id=70,from_cache=0,grep=1)
(Test id: 2653320044) 6.00528144836 > 0.00666499137878 > 2.9994131724
(Test id: 2653320044) Failed to control HTTP response delay for URL http://localhost/ - parameter "User-Agent" for 3 seconds using <ExactDelay (fmt:() { test; }; sleep %s, delta:0, mult:1)>, response wait time was: 0.00666499137878 seconds.
REPORT http://localhost/ returned HTTP code "405" (id=71,from_cache=0,grep=1)
UNLINK http://localhost/ returned HTTP code "501" (id=72,from_cache=0,grep=1)
NOTIFY http://localhost/ returned HTTP code "501" (id=73,from_cache=0,grep=1)
OPTIONS http://localhost/ returned HTTP code "200" (id=74,from_cache=0,grep=1)
BASELINE_CONTROL http://localhost/ returned HTTP code "501" (id=75,from_cache=0,grep=1)
SEARCH http://localhost/ returned HTTP code "405" (id=76,from_cache=0,grep=1)
POLL http://localhost/ returned HTTP code "501" (id=77,from_cache=0,grep=1)
PIN http://localhost/ returned HTTP code "501" (id=78,from_cache=0,grep=1)
GET http://localhost/ returned HTTP code "200" (id=79,from_cache=0,grep=1)
CHECKIN http://localhost/ returned HTTP code "405" (id=80,from_cache=0,grep=1)
* http://localhost/ returned HTTP code "501" (id=81,from_cache=0,grep=1)
CONNECT http://localhost/ returned HTTP code "400" (id=82,from_cache=0,grep=1)
CHECKOUT http://localhost/ returned HTTP code "405" (id=83,from_cache=0,grep=1)
LABEL http://localhost/ returned HTTP code "405" (id=84,from_cache=0,grep=1)
PROPFIND http://localhost/ returned HTTP code "405" (id=85,from_cache=0,grep=1)
SPACEJUMP http://localhost/ returned HTTP code "501" (id=86,from_cache=0,grep=1)
SUBSCRIBE http://localhost/ returned HTTP code "501" (id=87,from_cache=0,grep=1)
LOCK http://localhost/ returned HTTP code "405" (id=88,from_cache=0,grep=1)
MKDIR http://localhost/ returned HTTP code "501" (id=89,from_cache=0,grep=1)
INVALID http://localhost/ returned HTTP code "501" (id=90,from_cache=0,grep=1)
UNCHECKOUT http://localhost/ returned HTTP code "405" (id=91,from_cache=0,grep=1)
MKWORKSPACE http://localhost/ returned HTTP code "405" (id=92,from_cache=0,grep=1)
MERGE http://localhost/ returned HTTP code "405" (id=93,from_cache=0,grep=1)
UNLOCK http://localhost/ returned HTTP code "405" (id=94,from_cache=0,grep=1)
PROPPATCH http://localhost/ returned HTTP code "405" (id=95,from_cache=0,grep=1)
DEBUG http://localhost/ returned HTTP code "501" (id=96,from_cache=0,grep=1)
VERSION_CONTROL http://localhost/ returned HTTP code "501" (id=97,from_cache=0,grep=1)
POST http://localhost/ returned HTTP code "200" (id=98,from_cache=0,grep=1)
COPY http://localhost/ returned HTTP code "405" (id=99,from_cache=0,grep=1)
Updating socket timeout for localhost from 0.731589175934 to 1.17770538568 seconds
TRACE http://localhost/ returned HTTP code "405" (id=100,from_cache=0,grep=1)
SUBSCRIPTIONS http://localhost/ returned HTTP code "501" (id=101,from_cache=0,grep=1)
PATCH http://localhost/ returned HTTP code "405" (id=102,from_cache=0,grep=1)
SHOWMETHOD http://localhost/ returned HTTP code "501" (id=103,from_cache=0,grep=1)
TRACK http://localhost/ returned HTTP code "501" (id=104,from_cache=0,grep=1)
UNSUBSCRIBE http://localhost/ returned HTTP code "501" (id=105,from_cache=0,grep=1)
TEXTSEARCH http://localhost/ returned HTTP code "501" (id=106,from_cache=0,grep=1)
MKACTIVITY http://localhost/ returned HTTP code "405" (id=107,from_cache=0,grep=1)
Exception in thread GTKDraw:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/w3af/w3af/core/ui/gui/scanrun.py", line 419, in _draw_real
    raise ValueError(msg % args)
ValueError: A ValueError exception with message "invalid literal for int() with base 10: '127.39'" was found while trying to render a new dotcode. Please create a new bug report at https://github.com/andresriancho/w3af/issues/new including the following info:

['"<GtkTreeIter at 0xb33ae80>" [label="http://localhost"]']

Found 1 URLs and 1 different injections points.
The URL list is:
- http://localhost/
The list of fuzzable requests is:
- Method: GET | http://localhost/
GET http://localhost/ returned HTTP code "200" (id=108,from_cache=0,grep=1)
GET http://localhost/ returned HTTP code "200" (id=109,from_cache=0,grep=0)
Scan finished in 3 seconds.
Stopping the core...

**Comment by andresriancho** [comment]
What's the bug?
