### ISSUE TITLE
w3af_gui  or w3af_console does not recognize pip installation

### ISSUE THREAD

**Issue by mnigudkar** [andresriancho/w3af#13493]
MAC OS X Yosemite Version 10.10.5

$ ./w3af_gui 
We recommend you install pip before continuing.
http://www.pip-installer.org/en/latest/installing.html
$ which pip
/usr/local/bin/pip
$ pip --version
pip 8.0.2 from /Library/Python/2.7/site-packages/pip-8.0.2-py2.7.egg (python 2.7)
$

**Comment by andresriancho** [comment]
This looks like one of the following:

 * A bug in [this piece of code](https://github.com/andresriancho/w3af/blob/master/w3af/core/controllers/dependency_check/dependency_check.py#L26-L32), which I believe is very unlikely.
 * A bug in the way your system is setup. Most likely your OS has two different python versions, please check that and make sure that the python executable used to run `w3af_gui` is the same as the one you run when executing `python` in the command line. This was discussed previously in other OS X issues.

**Comment by mineo210** [comment]
just get kali linux on VM
