### ISSUE TITLE
w3af_console keeps saying missing operating system packages

### ISSUE THREAD

**Issue by clemwong** [andresriancho/w3af#13577]
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.2
BuildVersion:	15C50

/tmp/w3af_dependency_install.sh

#!/bin/bash
  2 
  3 sudo pip install pyClamd==0.3.15 PyGithub==1.21.0 GitPython==0.3.2.RC1 pybloomfiltermmap==0.3.14 esmre==0.3.1 phply=    =0.9.1 nltk==3.0.1 chardet==2.1.1 tblib==0.2.0 pdfminer==20140328 futures==2.1.5 pyOpenSSL==0.15.1 ndg-httpsclient==    0.3.3 pyasn1==0.1.8 lxml==3.4.4 scapy-real==2.2.0-dev guess-language==0.2 cluster==1.1.1b3 msgpack-python==0.4.4 pyt    hon-ntlm==1.0.1 halberd==0.2.4 darts.util.lru==0.5 Jinja2==2.7.3 vulndb==0.0.19 markdown==2.6.1 psutil==2.2.1 mitmpr    oxy==0.13 ruamel.ordereddict==0.4.8 Flask==0.10.1 PyYAML==3.11

$ pip freeze
backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
blinker==1.4
certifi==2016.2.28
cffi==1.5.2
chardet==2.1.1
cluster==1.1.1b3
ConfigArgParse==0.10.0
cryptography==1.2.3
darts.util.lru==0.5
enum34==1.1.2
esmre==0.3.1
Flask==0.10.1
futures==2.1.5
gitdb==0.6.4
GitPython==0.3.2rc1
guess-language==0.2
halberd==0.2.4
hpack==2.1.0
html2text==2016.1.8
idna==2.0
ipaddress==1.0.16
itsdangerous==0.24
Jinja2==2.7.3
lxml==3.4.4
Markdown==2.6.1
MarkupSafe==0.23
mitmproxy==0.13
msgpack-python==0.4.4
ndg-httpsclient==0.3.3
netlib==0.13.1
nltk==3.0.1
passlib==1.6.5
pdfminer==20140328
phply==0.9.1
Pillow==3.1.1
ply==3.8
psutil==2.2.1
pyasn1==0.1.8
pybloomfiltermmap==0.3.14
pyClamd==0.3.15
pycparser==2.14
PyGithub==1.21.0
pyOpenSSL==0.15.1
pyparsing==2.1.0
pyperclip==1.5.26
python-ntlm==1.0.1
PyYAML==3.11
ruamel.ordereddict==0.4.8
scapy-real==2.2.0.dev0
singledispatch==3.4.0.3
six==1.10.0
smmap==0.9.0
tblib==0.2.0
tornado==4.3
urwid==1.3.1
vulndb==0.0.19
Werkzeug==0.11.4
xdot==0.6

$ python --version
Python 2.7.11

Please help!!!

**Comment by clemwong** [comment]
I saw the issue #7185
https://github.com/andresriancho/w3af/issues/7185

How can I find the old version of setuptools?

**Comment by andresriancho** [comment]
Check if the version of python being used to run w3af is the same as the one you run from the console. OSX seems to have that issue.
