### ISSUE TITLE
Failed to initialize the 404 detection, original exception was: "'HTTPResponse' object has no attribute 'path'" - Issue when trying to run a scan

### ISSUE THREAD

**Issue by bogdangrigore** [andresriancho/w3af#13598]
[w3af-sysinfo.txt](https://github.com/andresriancho/w3af/files/167181/w3af-sysinfo.txt)
[output.txt](https://github.com/andresriancho/w3af/files/167192/output.txt)

w3af - Web Application Attack and Audit Framework
Version: 1.6.54
Distribution: Kali Linux
Author: Andres Riancho and the w3af team.

I am hitting an issue when trying to run a scan. As the title says I get the error "Failed to initialize the 404 detection, original exception was: "'HTTPResponse' object has no attribute 'path'"." The error is really not helpful for me. Can you please provide more details into what could be causing this?

Attached you can find my sysinfo and output txt files.

Thank you!

**Comment by Gormogon** [comment]
:+1: +1

I'm running into this issue as well.  Same configuration as @bogdangrigore.

**Comment by andresriancho** [comment]
Use the latest w3af from github, that one fixes the issue

**Comment by bogdangrigore** [comment]
@andresriancho The latest released version is marked as 1.6.54, isn't that the latest one?

**Comment by andresriancho** [comment]
https://github.com/andresriancho/w3af/blob/master/w3af/core/data/constants/version.txt
