### ISSUE TITLE
HTTP POST SQLi

### ISSUE THREAD

**Issue by knikulov** [andresriancho/w3af#13663]
Does w3af have support for HTTP POST sql injection?

I wrote a small page with possibility of sqli in post parameters (that was correctly detected by sqlmap), and then tried to catch it using w3af, but injection point wasn't detected. Then i read sqli and blind_sqli plugins, and didn't found any mentions of http post parameters.

**Comment by andresriancho** [comment]
Should work, it might be limited by https://github.com/andresriancho/w3af/issues/10498 , but if the form is url encoded all should work.
