### ISSUE TITLE
problem during the scan

### ISSUE THREAD

**Issue by Butcher22** [andresriancho/w3af#13683]
Hello

w3af generated this bug : 
`

> Submit this bug here: https://sourceforge.net/tracker/?func=add&group_id=170274&atid=853652 
> 
> Python version:
> 2.7.9 (default, Mar  1 2015, 12:57:24) 
> [GCC 4.9.2]
> 
> GTK version:2.24.25
> PyGTK version:2.24.0
> 
> 
> w3af - Web Application Attack and Audit Framework
> Version: 1.1 (from Debian Package y: le paquet « w3af-console » n'est pas disponible
> Utilisez dpkg --info (= dpkg-deb --info) pour examiner les fichiers
> archives, et dpkg --contents (= dpkg-deb --contents) pour afficher leur
> contenu.)
> Author: Andres Riancho and the w3af team.Traceback (most recent call last):
>   File "/usr/share/w3af/core/ui/gtkUi/main.py", line 590, in startScanWrap
>     self.w3af.start()
>   File "/usr/share/w3af/core/controllers/w3afCore.py", line 417, in start
>     self._realStart()
>   File "/usr/share/w3af/core/controllers/w3afCore.py", line 602, in _realStart
>     self._end( e )
>   File "/usr/share/w3af/core/controllers/w3afCore.py", line 676, in _end
>     tm.join( joinAll=True )
>   File "/usr/share/w3af/core/controllers/threads/threadManager.py", line 119, in join
>     self._threadPool.wait( ownerObj, joinAll )
>   File "/usr/share/w3af/core/controllers/threads/threadpool.py", line 260, in wait
>     self.poll(block=True, ownerObj=ownerObj, joinAll=joinAll)
>   File "/usr/share/w3af/core/controllers/threads/threadpool.py", line 245, in poll
>     raise result
> w3afException: w3afMustStopException found by _send_404, someone else will handle it.

`

Some one can help me ?

**Comment by andresriancho** [comment]
That w3af version is too old. Use the latest from github
