### ISSUE TITLE
w3af_gui can not run

### ISSUE THREAD

**Issue by xuanyuanhaogu** [andresriancho/w3af#13780]
root@localhost:/usr/share/w3af# ./w3af_gui 
Starting w3af, running on:
  Python version: 2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]
  GTK version: 2.24.25
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6.54
    Distribution: Kali Linux
    Author: Andres Riancho and the w3af team.
Exception in thread GTKDraw:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/w3af/w3af/core/ui/gui/scanrun.py", line 419, in _draw_real
    raise ValueError(msg % args)
ValueError: A ValueError exception with message "invalid literal for int() with base 10: '174.18'" was found while trying to render a new dotcode. Please create a new bug report at https://github.com/andresriancho/w3af/issues/new including the following info:

['"<GtkTreeIter at 0x5852e20>" [label="http://192.168.30.126"]']

**Comment by andresriancho** [comment]
Duplicated
