### ISSUE TITLE
Bug reporting web page slightly misleading

### ISSUE THREAD

**Issue by phorgan1** [andresriancho/w3af#14273]
The Bug reporting page has this:
```
ser@box:~/w3af$ wget http://goo.gl/eXpPDl
user@box:~/w3af$ chmod +x collect-sysinfo.py
user@box:~/w3af$ ./collect-sysinfo.py
```
But that resulted in a file named _eXpPDI_ instead of _collect-sysinfo.py_
It's the right file, just a different name. I didn't bother to rename it, just gave it execute permissions and ran it. No big deal for me but I'm been using unix/linux boxes since the 80s. Most things seem obvious to me. Would probably be confusing to a new user.

**Comment by andresriancho** [comment]
Thanks!
