### ISSUE TITLE
w3af won't believe I have python-setuptools on fedora 24

### ISSUE THREAD

**Issue by phorgan1** [andresriancho/w3af#14272]
After updating to current git master:
```
w3af» git pull
Current branch master is up to date.
```
When running w3af (on fedora 24) I get the message:
```
» ./w3af_console
w3af's requirements are not met, one or more third-party libraries need to be installed.

On fedora systems please install the following operating system packages before running the pip installer:
    sudo yum install python-setuptools

A script with these commands has been created for you at /tmp/w3af_dependency_install.sh
```

Unfortunately that's already installed:
```
» sudo dnf install python-setuptools
Package python2-setuptools-20.1.1-1.fc24.noarch is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
```
It does that even if trying to get the --version. Maybe the --version options could be responded to even if all of the prerequisites weren't available? I can send some git patches for all of these things if you like.

The root of the problem seems to be a disagreement between what to look for between rpm -q which w3af uses, and dnf. 

```
» rpm -q  python-setuptools
package python-setuptools is not installed
```

Of course, dnf installs python2-setuptools when asked to install python-setuptools and when using rpm to ask about that, it is found.
```
» rpm -q  python2-setuptools
python2-setuptools-20.1.1-1.fc24.noarch
```
That said, there is certainly a _/usr/lib/python2.7/site-packages/setuptools_

I think with either python 2 or 3 you can do:
```
>>> import pkgutil
>>> print ( 1 if pkgutil.find_loader('setuptools') else 0)
1
```
That should be more portable across OSes and levels. They already do the work that you are trying to do.

Here's the sysinfo.txt:

Operating system
================
System: linux - Distribution: ('fedora', '24', 'Twenty Four') - Release: 4.7.2-201.fc24.x86_64

Kernel version
==============
Linux patricksBox 4.7.2-201.fc24.x86_64 #1 SMP Fri Aug 26 15:58:40 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Python version
==============

pip version
===========
pip 8.0.2 from /usr/lib/python2.7/site-packages (python 2.7)

pip freeze
==========
astroid==1.4.5
backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
Beaker==1.5.4
beautifulsoup4==4.5.1
blinker==1.4
blivet==1.20.3
boto==2.41.0
bzr==2.6.0
catfish==1.4.2
certifi==2016.8.31
cffi==1.5.2
chardet==2.1.1
cluster==1.1.1b3
ConfigArgParse==0.10.0
coverage==4.2
cryptography==1.3.1
cssselect==0.9.1
darts.util.lru==0.5
decorator==4.0.6
di==0.3
Django==1.9.8
dnf-langpacks==0.15.1
dockerfile-parse==0.0.5
dropbox==3.41
duplicity==0.7.9
ecdsa==0.13
enum==0.4.4
enum34==1.0.4
esmre==0.3.1
fedpkg==1.24
Flask==0.10.1
frescobaldi==2.19.0
futures==2.1.5
gitdb==0.6.4
GitPython==0.3.2rc1
GnuPGInterface==0.3.2
guess-language==0.2
halberd==0.2.4
hpack==2.3.0
html2text==2015.6.6
html5lib==0.999
httplib2==0.9.2
idna==2.0
iniparse==0.4
ipaddr==2.1.10
ipaddress==1.0.16
IPy==0.81
ipython==3.2.1
itsdangerous==0.24
Jinja2==2.7.3
jsonpointer==1.10
jsonschema==2.4.0
kitchen==1.2.4
laditools==1.0.1
langtable==0.0.35
lazy-object-proxy==1.2.1
lockfile==0.11.0
logilab-common==0.63.2
lxml==3.4.4
Magic-file-extensions==0.2
Mako==1.0.3
Markdown==2.6.1
MarkupSafe==0.23
mercurial==3.7.3
mistune==0.7.3
mitmproxy==0.13
msgpack-python==0.4.4
munch==2.0.4
ndg-httpsclient==0.3.3
netlib==0.13.1
nltk==3.0.1
nose==1.3.7
ntplib==0.3.3
numpy==1.11.0
osbs-client==0.24
packagedb-cli==2.13
paramiko==1.16.0
passlib==1.6.5
Paste==2.0.2
path.py==5.2
pcapy==0.10.8
pdfminer==20140328
pexpect==4.1.0
phply==0.9.1
Pillow==3.2.0
ply==3.8
policycoreutils-default-encoding==0.1
psutil==2.2.1
ptyprocess==0.5.1
pwquality==1.3.0
pyalsa==1.0.29
pyasn1==0.1.8
pyasn1-modules==0.0.8
pybloomfiltermmap==0.3.14
pyClamd==0.3.15
pycparser==2.14
pycrypto==2.6.1
pycryptopp==0.6.0.1206569328141510525648634803928199668821045408958
pycups==1.9.72
pycurl==7.43.0
PyGithub==1.21.0
pygobject==3.20.1
pygpgme==0.3
pyinotify==0.9.6
pykickstart==2.25
pyliblzma==0.5.3
pylint==1.5.6
pyOpenSSL==0.15.1
PyPAM==0.5.0
pyparsing==2.1.5
pyparted==3.10.7
pyperclip==1.5.27
PySocks==1.5.6
python-augeas==0.5.0
python-bugzilla==1.2.2
python-cloudfiles==1.7.11
python-dmidecode==3.12.2
python-fedora==0.8.0
python-ldap==2.4.25
python-ly==0.9.4
python-meh==0.43
python-ntlm==1.0.1
python-poppler-qt4==0.18.1
python-systemd==231
pytz==2016.6.1
pyudev==0.21.0
pyxattr==0.5.3
pyxdg==0.25
PyYAML==3.11
pyzmq==14.7.0
reportlab==3.3.0
requests==2.10.0
rpkg==1.46
rpm-python==4.13.0rc1
rsa==3.4.1
ruamel.ordereddict==0.4.8
scapy==2.3.1
scapy-real==2.2.0.dev0
seobject==0.1
sepolicy==1.1
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
slip==0.6.4
slip.dbus==0.6.4
smmap==0.9.0
solaar==0.9.2
SSSDConfig==1.13.4
tblib==0.2.0
Tempita==0.5.1
tornado==4.4.1
uniconvertor==2.0
urlgrabber==3.10.1
urllib3==1.15.1
urwid==1.3.1
vulndb==0.0.19
Werkzeug==0.11.11
wheel==0.26.0
wrapt==1.10.5
xdot==0.6
yum-metadata-parser==1.1.4
zenmap==7.12

Package list
============

**Comment by andresriancho** [comment]
Dup https://github.com/andresriancho/w3af/issues/14339
