### ISSUE TITLE
What is Netscape format cookies file?

### ISSUE THREAD

**Issue by hyanx** [andresriancho/w3af#14680]
When I include a cookies file w3af report a error
```
Identified an error with the user-defined settings:

    - Error while loading cookiejar file. Description: "'cookies.txt' does not look like a Netscape format cookies file". 

No information has been saved.

```

I used such as this form still error

1.   .abc.com	TRUE	/	FALSE	1482319621	JSESSIONID	efeiflLak9kee4V3O2fbd

2. Set-Cookie:  JSESSIONID=efeiflLak9kee4V3O2fbd

How can I do ? :sob:

**Comment by andresriancho** [comment]
http://docs.w3af.org/en/latest/authentication.html#setting-http-cookie doesn't work?
