### ISSUE TITLE
find_dvcs plugin trigger false positives

### ISSUE THREAD

**Issue by mtskg** [andresriancho/w3af#14955]
I have found that find_dvcs often trigger false positives. Maybe some extra validation could be done in order to guarantee that the files that are found are actually valid.

**Comment by andresriancho** [comment]
An example where find_dvcs trigger false positives was sent over email by @mtskg:

http://xyz/goteborg/.git/index
http://xyz/Content/.cvsignore

Looks like the 404 detection is failing, but it's really strange since the HTTP response code is 404.

**Comment by andresriancho** [comment]
I was able to reproduce the bug in the latest develop:

```
New URL found by find_dvcs plugin: "http://xyz/.git/index"
New URL found by find_dvcs plugin: "http://xyz/.git/.git/index"
New URL found by find_dvcs plugin: "http://xyz/.git/.git/.git/index"
...
```

**Comment by andresriancho** [comment]
```
http-settings
set max_requests_per_second 15
set max_http_retries 2
set user_agent Holm Security WAS
set timeout 0
back
misc-settings
set fuzz_url_parts False
set fuzz_cookies False
set fuzz_url_filenames False
back
plugins

crawl find_dvcs
crawl robots_txt

output text_file
output config text_file
set output_file output-w3af.txt
set verbose True
back

back
target set target http://xyz/
start
exit
```

**Comment by andresriancho** [comment]
Not fixed yet! Check my email
