### ISSUE TITLE
Is plugin.rfi still unavailable?

### ISSUE THREAD

**Issue by jinhaoxia** [andresriancho/w3af#15153]
When I start scan with plugin.rfi included 

`An error occurred while running local web server for the remote file inclusion (rfi) plugin: "[Errno 98] Address already in use"
`

How can I do? 😂

version 1.7.6 of kali

**Comment by andresriancho** [comment]
## Solution
Configure the rfi plugin to use another port or just use the w3af site for testing RFI.

## Task
The error seems to be difficult to understand for regular users, if socket errors are detected I should give them better guidance on which actions they should take to solve the problem.
