### ISSUE TITLE
w3af_console doesn't run

### ISSUE THREAD

**Issue by ztencmcp** [andresriancho/w3af#15369]
Version infor
-----------------------------------------------------------------
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"
-----------------------------------------------------------------
PIP Freeze
-----------------------------------------------------------------
adns-python==1.2.1
AdvancedHTTPServer==2.0.9
alembic==0.8.6
amqp==1.4.9
anyjson==0.3.3
appdirs==1.4.3
argcomplete==1.8.1
argh==0.26.2
asn1crypto==0.22.0
attrs==16.3.0
backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
basemap==1.0.7
BBQSQL==1.0
BeautifulSoup==3.2.1
beautifulsoup4==4.5.3
billiard==3.3.0.23
BlindElephant==1.0
blinker==1.3
boltons==16.4.1
brotlipy==0.6.0
bs4==0.0.1
capstone==3.0.4
celery==3.1.23
certifi==2016.2.28
cffi==1.10.0
chardet==2.1.1
Cheetah==2.4.4
cheroot==5.3.0
CherryPy==10.2.1
## FIXME: could not find svn URL in dependency_links for this package:
chirp===daily-20170124
click==6.6
cluster==1.1.1b3
colorama==0.3.7
ConcurrentLogHandler==0.9.1
ConfigArgParse==0.11.0
configobj==5.0.6
configparser==3.5.0
constantly==15.1.0
construct==2.5.2
couchdbkit==0.6.5
crackmapexec==3.1.5.dev0
cryptography==1.8.1
cssutils==1.0
cycler==0.10.0
dap==2.2.6.7
darts.util.lru==0.5
decorator==4.0.11
dicttoxml==1.7.4
dissy==9
distorm3==3.3.4
Django==1.10.6
dnspython==1.15.0
docutils==0.13.1
dominate==2.2.0
easygui==0.96
EasyProcess==0.2.3
Elixir==0.7.1
enum34==1.1.6
esmre==0.3.1
feedparser==5.1.3
Flask==0.10.1
Flask-Bootstrap==3.3.6.0
Flask-Cache==0.13.1
Flask-Migrate==1.8.0
flask-paginate==0.4.5
Flask-Script==2.0.5
Flask-SQLAlchemy==2.1
FormEncode==1.3.0
functools32==3.2.3.post2
fuse-python==0.2.1
future==0.15.2
futures==2.1.5
fuzzywuzzy==0.15.0
GDAL==2.1.2
GeoIP==1.3.2
geoip2==2.4.2
geojson==1.3.1
gevent==1.2.1
gitdb==0.6.4
gitdb2==2.0.0
GitPython==0.3.2rc1
greenlet==0.4.11
guess-language==0.2
h2==2.5.2
halberd==0.2.4
hpack==2.3.0
html2text==2016.9.19
html5lib==0.999999999
http-parser==0.8.3
httplib2==0.9.2
httpretty==0.8.14
hyperframe==4.0.1
icalendar==3.8
idna==2.5
impacket==0.9.15
incremental==16.10.1
ipaddress==1.0.18
iptools==0.6.1
IPy==0.83
ipython==5.1.0
ipython-genutils==0.1.0
itsdangerous==0.24
jdcal==1.0
Jinja2==2.7.3
jsbeautifier==1.6.4
jsonpickle==0.9.3
jsonrpclib==0.1.3
keepnote==0.7.8
keyring==10.1
keyrings.alt==1.3
killerbee==1.0
kombu==3.0.37
lxml==3.4.4
M2Crypto==0.24.0
Mako==1.0.4
Markdown==2.6.1
MarkupSafe==0.23
matplotlib==2.0.0
maxminddb==1.2.3
mechanize==0.2.5
mercurial==4.0
metaconfig==0.1.4a1
mitmproxy==0.13
mockito==0.5.2
msgpack-python==0.4.4
mysqlclient==1.3.7
nassl==0.12
ndg-httpsclient==0.3.3
netaddr==0.7.18
netlib==0.13.1
NfSpy==1.0
nltk==3.0.1
numpy==1.12.0
olefile==0.42.1
openpyxl==2.3.0
packaging==16.8
PAM==0.4.2
paramiko==2.0.0
passlib==1.7.0.post20161128115349
Paste==2.0.3
PasteDeploy==1.5.2
PasteScript==1.7.5
pathlib2==2.1.0
pathtools==0.1.2
pcapy==0.10.8
pdfkit==0.6.1
pdfminer==20140328
pefile==2016.3.28
pexpect==4.2.1
phply==0.9.1
pickleshare==0.7.4
Pillow==4.0.0
pluginbase==0.4
ply==3.10
portend==1.8
prettytable==0.7.2
prompt-toolkit==1.0.9
psutil==2.2.1
psycopg2==2.6.2
ptyprocess==0.5.1
py==1.4.32
pyasn1==0.1.9
pyasn1-modules==0.0.7
pybloomfiltermmap==0.3.14
pyClamd==0.3.15
pycparser==2.17
pycrypto==2.6.1
pycurl==7.43.0
PyDispatcher==2.0.5
pydns==2.3.6
pyenchant==1.6.7
PyGithub==1.21.0
Pygments==2.2.0
pygobject==3.22.0
pygraphviz==1.4rc1
pyinotify==0.9.6
pylibemu==0.3.3
pymongo==3.4.0
pymssql==1.0.2
pyOpenSSL==0.15.1
pyotp==2.2.1
pyparsing==2.2.0
PyPDF2==1.26.0
pyperclip==1.5.27
pyrit==0.5.1
pyscard==1.9.4
pyserial==3.2.1
pysnmp==4.3.2
pysnmp-apps==0.3.2
pysnmp-mibs==0.1.3
PySocks==1.6.5
pyspatialite==3.0.1
pysqlite==2.7.0
pytest==3.0.6
python-apt==1.4.0b2
python-dateutil==2.5.3
python-debian==0.1.30
python-debianbts==2.6.1
python-editor==1.0
python-Levenshtein==0.12.0
python-magic==0.4.11
python-ntlm==1.0.1
python-openid==2.2.5
python-pam==1.8.2
python-qt-binding==0.2.17
pytz==2016.7
pyusb==1.0.0b2
PyVirtualDisplay==0.2.1
PyX==0.12.1
pyxdg==0.25
PyYAML==3.12
qrcode==5.3
qt4reactor==1.6
rarfile==2.7
rdpy==1.3.2
reportbug==6.6.6
requests==2.6.2
restkit==4.2.2
rfidiot==1.0
roman==2.0.0
rsa==3.4.2
ruamel.ordereddict==0.4.8
scapy===unknown.version
scapy-real==2.2.0.dev0
scgi==1.13
SecretStorage==2.3.1
service-identity==16.0.0
Shapely==1.5.17
simplegeneric==0.8.1
simplejson==3.10.0
singledispatch==3.4.0.3
six==1.10.0
slowaes==0.1a1
smmap==0.9.0
smmap2==2.0.1
smoke-zephyr==1.0.2
socketpool==0.5.3
SQLAlchemy==1.0.13
subprocess32==3.2.7
tblib==0.2.0
tcpwatch==1.3.1
Tempita==0.5.2
tempora==1.6.1
termcolor==1.1.0
tldextract==1.7.2
tornado==4.4.2
traitlets==4.3.1
Twisted==16.6.0
typing==3.5.2.2
tzlocal==1.3
unicodecsv==0.14.1
urllib3==1.19.1
urwid==1.3.1
uTidylib==0.3
vinetto==0.7b0
visitor==0.1.3
volatility==2.6
vulndb==0.0.19
wafw00f==0.9.3
wapiti==2.3.0
watchdog==0.8.3
wcwidth==0.1.7
webencodings==0.5
webunit==1.3.10
Werkzeug==0.11.9
wfuzz==0.0.0
Whoosh==2.7.0
wxPython==3.0.2.0
wxPython-common==3.0.2.0
xdot==0.6
XlsxWriter==0.9.6
xmlbuilder==1.0
yara-python==3.5.0
zenmap==7.40
zim==0.65
zope.interface==4.3.2
----------------------------------------------------
I have installed all dependencies, so there is no /tmp/w3af_dependency_install.sh, when i use ./w3af_console, the error message like below:

Error message
---------------------------------------------------------------------
Traceback (most recent call last):
  File "./w3af_console", line 15, in <module>
    from w3af.core.ui.console.console_ui import ConsoleUI
  File "/opt/w3af/w3af/core/ui/console/console_ui.py", line 35, in <module>
    from w3af.core.ui.console.rootMenu import rootMenu
  File "/opt/w3af/w3af/core/ui/console/rootMenu.py", line 32, in <module>
    from w3af.core.ui.console.plugins import pluginsMenu
  File "/opt/w3af/w3af/core/ui/console/plugins.py", line 29, in <module>
    from w3af.core.ui.console.config import ConfigMenu
  File "/opt/w3af/w3af/core/ui/console/config.py", line 27, in <module>
    from w3af.core.controllers.plugins.plugin import Plugin
  File "/opt/w3af/w3af/core/controllers/plugins/plugin.py", line 37, in <module>
    from w3af.core.data.url.helpers import new_no_content_resp
  File "/opt/w3af/w3af/core/data/url/helpers.py", line 28, in <module>
    import OpenSSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

**Comment by andresriancho** [comment]
Solved with the latest merge from develop to master I made today. In order to fix this issue you need to go to your w3af directory and run `git pull`, then try to run the `w3af_console` again.
