### ISSUE TITLE
ImportError: No module named webkit

### ISSUE THREAD

**Issue by harvies** [andresriancho/w3af#15370]
Traceback (most recent call last):
  File "w3af_gui", line 110, in <module>
    _main()
  File "w3af_gui", line 106, in _main
    sys.exit(main())
  File "w3af_gui", line 100, in main
    from w3af.core.ui.gui.main import main as gui_main
  File "/root/git/w3af/w3af/core/ui/gui/main.py", line 54, in <module>
    from w3af.core.ui.gui import scanrun, helpers, profiles, compare
  File "/root/git/w3af/w3af/core/ui/gui/scanrun.py", line 27, in <module>
    import webkit
ImportError: No module named webkit

**Comment by crystalstorm** [comment]
I had the same problem on OS X, fixed it with macports:
`sudo port install py27-webkitgtk`

**Comment by markohaapala** [comment]
`sudo apt-get install python-webkit` fixed it for me in Debian.

**Comment by geranne** [comment]
I got the same error: ImportError: No module named webkit
Using MAC OSX 10.10 Yosemite

**Comment by yuleitest** [comment]
root@kali:~/w3af# apt-get install python-webkit
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-webkit
root@kali:~/w3af#
