### ISSUE TITLE
 Installation issue on Kali Linux 

### ISSUE THREAD

**Issue by aiApple** [andresriancho/w3af#15636]
I tried to install w3af on Kali following the commands:
**apt-get update
apt-get install kali-linux-all
apt-get build-dep python-lxml
cd ~
pip install --upgrade pip
git clone https://github.com/andresriancho/w3af.git
cd w3af
./w3af_console
/tmp/w3af_dependency_install.sh**
after installed, when I run "./w3af_console" I got the this error:
Traceback (most recent call last):
  File "./w3af_console", line 15, in <module>
    from w3af.core.ui.console.console_ui import ConsoleUI
  File "/home/john/w3af/w3af/core/ui/console/console_ui.py", line 35, in <module>
    from w3af.core.ui.console.rootMenu import rootMenu
  File "/home/john/w3af/w3af/core/ui/console/rootMenu.py", line 32, in <module>
    from w3af.core.ui.console.plugins import pluginsMenu
  File "/home/john/w3af/w3af/core/ui/console/plugins.py", line 29, in <module>
    from w3af.core.ui.console.config import ConfigMenu
  File "/home/john/w3af/w3af/core/ui/console/config.py", line 27, in <module>
    from w3af.core.controllers.plugins.plugin import Plugin
  File "/home/john/w3af/w3af/core/controllers/plugins/plugin.py", line 37, in <module>
    from w3af.core.data.url.helpers import new_no_content_resp
  File "/home/john/w3af/w3af/core/data/url/helpers.py", line 28, in <module>
    import OpenSSL
  File "/home/john/.virtualenvs/w3af/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/john/.virtualenvs/w3af/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

**Comment by derboblan** [comment]
try #14966 and maybe comment `PIPDependency('pyasn1', 'pyasn1', '0.1.9')`, in `w3af/core/controllers/dependency_check/requirements.py`

**Comment by GhostSpotter** [comment]
Hi
sorry for my bad English..i am from Germany...i found a Solution to install w3af under Kali Rolling 2017.
u have to do this steps..i use the new Kali Version...

**install w3af in kali linux (rolling)** 
for Kali Linux latest version 20170601
Kali Linux has been installed some packages for fill the requirements of w3af.

    openssl ==> 16.2.0 
    lxml ==> 3.7.1 

**Preparing install:**
sudo apt install -y python-pybloomfiltermmap

    pybloomfiltermmap ==> 0.3.15

**update the version in** requiremenets.py
vim ~/w3af/w3af/core/controllers/dependency_check/requirements.py

    PIPDependency('pybloomfilter', 'pybloomfiltermmap', '0.3.15'), 
    PIPDependency('OpenSSL', 'pyOpenSSL', '16.2.0'), 
    PIPDependency('lxml', 'lxml', '3.7.1'), 

update mac version dependency_check
vim ~/w3af/w3af/core/controllers/dependency_check/platforms/mac.py

    MAC_CORE_PIP_PACKAGES.remove(PIPDependency('pybloomfilter', 'pybloomfiltermmap', '0.3.15') 

execute command for generating installation scripts
./w3af_console

And the script will be generated to /tmp/w3af_dependency_install.sh
Then execute the scripts and finish the installation. 

that it..have i nice day

**Comment by andresriancho** [comment]
Solved with the latest merge from develop to master I made today. In order to fix this issue you need to go to your w3af directory and run `git pull`, then try to run the `w3af_console` again.
