### ISSUE TITLE
edit/update pip dependencies

### ISSUE THREAD

**Issue by alphaaurigae** [andresriancho/w3af#15828]
hi,

i have difficulties installing w3af from source without breaking other installations due to the pip dependency version requirements.

i tried to put >= in front of the version numbers in pip_dependency.py but obv that doesent work.

Is there an automatic way to update pip dependencies based on the system?

**Comment by andresriancho** [comment]
this should help http://docs.w3af.org/en/latest/advanced-install.html#installing-using-virtualenv

**Comment by alphaaurigae** [comment]
thx, that did the trick. Heres what solved it for me ...
https://github.com/alphaaurigae/ITSEC-Install-Scripts/blob/master/2.Vulnerability-Scanner/w3af.sh
```
:~$ w3af_gui 
Starting w3af, running on:
  Python version: 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
  Platform: Ubuntu 16.04 xenial
  GTK version: 2.24.30
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.7.6
    Revision: 8794f3882b - 03 Jul 2017 12:26
    Branch: develop
    Local changes: No
    Author: Andres Riancho and the w3af team.

```
