### ISSUE TITLE
Problem installing pybloomfiltermmap

### ISSUE THREAD

**Issue by sasatefa2009** [andresriancho/w3af#15992]
i have many many many problems while installing dependencies, while I've already installed the latest versions of every dependency, w3af insist not.
here is the first problem

i'm using kali linux 2016.2 with no updates

Collecting pybloomfiltermmap==0.3.14
  Using cached pybloomfiltermmap-0.3.14.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kmcl48da/pybloomfiltermmap/setup.py", line 31
        print "info: Building from Cython"
                                         ^
    SyntaxError: Missing parentheses in call to 'print'

and why do you specify versions for every dependency, why not just "pip" ?? to get the last version of every one ?

**Comment by andresriancho** [comment]
You seem to be trying to run w3af / pybloomfilter with python 3k, while w3af was coded for python 2.7

**Comment by sasatefa2009** [comment]
@andresriancho  Please don't close any issue before the problem is solved.

all the dependencies is installed with latest versions, not the late versions specified by w3af.
i have two questions now:-

1- how to make sure all the dependencies is installed
2- why do you specify versions for every dependency, why not just "pip" ?? to get the last version of every one ?

**Comment by andresriancho** [comment]
You need the lib versions specified by w3af. Those lib versions are known to work with w3af. Other versions might bring issues.

It is possible to use http://docs.w3af.org/en/latest/advanced-install.html#installing-using-virtualenv to install the "old library versions" required by w3af without modifying your operating system's python installation.

**Comment by sasatefa2009** [comment]
w3af is asking me to install exactly a 23 dependency, with an old versions !

i could do what you are saying if it was a 2 or 3 dependencies, but to un-install 23 dependency with their newer versions and install old ones. This is not sane at all.

maybe you need to update w3af to be compatible with the newer versions, because sooner or later you will do.

**Comment by andresriancho** [comment]
That is why virtualenv exists.

**Comment by sasatefa2009** [comment]
@andresriancho  
you are worsen the situation by this.
the problem key is in your pocket. if i did this it will be just for me. but your fix will be a universal solution.
as i said, you are not going to use the old versions of these libraries for too long, so you better update now.

**Comment by sasatefa2009** [comment]
you may close the issue now if you like

**Comment by andresriancho** [comment]
Updating now is possible, yes.

But then I have to update every 6 months. Every 3 months. Every month. Every week? Every time a new library version comes out? What is the right periodicity for this?

Also, a new library might be available on pip but not on ubuntu repositories. Or it might be on pip, ubuntu, but not on Kali, or... not in whatever linux distribution is used by some user.

Maintaining an open source project is hard. Take it easy, chill, go grab a beer and think about how aggressive you were in this exchange.

**Comment by sasatefa2009** [comment]
@andresriancho 

> What is the right periodicity for this? 

maybe a month ?!

Well. the logic itself 'w3af' build upon is wrong, you could set a limit to the version of the library so that it could not be before it but no problem if it was newer.

I'm so sorry if i was aggressive or you felt it this way. I really admire your great work and the effort for what you are doing. but,

_i don't drink beer_

**Comment by andresriancho** [comment]
> you could set a limit to the version of the library so that it could not be before it but no problem if it was newer.

That is not true. We had a case where a library broke w3af when they released a new version.
