### ISSUE TITLE
Error While Installing Dependency

### ISSUE THREAD

**Issue by HarshilPatel007** [andresriancho/w3af#15990]
Hi, I Try to Install w3af but it fails to install dependency.
Here Is The Full Log Of Error.
https://gist.githubusercontent.com/HarshilPatel007/a0757a9ee4f7b728d02c708c45f2f585/raw/468ce290b49e5a3e4bdb1ca1906f920796cba23f/w3af-error.txt

Please Help me.
Note: Before Submitting Issue I Try Each End Every Solutions Of
https://askubuntu.com/ , https://stackoverflow.com/ , youtube videos, etc.
but no luck :'(
Can anyone encounter the error please.
help me to install w3af. ( I Stuck With It )
System Info : Kali Rolling x86_64 Latest Full Updated And Upgraded.

And my question is why Kali is ( OffSec. ) not include w3af in their repo...????
However, Currently I Added debian repo. in my kali and install very old version(1.1) of w3af! from apt!
it's not updated!
It's my humble request to developer to add w3af in kali repo.

**Comment by andresriancho** [comment]
It seems you're getting an error in the libxml compilation process. Maybe search for that instead? Example searches:

`libxml /usr/bin/ld: cannot find lz`

**Comment by andresriancho** [comment]
Alternative: Use w3af's docker http://docs.w3af.org/en/latest/install.html#installing-using-docker

**Comment by HarshilPatel007** [comment]
Yes Search For Specially " ld command " and ask in askubuntu.com but problem can't solved :(
