### ISSUE TITLE
Error on /tmp/w3af_dependency_install.sh in kali linux 2017.2

### ISSUE THREAD

**Issue by BlackRouter** [andresriancho/w3af#16046]
hi
i get error on /tmp/w3af_dependency_install.sh in kali 2017.2.

`Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-canbTz/pybloomfiltermmap/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-saV__M-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-canbTz/pybloomfiltermmap/
`

**Comment by B4B4NN** [comment]
yes when install dependency i got same error 
    x86_64-linux-gnu-gcc: error trying to exec 'cc1plus': execvp: No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vf0ANY/pybloomfiltermmap/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-WyHVhN-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-vf0ANY/pybloomfiltermmap/

**Comment by B4B4NN** [comment]
i got fix this problem 
sudo apt update
sudo apt upgrade
sudo apt install gcc python3-dev python3-pip libxml2-dev libxslt1-dev zlib1g-dev g++
