### ISSUE TITLE
Restful API - Can not stop scan. Grep consumer join indefinitely

### ISSUE THREAD

**Issue by linerd0196** [andresriancho/w3af#16055]
I started a scan on target `testphp.vulnweb.com`, using Restful API. After 3mins, I stopped the scan using API `/scan/<scan_id>/stop`. But this stopping was endless.  

After a while debugging, It turned out that was the grep consumer problem. The stopping process runned `strategy.terminate` method on 2 separated threads. (scan stopping thread and main thread)

`audit`, `crawl_infrastructure` 's `terminate` method runned on scan stopping thread,  `bruteforce` and `grep` 's runned on main thread. `grep` consumer's  `join` method runned indefinitely

**Comment by andresriancho** [comment]
@linerd0196 I've experienced the "w3af never stops" issue too.

Why did you close this issue? Did you fix it? May we get that fix too?

**Comment by linerd0196** [comment]
I think I 've found the cause of this problem. Please check #16063.
Btw, Why does the `strategy.terminate()` method has to run twice at the same time when calling w3afCore.stop()? 
I mean why do you have to do a w3afCore's cleanup on two separated threads?

**Comment by andresriancho** [comment]
> Btw, Why is the strategy.terminate() called twice when user calls w3afCore.stop() method?
I mean why do you do a w3afCore cleanup on two separated threads?

Could you show me the code where that happens? I would have to put a lot of effort to find it and you already know how that part works.
