### ISSUE TITLE
a python question

### ISSUE THREAD

**Issue by aaeolus** [andresriancho/w3af#16323]
Downloading pybloomfiltermmap-0.3.14.tar.gz (446kB)
    100% |████████████████████████████████| 450kB 315kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5iekr12m/pybloomfiltermmap/setup.py", line 31
        print "info: Building from Cython"
                                         ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5iekr12m/pybloomfiltermmap/

**Comment by andresriancho** [comment]
Looks like you're trying to install w3af (and its dependencies) in a system which uses python3 as default. w3af can only work with python2.
