### ISSUE TITLE
404_responses repeat too much

### ISSUE THREAD

**Issue by qux-bbb** [andresriancho/w3af#16521]
In w3af/w3af/core/controllers/core_helpers/fingerprint_404.py 179  

You should change "continue" to "break", or 404_responses will repeat too much.

**Comment by andresriancho** [comment]
Thanks for reviewing the code :+1: 

There is something I don't understand, you're referring to this `continue`:

https://github.com/andresriancho/w3af/blob/22340ba098de401a1aaef86bbc41f1ccef796396/w3af/core/controllers/core_helpers/fingerprint_404.py#L174-L179

I believe it does its intended job: `If i and j are the same object do not compare them and continue with the next j`

If we change that `continue` to a `break` then there might be some items from `self._404_responses` which are never compared with the items from `not_exist_resp_lst` and that is not what we want?

**Comment by qux-bbb** [comment]
Sorry I read too late.  
For example:  
```python
# coding:utf8

ii = [1, 2, 3, 4, 5, 6]
jj = [1, 2]

for i in ii:
    for j in jj:
        if i == j:
            break
    else:
        jj.append(i)

print jj
```
The result is:  
[1, 2, 3, 4, 5, 6]  

So, I think it is not a problem.

**Comment by qux-bbb** [comment]
If replace "break" with "continue":  
```python
# coding:utf8

ii = [1, 2, 3, 4, 5, 6]
jj = [1, 2]

for i in ii:
    for j in jj:
        if i == j:
            continue
    else:
        jj.append(i)

print jj
```
The result is:  
[1, 2, 1, 2, 3, 4, 5, 6]

**Comment by andresriancho** [comment]
Oh... hmmm...

**Comment by andresriancho** [comment]
Thanks!
