### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by gbiagomba** [andresriancho/w3af#16722]
Hello Andres,

Is there a requirements folder for python dependencies? and Maybe one for system packages? I got an error telling me I was missing some dependencies, I looked at your install doc and it it referenced a dependency shell script but I couldn't find said shell script. I am guessing it was in an earlier release?

**Comment by andresriancho** [comment]
https://github.com/andresriancho/w3af/blob/master/w3af/core/controllers/dependency_check/requirements.py

**Comment by andresriancho** [comment]
And for the OS

https://github.com/andresriancho/w3af/tree/master/w3af/core/controllers/dependency_check/platforms

**Comment by gbiagomba** [comment]
Thank you!
