### ISSUE TITLE
REST-API XML

### ISSUE THREAD

**Issue by ebakirmak** [andresriancho/w3af#16950]
Hi there,

i want to download vulnerabilities as XML File. Can i do this with w3af-api ?

**Comment by andresriancho** [comment]
No, you will have to get them from the REST API using HTTP requests.

The other potential way is to enable the `xml_file` output plugin and then have access to the OS file system where the rest api server is being run.

**Comment by ebakirmak** [comment]
Well, i want to create a profile file.etc. where can i find explains of  [output.xml_file]  [grep.feeds] etc. ?

**Comment by andresriancho** [comment]
Example profiles can be found at https://github.com/andresriancho/w3af/tree/master/profiles

You can also start the w3af-gui, choose the plugins you want to run, configure them, save the profile to a file, and inspect / use it.
