### ISSUE TITLE
Netscape format cookie file not working

### ISSUE THREAD

**Issue by rkhal101** [andresriancho/w3af#17116]
Hi, I'm trying to set a cookie for my scan and I followed the format provided here: http://docs.w3af.org/en/latest/authentication.html#setting-http-cookie. However, it is not working. I get the error "The supplied cookiejar file is not in Netscape format please...."

[cookie2.txt](https://github.com/andresriancho/w3af/files/2172497/cookie2.txt)
 I attached the file I'm using. Thanks in advance!

**Comment by andresriancho** [comment]
It took me a while to figure it out, but after reading the source at `/usr/lib/python2.7/_MozillaCookieJar.py` I found that there were two bugs in your cookie2.txt file:

 * Missing dot at the beginning of the domain (in your case the IP address)
 * Using spaces as separator (use tabs)

Modified updated to docs to help others.
