### ISSUE TITLE
Shell page show when running mac os in virtualbox

### ISSUE THREAD

**Issue by MAN-2017** [andresriancho/w3af#17159]
I tired for setting up mac OS in virtualbox... 
when running mac  os in virtualbox , I see a shell page...
![error](https://user-images.githubusercontent.com/35096297/43518745-3f24c352-95a2-11e8-83d0-55c4f7051004.png)
 

please help me for solving this problem...

**Comment by andresriancho** [comment]
That has nothing to do with w3af.
