### ISSUE TITLE
Shell page show when running mac os in virtualbox 

### ISSUE THREAD

**Issue by MAN-2017** [andresriancho/w3af#17160]
Hi , I tired for setting up mac os in virtualbox...
shell page show when start virtualbox

![error](https://user-images.githubusercontent.com/35096297/43529418-7af30bdc-95c0-11e8-8e03-373c354c1bca.png)

please help... thanks...

**Comment by andresriancho** [comment]
Told you in the other issue you opened: this has nothing to do with w3af.
