### ISSUE TITLE
same  origin

### ISSUE THREAD

**Issue by kfr-ma** [andresriancho/w3af#17180]
Hi
 I have a target  https://a.domain.com  which contain scripts from other virtual hosts b.domain.com,c.domain.com ,  when i run spider man, w3af  scan only target defined .
How can make w3af scan all the subdomains ? is there any set target *.domain.com ? 

Thank you in advance.

**Comment by andresriancho** [comment]
That is one of w3af most annoying limitations. Only a few users find it,
but it is annoying because it can't be easily fixed.

W3af was designed to scan one target domain. Changing that would require
considerable effort and testing. That initial design flaw was what makes
this so annoying.

**Comment by kfr-ma** [comment]
HI andresriancho,

I understand now , thx ;:) ,  I bypass it by running multiple scan on multiple target by :
surfing on the primary target (spiderman)
defining the target as the other vhost.

 


 W3AF is awesome , i use it all the times , and i thank you for your work and your effort . 
I 


Regards.


Regards.
