### ISSUE TITLE
w3af_console_docker -t unstable Connection to 172.17.0.2 closed by remote host.

### ISSUE THREAD

**Issue by arputcu** [andresriancho/w3af#17279]
testing w3af on fedora 28 with the docker build 
i get 
Connection to 172.17.0.2 closed by remote host.
on the stable and unstable after all docker images are installed 

install log
https://gist.github.com/arputcu/96bb5d2bf5047f3252b4699fba8aac60

**Comment by arputcu** [comment]
looks like i had to stop the firewalld
sudo systemctl stop firewalld

but now i get 
sudo ./w3af_console_docker -t unstable                                                                                                                                             1 ↵  10480  01:04:55 
docker: Error response from daemon: driver failed programming external connectivity on endpoint distracted_meitner (7541ae1a81ed0f754893afaa847c527e962c11412938d8d688c25aa50c216cdf):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 44444 -j DNAT --to-destination 172.17.0.2:44444 ! -i docker0: iptables: No chain/target/match by that name.
 (exit status 1)).
w3af container failed to start: "Command 'docker run -d -v ~/.w3af:/root/.w3af -v ~/w3af-shared:/root/w3af-shared -p 44444:44444 andresriancho/w3af:unstable' returned non-zero exit status 125"

**Comment by arputcu** [comment]
hm this does not help after restart docker ads the iptables and i get the same first error

**Comment by andresriancho** [comment]
No idea what this is all about. Were you finally able to make it work? What was the root cause? Is there any definitive fix?

Asking so that others with the same problem that google to this issue can make it work. Trying to prevent this:

![wisdom_of_the_ancients](https://user-images.githubusercontent.com/865200/45963260-27c84b80-bff9-11e8-9e3a-bfbd94a3be7c.png)

**Comment by andresriancho** [comment]
PS: This doesn't seem to be a w3af-related issue, looks like docker-related.

**Comment by arputcu** [comment]
no sorry not found a solution so far , will update if i find one!
