### ISSUE TITLE
w3af console problem - Maximum crawl time limit hit, no new URLs will be added to the queue.

### ISSUE THREAD

**Issue by Xetzer** [andresriancho/w3af#17306]
Hello, I'm facing an issue while trying to run tests by w3af console.
Test execution hangs up after some time, the last log message is:

`Maximum crawl time limit hit, no new URLs will be added to the queue.`

Could you please tell me if there is a configurable parameter which could be tuned to solve this problem?
Thank you.

**Comment by andresriancho** [comment]
See `misc-settings` / `max_discovery_time`
