### ISSUE TITLE
Target URL with underscore not accepted

### ISSUE THREAD

**Issue by al3xdelarge** [andresriancho/w3af#17381]
This is not a bug, it's rather a feature request.

Defining target URLs  with underscore result in an error:

```
w3af/config:target>>> set target http://_sip.example.com:80
w3af/config:target>>> back
Identified an error with the user-defined settings:

    - Invalid format for target URL "http://_sip.example.com/", you have to specify the protocol (http/https/file) and a domain or IP address. Examples: http://host.tld/ ; https://127.0.0.1/ .

No information has been saved.
```

The error quite certainly comes from is_valid_domain (https://github.com/andresriancho/w3af/blob/356b14b975039706f4fd7f4f5db5b114cd75f14e/w3af/core/data/parsers/doc/url.py#L560).

Underscores in http hostnames are not allowed --> this is perfectly correct.
Still, there might exist websites that use underscore domains.

**Comment by andresriancho** [comment]
Thanks for reporting this, I learned a little bit about how underscores are used in hostnames!

Would you like to send a pull request for this issue?

**Comment by al3xdelarge** [comment]
Yes, I will!

**Comment by abankalarm** [comment]
hey i would like to know if this issue is still open as i am looking forward to contributing

**Comment by al3xdelarge** [comment]
> 
> 
> hey i would like to know if this issue is still open as i am looking forward to contributing

Thank you for getting in touch.
For me personally it is not an issue any more.
