### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Abdubek** [andresriancho/w3af#17455]
OS - Ubuntu16.04-amd64-PS, RAM 256

I reinstalled the server and started the installation with a clean operating system.

1. sudo apt-get update
2. sudo apt-get install git
3. python --version 2.7.12
4. sudo apt-get install python-pip
5. pip --version 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
6. git clone https://github.com/andresriancho/w3af.git
7. cd w3af/
8. ./w3af_console

<img width="1445" alt="screen shot 2018-11-30 at 2 43 18 pm" src="https://user-images.githubusercontent.com/16240224/49279301-522efd00-f4b1-11e8-9525-0eb7f750dfdb.png">

9. . /tmp/w3af_dependency_install.sh 
10. ./w3af_console

<img width="963" alt="screen shot 2018-11-30 at 2 54 08 pm" src="https://user-images.githubusercontent.com/16240224/49279363-7db1e780-f4b1-11e8-893c-6de3ecaea0e8.png">

11. . /tmp/w3af_dependency_install.sh 

<img width="980" alt="screen shot 2018-11-30 at 2 54 54 pm" src="https://user-images.githubusercontent.com/16240224/49279423-a639e180-f4b1-11e8-888b-7d13e04486d7.png">

I tried to download dependencies myself, but without success

**pip freeze**
acora==2.1
asn1crypto==0.24.0
backports-abc==0.5
biplist==1.0.3
blinker==1.4
bravado-core==5.0.2
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
cluster==1.1.1b3
ConfigArgParse==0.13.0
cryptography==2.4.2
darts.util.lru==0.5
diff-match-patch==20121119
ds-store==1.1.2
enum34==1.1.6
esmre==0.3.1
Flask==0.10.1
functools32==3.2.3.post2
future==0.17.1
futures==3.2.0
gitdb2==2.0.5
GitPython==2.1.3
guess-language==0.2
gyp==0.1
halberd==0.2.4
hpack==3.0.0
html2text==2018.1.9
idna==2.7
ipaddress==1.0.22
itsdangerous==1.1.0
Jinja2==2.10
jsonref==0.2
jsonschema==2.6.0
lxml==3.4.4
lz4==1.1.0
mac-alias==2.0.7
Markdown==2.6.1
MarkupSafe==1.1.0
mitmproxy==0.13
msgpack==0.5.6
msgpack-python==0.5.6
ndg-httpsclient==0.4.0
netlib==0.13.1
nltk==3.0.1
passlib==1.7.1
pdfminer==20140328
Pebble==4.3.8
phply==0.9.1
Pillow==5.3.0
ply==3.11
psutil==2.2.1
pyasn1==0.4.2
pybloomfiltermmap==0.3.14
pyClamd==0.4.0
pycparser==2.19
PyGithub==1.21.0
pyOpenSSL==18.0.0
pyparsing==2.3.0
pyperclip==1.7.0
python-dateutil==2.7.5
python-ntlm==1.0.1
pytz==2018.7
PyYAML==3.12
requests==2.20.1
rfc3987==1.3.8
ruamel.ordereddict==0.4.8
scapy==2.4.0
simplejson==3.16.0
singledispatch==3.4.0.3
six==1.11.0
smmap2==2.0.5
strict-rfc3339==0.7
swagger-spec-validator==2.4.1
tblib==0.2.0
termcolor==1.1.0
tldextract==1.7.2
tornado==5.1.1
urllib3==1.24.1
urwid==2.0.1
vulndb==0.1.0
vulners==1.3.0
webcolors==1.8.1
Werkzeug==0.14.1
You are using pip version 8.1.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by andresriancho** [comment]
This is strange...

What do you get when running `node --version`  and `nodejs --version` in a shell?

**Comment by andresriancho** [comment]
Try to make a symlink so that node points no nodejs and try the install again

**Comment by Abdubek** [comment]
`ln -s /usr/bin/nodejs /usr/bin/node`

solved my problem
