### ISSUE TITLE
./w3af_console can't install npm and libssl-dev on Ubuntu 18.04

### ISSUE THREAD

**Issue by WiiWalker** [andresriancho/w3af#17499]
Following the installation instructions from docs.w3af.org I cannot install npm and libssl-dev.
npm installs libssl1.0-dev and in the next step libssl-dev wants to remove libssl1.0-dev, node-gyp, nodejs-dev and npm.

I currently have npm manually installed (with libssl1.0-dev instead of libssl-dev). 

> ~/w3af/w3af$ . /tmp/w3af_dependency_install.sh
> Paketlisten werden gelesen... Fertig
> Abhängigkeitsbaum wird aufgebaut.
> Statusinformationen werden eingelesen.... Fertig
> Einige Pakete konnten nicht installiert werden. Das kann bedeuten, dass
> Sie eine unmögliche Situation angefordert haben oder, wenn Sie die
> Unstable-Distribution verwenden, dass einige erforderliche Pakete noch
> nicht erstellt wurden oder Incoming noch nicht verlassen haben.
> Die folgenden Informationen helfen Ihnen vielleicht, die Situation zu lösen:
> 
> Die folgenden Pakete haben unerfüllte Abhängigkeiten:
>  npm : Hängt ab von: node-gyp (>= 0.10.9) soll aber nicht installiert werden
> E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
```

```
#!/bin/bash
sudo apt-get -y install npm libssl-dev
npm install -g retire
```

```
acora==2.1
ansible==2.5.1
apache-libcloud==2.2.1
asn1crypto==0.24.0
backports-abc==0.5
biplist==1.0.3
blinker==1.4
bravado-core==5.0.2
certifi==2018.1.18
cffi==1.11.5
chardet==3.0.4
cluster==1.1.1b3
ConfigArgParse==0.13.0
cryptography==2.4.2
darts.util.lru==0.5
diff-match-patch==20121119
ds-store==1.1.2
enum34==1.1.6
esmre==0.3.1
Flask==0.10.1
functools32==3.2.3.post2
future==0.17.1
futures==3.2.0
gitdb2==2.0.5
GitPython==2.1.3
guess-language==0.2
gyp==0.1
halberd==0.2.4
hpack==3.0.0
html2text==2018.1.9
httplib2==0.9.2
idna==2.6
ipaddress==1.0.17
itsdangerous==1.1.0
Jinja2==2.10
jmespath==0.9.3
jsonref==0.2
jsonschema==2.6.0
keyring==10.6.0
keyrings.alt==3.0
lockfile==0.12.2
lxml==3.4.4
lz4==1.1.0
mac-alias==2.0.7
Markdown==2.6.1
MarkupSafe==1.0
mitmproxy==0.13
msgpack==0.5.6
msgpack-python==0.5.6
ndg-httpsclient==0.4.0
netaddr==0.7.19
netlib==0.13.1
nltk==3.0.1
paramiko==2.0.0
passlib==1.7.1
pdfminer==20140328
Pebble==4.3.8
phply==0.9.1
Pillow==5.3.0
ply==3.11
psutil==2.2.1
pyasn1==0.4.2
pybloomfiltermmap==0.3.14
pyClamd==0.4.0
pycparser==2.19
pycrypto==2.6.1
PyGithub==1.21.0
pygobject==3.26.1
pykerberos==1.1.14
pyOpenSSL==18.0.0
pyparsing==2.3.0
pyperclip==1.7.0
python-dateutil==2.7.5
python-ntlm==1.0.1
pytz==2018.7
pyxdg==0.25
PyYAML==3.12
requests==2.18.4
rfc3987==1.3.8
ruamel.ordereddict==0.4.8
scapy==2.4.0
SecretStorage==2.3.1
simplejson==3.13.2
singledispatch==3.4.0.3
six==1.11.0
smmap2==2.0.5
strict-rfc3339==0.7
swagger-spec-validator==2.4.1
tblib==0.2.0
termcolor==1.1.0
tldextract==1.7.2
tornado==5.1.1
urllib3==1.22
urwid==2.0.1
vulndb==0.1.0
vulners==1.3.0
webcolors==1.8.1
Werkzeug==0.14.1
xmltodict==0.11.0
```

`Python 2.7.15rc1`

**Comment by andresriancho** [comment]
Thanks for the bug report. Should be fixed in master now.

**Comment by jlcfly** [comment]
Still getting the issue during install. Installing libssl-dev removes npm. w3af then requires npm. Installing npm removes libssl-dev. w3af then requires libssl-dev. This is circular. Cannot fully install. Suggestions?

**Comment by Kidman1670** [comment]
This bug still exist, I use Ubuntu 18.04 too, someone please help solve this problem
