### ISSUE TITLE
who's backdoor?

### ISSUE THREAD

**Issue by hktalent** [andresriancho/w3af#17559]
why?
```
RUN echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDjXxcHjyVkwHT+dSYwS3vxhQxZAit6uZAFhuzA/dQ2vFu6jmPk1ewMGIYVO5D7xV3fo7/RXeCARzqHl6drw18gaxDoBG3ERI6LxVspIQYjDt5Vsqd1Lv++Jzyp/wkXDdAdioLTJyOerw7SOmznxqDj1QMPCQni4yhrE+pYH4XKxNx5SwxZTPgQWnQS7dasY23bv55OPgztI6KJzZidMEzzJVKBXHy1Ru/jjhmWBghiXYU5RBDLDYyT8gAoWedYgzVDmMZelLR6Y6ggNLOtMGiGYfPWDUz9Z6iDAUsOQBtCJy8Sj8RwSQNpmOgSzBanqnhed14hLwdYhnKWcPNMry71 w3af@w3af-docker.org' > /home/w3af/.ssh/w3af-docker.pub
RUN mkdir -p /root/.ssh/
RUN cat /home/w3af/.ssh/w3af-docker.pub >> /root/.ssh/authorized_keys
```
@see https://github.com/andresriancho/w3af/blob/master/extras/docker/Dockerfile#L37

**Comment by andresriancho** [comment]
If it is a backdoor, then it is well documenter, read the warning in [the docker docs](https://github.com/andresriancho/w3af/blob/master/doc/sphinx/docker.rst)

The SSH keys are in [this directory](https://github.com/andresriancho/w3af/tree/master/extras/docker/scripts/common) and are used by [these scripts](https://github.com/andresriancho/w3af/tree/master/extras/docker/scripts) to connect to the docker instance via SSH.
