### ISSUE TITLE
W3AF_GUI does not show results, log, etc.

### ISSUE THREAD

**Issue by linuxer86** [andresriancho/w3af#17681]
I'm using the last version of W3AF on Debian, installing it was hard but I finally got it (I'm writing a tutorial on this program because many users find difficulties to get it installed).

Everything seems to work, the scan runs and sometimes detects vulnerabilities but while it is scanning it does not show any progress or what is going on in the big white window, as you can see in this screenshot https://ibb.co/6ZkcdYn

I used W3AF years ago and had no problem, I wonder if maybe im doing something wrong and there is an option to enable verbosity in the graphical mode.

Would appreciate your help and name you in the article if you want.

**Comment by andresriancho** [comment]
> I'm using the last version of W3AF on Debian

Please don't, that is a really old one.

Install from this github repository and try with that.
