### ISSUE TITLE
Need help 

### ISSUE THREAD

**Issue by strunz983** [andresriancho/w3af#17758]
Hello i install w3af JavaScript Crawling and w3af_console is working fine buth when i start w3af_gui i get this message 
./w3af_gui
The GTK package requirements are not met, please make sure your system meets these requirements:
    - PyGTK >= 2.12
    - GTK >= 2.12

My OS is 
Linux kali 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux
 Thank you

**Comment by andresriancho** [comment]
Changed the dependency check module to return detailed errors.

https://github.com/andresriancho/w3af/commit/feaa612fa9fb2f4148f434011345cdb4435b57c9

Please `git pull` in the `feature/js` branch to get this change and try again. That should give you more detail on what is missing. If you can't figure the solution out with that detail please let me know and we'll figure it out.

**Comment by strunz983** [comment]
this is the message what i get when i try to start w3af_gui

(venv) root@kali:~/w3af# ./w3af_gui
The GTK package requirements are not met, please make sure your system meets these requirements:
    - PyGTK >= 2.12
    - GTK >= 2.12

**Comment by andresriancho** [comment]
Did you `git pull`? You should be seeing more detailed error messages.

**Comment by strunz983** [comment]
this is how i doing

https://pastebin.com/784KHEmu

**Comment by andresriancho** [comment]
Oh!

If you want to test the javascript crawling feature you need to be in the `feature/js` branch:

```
git clone https://github.com/andresriancho/w3af.git
cd w3af
git checkout feature/js
```

The last command is the one you're missing.

For testing the javascript crawling you won't need the GUI, you can use `w3af_console`
