### ISSUE TITLE
Parrot os installation error

### ISSUE THREAD

**Issue by jordantsap** [andresriancho/w3af#17774]
It is driving me mad, looping errors in circles

I downloaded git package,
i run ./w3af_console,
after running w3af_console, /tmp/w3af_dependency_install.sh and python -m pip install many times for each module, i finally limit the ammount of modules to get error:
Your python installation needs the following modules to run w3af:
    pyasn1 lxml cluster markdown psutil ruamel.ordereddict tldextract pebble acora diff_match_patch bravado_core vulners.

Then i run python -m pip install -i pyasn1 lxml cluster markdown psutil ruamel.ordereddict tldextract pebble acora diff_match_patch bravado_core vulners in order to install them, the output is:
Looking in indexes: pyasn1
Requirement already satisfied: lxml in /usr/lib/python2.7/dist-packages (4.3.2)
Requirement already satisfied: cluster in /home/jordan/.local/lib/python2.7/site-packages (1.4.1.post2)
Requirement already satisfied: markdown in /home/jordan/.local/lib/python2.7/site-packages (3.1)
Requirement already satisfied: psutil in /home/jordan/.local/lib/python2.7/site-packages (5.6.1)
Requirement already satisfied: ruamel.ordereddict in /home/jordan/.local/lib/python2.7/site-packages (0.4.13)
Requirement already satisfied: tldextract in /home/jordan/.local/lib/python2.7/site-packages (2.2.1)
Requirement already satisfied: pebble in /home/jordan/.local/lib/python2.7/site-packages (4.3.10)
Requirement already satisfied: acora in /home/jordan/.local/lib/python2.7/site-packages (2.2)
Requirement already satisfied: diff_match_patch in /home/jordan/.local/lib/python2.7/site-packages (20181111)
Requirement already satisfied: bravado_core in /home/jordan/.local/lib/python2.7/site-packages (5.12.0)
Requirement already satisfied: vulners in /home/jordan/.local/lib/python2.7/site-packages (1.4.9)
Requirement already satisfied: setuptools>=36 in /usr/lib/python2.7/dist-packages (from markdown) (40.8.0)
Requirement already satisfied: requests>=2.1.0 in /usr/lib/python2.7/dist-packages (from tldextract) (2.21.0)
Requirement already satisfied: requests-file>=1.4 in /home/jordan/.local/lib/python2.7/site-packages (from tldextract) (1.4.3)
Requirement already satisfied: idna in /usr/lib/python2.7/dist-packages (from tldextract) (2.6)
Requirement already satisfied: futures; python_version < "3" in /usr/lib/python2.7/dist-packages (from pebble) (3.2.0)
Requirement already satisfied: simplejson in /usr/lib/python2.7/dist-packages (from bravado_core) (3.16.0)
Requirement already satisfied: python-dateutil in /usr/lib/python2.7/dist-packages (from bravado_core) (2.7.3)
Requirement already satisfied: jsonschema[format]>=2.5.1 in /home/jordan/.local/lib/python2.7/site-packages (from bravado_core) (3.0.1)
Requirement already satisfied: msgpack-python>=0.5.2 in /home/jordan/.local/lib/python2.7/site-packages (from bravado_core) (0.5.6)
Requirement already satisfied: jsonref in /home/jordan/.local/lib/python2.7/site-packages (from bravado_core) (0.2)
Requirement already satisfied: pytz in /usr/lib/python2.7/dist-packages (from bravado_core) (2018.9)
Requirement already satisfied: enum34; python_version < "3.4" in /usr/lib/python2.7/dist-packages (from bravado_core) (1.1.6)
Requirement already satisfied: six in /home/jordan/.local/lib/python2.7/site-packages (from bravado_core) (1.10.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python2.7/dist-packages (from bravado_core) (3.12)
Requirement already satisfied: swagger-spec-validator>=2.0.1 in /home/jordan/.local/lib/python2.7/site-packages (from bravado_core) (2.4.3)
Requirement already satisfied: functools32; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from jsonschema[format]>=2.5.1->bravado_core) (3.2.3.post2)
Requirement already satisfied: attrs>=17.4.0 in /usr/lib/python2.7/dist-packages (from jsonschema[format]>=2.5.1->bravado_core) (18.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /home/jordan/.local/lib/python2.7/site-packages (from jsonschema[format]>=2.5.1->bravado_core) (0.14.11)
Requirement already satisfied: strict-rfc3339; extra == "format" in /home/jordan/.local/lib/python2.7/site-packages (from jsonschema[format]>=2.5.1->bravado_core) (0.7)
Requirement already satisfied: rfc3987; extra == "format" in /home/jordan/.local/lib/python2.7/site-packages (from jsonschema[format]>=2.5.1->bravado_core) (1.3.8)
Requirement already satisfied: webcolors; extra == "format" in /home/jordan/.local/lib/python2.7/site-packages (from jsonschema[format]>=2.5.1->bravado_core) (1.8.1)
Requirement already satisfied: jsonpointer>1.13; extra == "format" in /home/jordan/.local/lib/python2.7/site-packages (from jsonschema[format]>=2.5.1->bravado_core) (2.0)

Finallly running ./w3af_console i get:
Your python installation needs the following modules to run w3af:
    pyasn1 lxml cluster markdown psutil ruamel.ordereddict tldextract pebble acora diff_match_patch bravado_core vulners

After installing any missing operating system packages, use pip to install the remaining modules:
    sudo pip install pyasn1==0.4.2 lxml==3.4.4 cluster==1.1.1b3 markdown==2.6.1 psutil==5.4.8 ruamel.ordereddict==0.4.8 tldextract==1.7.2 pebble==4.3.8 acora==2.1 diff-match-patch==20121119 bravado-core==5.0.2 vulners==1.3.0

A script with these commands has been created for you at /tmp/w3af_dependency_install.sh

I run again:
python -m pip install pyasn1 lxml cluster markdown psutil ruamel.ordereddict tldextract pebble acora diff_match_patch bravado_core vulners
sudo pip install pyasn1==0.4.2 lxml==3.4.4 cluster==1.1.1b3 markdown==2.6.1 psutil==5.4.8 ruamel.ordereddict==0.4.8 tldextract==1.7.2 pebble==4.3.8 acora==2.1 diff-match-patch==20121119 bravado-core==5.0.2 vulners==1.3.0
. tmp/w3af_dependency_install.sh
and i get:
Requirement already satisfied: pyasn1==0.4.2 in /usr/lib/python2.7/dist-packages (0.4.2)
Collecting lxml==3.4.4
  Using cached https://files.pythonhosted.org/packages/63/c7/4f2a2a4ad6c6fa99b14be6b3c1cece9142e2d915aa7c43c908677afc8fa4/lxml-3.4.4.tar.gz
Requirement already satisfied: cluster==1.1.1b3 in /usr/local/lib/python2.7/dist-packages (1.1.1b3)
Requirement already satisfied: markdown==2.6.1 in /usr/local/lib/python2.7/dist-packages (2.6.1)
Requirement already satisfied: psutil==5.4.8 in /usr/local/lib/python2.7/dist-packages (5.4.8)
Requirement already satisfied: ruamel.ordereddict==0.4.8 in /usr/local/lib/python2.7/dist-packages (0.4.8)
Requirement already satisfied: tldextract==1.7.2 in /usr/local/lib/python2.7/dist-packages (1.7.2)
Requirement already satisfied: pebble==4.3.8 in /usr/local/lib/python2.7/dist-packages (4.3.8)
Requirement already satisfied: acora==2.1 in /usr/local/lib/python2.7/dist-packages (2.1)
Requirement already satisfied: diff-match-patch==20121119 in /usr/local/lib/python2.7/dist-packages (20121119)
Requirement already satisfied: bravado-core==5.0.2 in /usr/local/lib/python2.7/dist-packages (5.0.2)
Requirement already satisfied: vulners==1.3.0 in /usr/local/lib/python2.7/dist-packages (1.3.0)
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from tldextract==1.7.2) (40.8.0)
Requirement already satisfied: futures; python_version < "3" in /usr/lib/python2.7/dist-packages (from pebble==4.3.8) (3.2.0)
Requirement already satisfied: simplejson in /usr/lib/python2.7/dist-packages (from bravado-core==5.0.2) (3.16.0)
Requirement already satisfied: python-dateutil in /usr/lib/python2.7/dist-packages (from bravado-core==5.0.2) (2.7.3)
Requirement already satisfied: jsonschema[format]>=2.5.1 in /usr/local/lib/python2.7/dist-packages (from bravado-core==5.0.2) (3.0.1)
Requirement already satisfied: jsonref in /usr/local/lib/python2.7/dist-packages (from bravado-core==5.0.2) (0.2)
Requirement already satisfied: pytz in /usr/lib/python2.7/dist-packages (from bravado-core==5.0.2) (2018.9)
Requirement already satisfied: enum34; python_version < "3.4" in /usr/lib/python2.7/dist-packages (from bravado-core==5.0.2) (1.1.6)
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from bravado-core==5.0.2) (1.12.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python2.7/dist-packages (from bravado-core==5.0.2) (3.12)
Requirement already satisfied: swagger-spec-validator>=2.0.1 in /usr/local/lib/python2.7/dist-packages (from bravado-core==5.0.2) (2.4.3)
Requirement already satisfied: msgpack-python in /usr/local/lib/python2.7/dist-packages (from bravado-core==5.0.2) (0.5.6)
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (from vulners==1.3.0) (2.21.0)
Requirement already satisfied: functools32; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from jsonschema[format]>=2.5.1->bravado-core==5.0.2) (3.2.3.post2)
Requirement already satisfied: attrs>=17.4.0 in /usr/lib/python2.7/dist-packages (from jsonschema[format]>=2.5.1->bravado-core==5.0.2) (18.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /usr/local/lib/python2.7/dist-packages (from jsonschema[format]>=2.5.1->bravado-core==5.0.2) (0.14.11)
Requirement already satisfied: strict-rfc3339; extra == "format" in /usr/local/lib/python2.7/dist-packages (from jsonschema[format]>=2.5.1->bravado-core==5.0.2) (0.7)
Requirement already satisfied: idna; extra == "format" in /usr/lib/python2.7/dist-packages (from jsonschema[format]>=2.5.1->bravado-core==5.0.2) (2.6)
Requirement already satisfied: rfc3987; extra == "format" in /usr/local/lib/python2.7/dist-packages (from jsonschema[format]>=2.5.1->bravado-core==5.0.2) (1.3.8)
Requirement already satisfied: webcolors; extra == "format" in /usr/local/lib/python2.7/dist-packages (from jsonschema[format]>=2.5.1->bravado-core==5.0.2) (1.8.1)
Requirement already satisfied: jsonpointer>1.13; extra == "format" in /usr/local/lib/python2.7/dist-packages (from jsonschema[format]>=2.5.1->bravado-core==5.0.2) (2.0)
Building wheels for collected packages: lxml
  Running setup.py bdist_wheel for lxml ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-t1yIxR/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-r0H4VQ --python-tag cp27:
  Building lxml version 3.4.4.
  Building without Cython.
  ERROR: /bin/sh: 1: xslt-config: not found
  
  ** make sure the development packages of libxml2 and libxslt are installed **
  
  Using build configuration of libxslt
  /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/__init__.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/ElementInclude.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/doctestcompare.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/sax.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/builder.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/_elementpath.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/pyclasslookup.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/usedoctest.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/cssselect.py -> build/lib.linux-x86_64-2.7/lxml
  creating build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/__init__.py -> build/lib.linux-x86_64-2.7/lxml/includes
  creating build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/__init__.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/ElementSoup.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/formfill.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/_setmixin.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/html5parser.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/builder.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/diff.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/_html5builder.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/soupparser.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/usedoctest.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/defs.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/clean.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/_diffcommand.py -> build/lib.linux-x86_64-2.7/lxml/html
  creating build/lib.linux-x86_64-2.7/lxml/isoschematron
  copying src/lxml/isoschematron/__init__.py -> build/lib.linux-x86_64-2.7/lxml/isoschematron
  copying src/lxml/lxml.etree.h -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/lxml.etree_api.h -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xslt.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/tree.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/config.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xpath.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/schematron.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xinclude.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/uri.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/relaxng.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/c14n.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/lxml-version.h -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/etree_defs.h -> build/lib.linux-x86_64-2.7/lxml/includes
  creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources
  creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/rng
  copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/rng
  creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl
  creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  running build_ext
  building 'lxml.etree' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/src
  creating build/temp.linux-x86_64-2.7/src/lxml
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-Jh9aba/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/tmp/pip-install-t1yIxR/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w
  In file included from src/lxml/lxml.etree.c:239:
  /tmp/pip-install-t1yIxR/lxml/src/lxml/includes/etree_defs.h:14:10: fatal error: libxml/xmlversion.h: No such file or directory
   #include "libxml/xmlversion.h"
            ^~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for lxml
  Running setup.py clean for lxml
Failed to build lxml
Installing collected packages: lxml
  Found existing installation: lxml 4.3.2
    Not uninstalling lxml at /usr/lib/python2.7/dist-packages, outside environment /usr
    Can't uninstall 'lxml'. No files were found to uninstall.
  Running setup.py install for lxml ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-t1yIxR/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-WrtL2Q/install-record.txt --single-version-externally-managed --compile:
    Building lxml version 3.4.4.
    Building without Cython.
    ERROR: /bin/sh: 1: xslt-config: not found
    
    ** make sure the development packages of libxml2 and libxslt are installed **
    
    Using build configuration of libxslt
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/lxml
    copying src/lxml/__init__.py -> build/lib.linux-x86_64-2.7/lxml
    copying src/lxml/ElementInclude.py -> build/lib.linux-x86_64-2.7/lxml
    copying src/lxml/doctestcompare.py -> build/lib.linux-x86_64-2.7/lxml
    copying src/lxml/sax.py -> build/lib.linux-x86_64-2.7/lxml
    copying src/lxml/builder.py -> build/lib.linux-x86_64-2.7/lxml
    copying src/lxml/_elementpath.py -> build/lib.linux-x86_64-2.7/lxml
    copying src/lxml/pyclasslookup.py -> build/lib.linux-x86_64-2.7/lxml
    copying src/lxml/usedoctest.py -> build/lib.linux-x86_64-2.7/lxml
    copying src/lxml/cssselect.py -> build/lib.linux-x86_64-2.7/lxml
    creating build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/__init__.py -> build/lib.linux-x86_64-2.7/lxml/includes
    creating build/lib.linux-x86_64-2.7/lxml/html
    copying src/lxml/html/__init__.py -> build/lib.linux-x86_64-2.7/lxml/html
    copying src/lxml/html/ElementSoup.py -> build/lib.linux-x86_64-2.7/lxml/html
    copying src/lxml/html/formfill.py -> build/lib.linux-x86_64-2.7/lxml/html
    copying src/lxml/html/_setmixin.py -> build/lib.linux-x86_64-2.7/lxml/html
    copying src/lxml/html/html5parser.py -> build/lib.linux-x86_64-2.7/lxml/html
    copying src/lxml/html/builder.py -> build/lib.linux-x86_64-2.7/lxml/html
    copying src/lxml/html/diff.py -> build/lib.linux-x86_64-2.7/lxml/html
    copying src/lxml/html/_html5builder.py -> build/lib.linux-x86_64-2.7/lxml/html
    copying src/lxml/html/soupparser.py -> build/lib.linux-x86_64-2.7/lxml/html
    copying src/lxml/html/usedoctest.py -> build/lib.linux-x86_64-2.7/lxml/html
    copying src/lxml/html/defs.py -> build/lib.linux-x86_64-2.7/lxml/html
    copying src/lxml/html/clean.py -> build/lib.linux-x86_64-2.7/lxml/html
    copying src/lxml/html/_diffcommand.py -> build/lib.linux-x86_64-2.7/lxml/html
    creating build/lib.linux-x86_64-2.7/lxml/isoschematron
    copying src/lxml/isoschematron/__init__.py -> build/lib.linux-x86_64-2.7/lxml/isoschematron
    copying src/lxml/lxml.etree.h -> build/lib.linux-x86_64-2.7/lxml
    copying src/lxml/lxml.etree_api.h -> build/lib.linux-x86_64-2.7/lxml
    copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/xslt.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/tree.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/config.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/xpath.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/schematron.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/xinclude.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/uri.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/relaxng.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/c14n.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/lxml-version.h -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/etree_defs.h -> build/lib.linux-x86_64-2.7/lxml/includes
    creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources
    creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/rng
    copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/rng
    creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl
    creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    running build_ext
    building 'lxml.etree' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    creating build/temp.linux-x86_64-2.7/src/lxml
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-Jh9aba/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/tmp/pip-install-t1yIxR/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w
    In file included from src/lxml/lxml.etree.c:239:
    /tmp/pip-install-t1yIxR/lxml/src/lxml/includes/etree_defs.h:14:10: fatal error: libxml/xmlversion.h: No such file or directory
     #include "libxml/xmlversion.h"
              ^~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
  Can't roll back lxml; was not uninstalled
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-t1yIxR/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-WrtL2Q/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-t1yIxR/lxml/
┌─[✗]─[jordan@parrot]─[/media/jordan/Drive2Docs/Pentest/w3af]

and when i try ./w3af_console i get same output again

Your python installation needs the following modules to run w3af:
    pyasn1 lxml cluster markdown psutil ruamel.ordereddict tldextract pebble acora diff_match_patch bravado_core vulners

After installing any missing operating system packages, use pip to install the remaining modules:
    sudo pip install pyasn1==0.4.2 lxml==3.4.4 cluster==1.1.1b3 markdown==2.6.1 psutil==5.4.8 ruamel.ordereddict==0.4.8 tldextract==1.7.2 pebble==4.3.8 acora==2.1 diff-match-patch==20121119 bravado-core==5.0.2 vulners==1.3.0

A script with these commands has been created for you at /tmp/w3af_dependency_install.sh

**Comment by andresriancho** [comment]
Did you try to install inside a virtualenv?

**Comment by andresriancho** [comment]
http://docs.w3af.org/en/latest/advanced-install.html#installing-using-virtualenv

**Comment by jordantsap** [comment]
The error i had to see first was  In file included from src/lxml/lxml.etree.c:239:
  /tmp/pip-install-BizkKx/lxml/src/lxml/includes/etree_defs.h:14:10: fatal error: libxml/xmlversion.h: No such file or directory
   #include "libxml/xmlversion.h"
            ^~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for lxml
  Running setup.py clean for lxml
Failed to build lxml
So the command tyo do the trick was:
sudo apt-get install libxml2-dev libxslt1-dev did the trick

**Comment by jordantsap** [comment]
For gui also install PyGTK GTK
