### ISSUE TITLE
一个测试百变的问题

### ISSUE THREAD

**Issue by AnZhanLiangJian** [andresriancho/w3af#17915]
root@kali:~/Documents/w3af# ./w3af_gui
External programs used by w3af are not installed or were not found.Run these commands to install them on your system:

    npm install -g retire
    npm update -g retire

A script with these commands has been created for you at /tmp/w3af_dependency_install.sh

求解，这是什么情况？

**Comment by imidoriya** [comment]
+1 Also having this issue.  Running macOS Mojave 10.14.5
I can confirm that retire is installed and appears to work fine.  As far as I can tell, every requirement is met and working, but I can't launch the console or the gui without getting this message.

**Comment by imidoriya** [comment]
Figured out the issue for me.  w3af wants retire 2.x, which is a beta.  The latest [release of retire](https://www.npmjs.com/package/retire) on the npmjs site (as of this moment) is 1.6.3.  So running `npm install -g retire` and the `npm update -g retire` only installs that version, which is insufficient.  

I had to run this to get it to work.  
`npm install -g retire@2.0.3`

**Comment by andresriancho** [comment]
Improved in https://github.com/andresriancho/w3af/commit/d39da94ed340f6261c82218801a2fcf226629772 using @imidoriya feedback
