### ISSUE TITLE
Exceptions raised from audit plugin when using OWASP_TOP_10

### ISSUE THREAD

**Issue by NischaiV** [andresriancho/w3af#17924]
Hi,

Any suggestion to resolve the below error? 

> w3af/profiles>>> use OWASP_TOP10 
> The profile you are trying to load (OWASP_TOP10) seems to be outdated, this is a common issue which happens when the framework is updated and one of its plugins adds/removes one of the configuration parameters referenced by a profile, or the plugin is removed all together.
> 
> The profile was loaded but some of your settings might have been lost. This is the list of issues that were found:
> 
>     - Setting the options for plugin "audit.ssl_certificate" raised an exception due to unknown or invalid configuration parameters. The OptionList doesn't contain an option with the name: "minExpireDays"
>     - Setting the options for plugin "infrastructure.allowed_methods" raised an exception due to unknown or invalid configuration parameters. The OptionList doesn't contain an option with the name: "reportDavOnly"
> 
> We recommend you review the specific plugin configurations, apply the required changes and save the profile in order to update it and avoid this message. If this warning does not disappear you can manually edit the profile file to fix it.

When I start the scan, it runs and outputs in terminal about some workerthreads being idle. Is that normal? It has been running for quite sometime (ofcourse more than 20 minutes).

Thanks and regards
Nischai

**Comment by andresriancho** [comment]
Thanks for reporting that, it was a bug, fixed in https://github.com/andresriancho/w3af/commit/12fa751be9bfc945aebb43002fa4d8911d12641f

Just use `git pull` to get the latest from `master` and that should be fixed.

**Comment by NischaiV** [comment]
Thanks Andres. Is it also a bug regarding the second issue?

> - Setting the options for plugin "infrastructure.allowed_methods" raised an exception due to unknown or invalid configuration parameters. The OptionList doesn't contain an option with the name: "reportDavOnly"

**Comment by NischaiV** [comment]
I renamed the variable 'reportDavOnly' in the below files to 'dav_only' as per the usage:

> profiles/full_audit.pw3af 
> profiles/web_infrastructure.pw3af 
> profiles/OWASP_TOP10.pw3af

**Comment by andresriancho** [comment]
Sorry, I thought I had fixed all instances.
