### ISSUE TITLE
retire retirejs wrong expecting a version that doesn't appear to exist

### ISSUE THREAD

**Issue by HankQuiter** [andresriancho/w3af#17922]
Posted this in my PR request too (https://github.com/andresriancho/w3af/pull/17911) sorry for the double post but I am baffled 
It is either really unclear as to what you are calling "retire" or "retirejs" . but there is no version 2.*
https://github.com/RetireJS/retire.js/releases
https://www.npmjs.com/package/retire
could you or someone who reads this point me in the direction of the version of "retire" or "retirejs" you expect to be used with w3af
Because I cannot find it
Thank you for your time.

**Comment by andresriancho** [comment]
You should install the latest `retirejs` using `npm install -g retire@2.0.3`

Improved dependency check in https://github.com/andresriancho/w3af/commit/d39da94ed340f6261c82218801a2fcf226629772
