### ISSUE TITLE
w3af complains retire is not installed, even after installing it!

### ISSUE THREAD

**Issue by NischaiV** [andresriancho/w3af#17921]
I am always getting the below error when I try to run w3af_console from my Ubuntu machine:

> External programs used by w3af are not installed or were not found.Run these commands to install them on your system:
> 
>     npm install -g retire
>     npm update -g retire
> 
> A script with these commands has been created for you at /tmp/w3af_dependency_install.sh

I installed retire by executing the above commands and executed /tmp/w3af_dependency_install.sh script as well to be sure.

> retire -V
> 1.6.3

Even then I am getting this error. Kindly help.

> cat /etc/lsb-release
> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=18.04
> DISTRIB_CODENAME=bionic
> DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

> cat /tmp/w3af_dependency_install.sh
> #!/bin/bash
> npm install -g retire
> npm update -g retire

> pip freeze
> acora==2.1
> asn1crypto==0.24.0
> attrs==19.1.0
> backports-abc==0.5
> biplist==1.0.3
> blinker==1.4
> bravado-core==5.12.1
> certifi==2019.3.9
> cffi==1.12.3
> chardet==3.0.4
> cluster==1.1.1b3
> colorama==0.4.1
> ConfigArgParse==0.14.0
> cryptography==2.7
> darts.util.lru==0.5
> diff-match-patch==20121119
> ds-store==1.1.2
> enum34==1.1.6
> esmre==0.3.1
> Flask==0.10.1
> functools32==3.2.3.post2
> future==0.17.1
> futures==3.2.0
> gitdb2==2.0.5
> GitPython==2.1.3
> guess-language==0.2
> gyp==0.1
> halberd==0.2.4
> hpack==3.0.0
> html2text==2018.1.9
> idna==2.6
> ipaddress==1.0.17
> ipaddresses==0.0.2
> itsdangerous==1.1.0
> Jinja2==2.10
> jsonpointer==2.0
> jsonref==0.2
> jsonschema==3.0.1
> keyring==10.6.0
> keyrings.alt==3.0
> lxml==3.4.4
> lz4==1.1.0
> mac-alias==2.0.7
> Markdown==2.6.1
> MarkupSafe==1.1.1
> mitmproxy==0.13
> msgpack==0.5.6
> msgpack-python==0.5.6
> ndg-httpsclient==0.4.0
> netlib==0.13.1
> nltk==3.0.1
> passlib==1.7.1
> pdfminer==20140328
> Pebble==4.3.8
> phply==0.9.1
> Pillow==6.0.0
> ply==3.11
> psutil==5.4.8
> pyasn1==0.4.2
> pybloomfiltermmap==0.3.14
> pycairo==1.16.2
> pyClamd==0.4.0
> pycparser==2.19
> pycrypto==2.6.1
> PyGithub==1.21.0
> pygobject==3.26.1
> pyOpenSSL==18.0.0
> pyparsing==2.4.0
> pyperclip==1.7.0
> pyrsistent==0.15.2
> python-dateutil==2.8.0
> python-ntlm==1.0.1
> pytz==2019.1
> pyxdg==0.25
> PyYAML==3.12
> requests==2.22.0
> rfc3987==1.3.8
> ruamel.ordereddict==0.4.8
> scapy==2.4.0
> SecretStorage==2.3.1
> simplejson==3.16.0
> singledispatch==3.4.0.3
> six==1.11.0
> smmap2==2.0.5
> strict-rfc3339==0.7
> subprocess32==3.5.4
> swagger-spec-validator==2.4.3
> tblib==0.2.0
> termcolor==1.1.0
> tldextract==1.7.2
> tornado==5.1.1
> urllib3==1.25.3
> urwid==2.0.1
> vulndb==0.1.1
> vulners==1.3.0
> webcolors==1.9.1
> Werkzeug==0.15.4
 

> python --version
> Python 2.7.15+

Regards
Nischai

**Comment by CarbonC** [comment]
Same here

**Comment by HankQuiter** [comment]
I am trying to get an explanation for why it is looking for version 2.* of retire
look in my pull request https://github.com/andresriancho/w3af/pull/17911
for the code  change that I proposed to fix this.
Currently I cannot find a 2.* version of retire anywhere so it appears to be looking for a phantom package that does not exist... yet
My question asking for a follow up must came just after this question - I didn't see yours.
https://github.com/andresriancho/w3af/issues/17922

**Comment by andresriancho** [comment]
You should install the latest `retirejs` using `npm install -g retire@2.0.3`

Improved dependency check in https://github.com/andresriancho/w3af/commit/d39da94ed340f6261c82218801a2fcf226629772
