### ISSUE TITLE
w3af_api ImportError: cannot import name select_ip_version

### ISSUE THREAD

**Issue by rohithkd** [andresriancho/w3af#17999]
I was able to get w3af_console and w3af_gui up and running. On running w3af_api, I am getting an import error.
`./w3af_api
Traceback (most recent call last):
  File "./w3af_api", line 12, in <module>
    from w3af.core.ui.api.main import main
  File "/home/roots/w3af/w3af/core/ui/api/__init__.py", line 1, in <module>
    from .utils.mp_flask import ThreadedFlask
File "/home/roots/w3af/w3af/core/ui/api/utils/mp_flask.py", line 7, in <module>
from werkzeug.serving import select_ip_version
ImportError: cannot import name select_ip_version`

I fixed it by editing [w3af/core/ui/api/utils/mp_flask.py](https://github.com/andresriancho/w3af/blob/master/w3af/core/ui/api/utils/mp_flask.py).

I replaced `from werkzeug.serving import select_ip_version` with `from werkzeug.serving import *`. This fixed the issue for me. 

How can we solve the issue ? Is the module `select_ip_version` valid now?

**Comment by wangenlei-git** [comment]
How did you solve the problem? I'm a little confused.

**Comment by shyixiu** [comment]
Select_ip_version is a function of werkzeug.serving.py, but it's removed since werkzeug 0.15

**Comment by andresriancho** [comment]
Just merged a bunch of changes from the `develop` branch. One of those changes should fix this issue.
