### ISSUE TITLE
Docker w3af asking for password?

### ISSUE THREAD

**Issue by fightthepower** [andresriancho/w3af#18030]
So I have pulled w3af docker using `docker pull andresriancho/w3af` and then I went to the project folder and typed  `sudo ./w3af_console_docker` . After entering my password It goes inside the docker terminal and again asking for password `root@172.17.0.3's password:` . My question is it safe to enter my device password? Why docker w3af requires a password?

**Comment by andresriancho** [comment]
`sudo` is requiring you the password in order to run `docker` with elevated privileges.

The password is used by `sudo` and never sent to w3af itself, so it is safe for you to run this.

**Comment by ghaurii** [comment]
Hi, I am facing an issue in running w3af using docker. It asks me for root@172.17..0.3's password. when I enter my root password it does not accept it and exits. I have confirmed that my password is correct like 50 times.
