### ISSUE TITLE
Python DeprecationWarning, failure to set cookie_jar_file -> http-settings

### ISSUE THREAD

**Issue by JohnyK07** [andresriancho/w3af#18058]
<img width="1815" alt="Screen Shot" src="https://user-images.githubusercontent.com/54043631/62898581-d49bdc00-bd23-11e9-8c83-14ddde266d17.png">

w3af>>> http-settings>>>set cookie_jar_file /path/to/the/cookie.txt
I've been trying to use a cookies.txt file because dvwa uses a csrf token, but I cannot proceed as even if I give the correct Netscape format, the cookies.txt file will not be accepted after typing save in w3af_console! The output message for most of the times is the following:   
-------------------------------------------/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_MozillaCookieJar.py:109: UserWarning: cookielib bug!
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_MozillaCookieJar.py", line 82, in _really_load
    assert domain_specified == initial_dot
AssertionError

  _warn_unhandled_exception()
/Users/john/w3af/w3af/core/data/url/opener_settings.py:190: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  if cle.message.startswith('invalid Netscape format cookies file'):
Identified an error with the user-defined settings:

    - The supplied cookiejar file is not in Netscape format please review our documentation at http://docs.w3af.org/en/latest/authentication.html#setting-http-cookie to better understand the required format. 

No information has been saved.
-------------------------------------------
However, I am sure that the format is correct and I follow every step that the documentation points out! This is the context of my cookies.txt file:
# Netscape HTTP Cookie File
.subdomain.domain.com	FALSE	/dvwa/login.php/	FALSE	0	security	low
.subdomain.domain.com	FALSE	/	FALSE	0	PHPSESSID	1se7nkdd827uo225e375lk6d5

[cookies.txt](https://github.com/andresriancho/w3af/files/3497471/cookies.txt)

I retrieve the cookies with the following command: wget --keep-session-cookies --save-cookies cookies.txt http://subdomain.domain/dvwa/login.php/
Then I modify the cookies.txt file to bring it in a Netscape format (using dot before domain and tabs between values). Furthermore, the cookies.txt comes with 0 (null value) for the expiration field, I changed that by giving a valid Unix TimeStamp value (eg August 23rd 2019 random time-date) and it does not work as well, w3af_console prompts the same message as before.... 
Any ideas what is not working as it suppose to work? Has something to do with the Python version and the deprecation warnings?

**Comment by andresriancho** [comment]
Not related with the deprecation warning.

Fixed in ee9e6cf3d6bb414e8dbc0d4db2313cb32dc8b39a

The problem was with the `cookies.txt` file, which doesn't follow the format (or the way that python implements the format). I had to subclass python's `MozillaCookieJar` to provide better error messages.

You should get the latest from the `develop` branch (where this fix lives) and try again. You'll see a way more descriptive error message, which you can then use to fix `cookies.txt`
