### ISSUE TITLE
Plugins(Grep:error_500, Infrastructure:server_header)  run by default

### ISSUE THREAD

**Issue by w5b2e** [andresriancho/w3af#18053]
For my test I activate single audit and grep plugins, but not the grep:error_500 plugin or the infrastructure:server_header plugin.
In the xml report at scan-info both plugins are listed. I also see them in the html report.
I tried to disable them which works for other plugins but not for them.

I run the following script:

plugins
output xml_file
output config xml_file
set output_file (Path+Filename).xml
back
output html_file
output config html_file
set output_file (Path+Filename).html
back
crawl import_results
crawl config import_results
set input_base64 (Path+Filename).csv
back
audit blind_sqli csrf eval file_upload
audit format_string frontpage global_redirect
audit ldapi lfi os_commanding
audit redos response_splitting sqli websocket_hijacking
audit xpath xss xst
grep click_jacking code_disclosure content_sniffing cross_domain_js error_pages  
grep hash_analysis html_comments http_in_body
grep strange_reason url_session xss_protection_header
grep analyze_cookies csp directory_indexing dom_xss form_autocomplete
grep keys path_disclosure     
grep strange_parameters strict_transport_security user_defined_regex
back
target
set target {Target IP}
back
start
exit

Later I added the following commands to disable the both plugins:
infrastructure !server_header
grep !error_500
Didn't work either.

![w3af version](https://user-images.githubusercontent.com/53855700/62608718-a7ed5c00-b900-11e9-938c-f7ad3a9f6d2c.jpg)

**Comment by andresriancho** [comment]
I'm not sure I fully understand the bug report.

Just in case you don't know, some plugins have dependencies, for example: https://github.com/andresriancho/w3af/blob/356b14b975039706f4fd7f4f5db5b114cd75f14e/w3af/plugins/infrastructure/hmap.py#L140-L147

In most cases those dependencies are required (plugin A depends on B, if B is not enabled and run before A, then A can't do anything), in some other cases they are "soft dependencies". In the code there is no distinction made between those two.

**Comment by andresriancho** [comment]
If you enable plugin A, and it has a dependency, it is automatically enabled too. There is no way to disable that right now.

If you want to disable it, just modify the plugin code from A, cross your fingers and run the scan :-)

**Comment by w5b2e** [comment]
I didn't know that some plugins have dependencies. Thanks for the quick response.
