### ISSUE TITLE
Idea for w3af on online platform

### ISSUE THREAD

**Issue by testt23** [andresriancho/w3af#18077]
I came up with the following idea (like acunetix) to have a web based option this W3AF scanner as a module, what do you think?

**Comment by lucasvazq** [comment]
@testt23 w3af now rest in peace, don't wake up him

**Comment by andresriancho** [comment]
These commits don't look like the ones from a dead project!

https://github.com/andresriancho/w3af/commits/develop
https://github.com/andresriancho/w3af/commits/master
