### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by Q-back** [andresriancho/w3af#18430]
# Tests fails in w3af

Currently I'm not able to just run nosetest and make it pass. At some point tests hangs and I kill it after 10 minutes of inactivity. I was able to accomplish test run by skipping some performance tests. The final result was:
```
Ran 2583 tests in 1587.648s
FAILED (SKIP=33, errors=886, failures=131)
```
So generally we have about 2.6k tests, it's impressive, but as I can see there are really many tests which should be refactored or shouldn't run under normal conditions. I mean all performance tests, all tests which depend on another tests or test which communicate with outside world.

## Solution
My idea is to write script which will:
* mark all tests which fails as deprecated and skip them
* mark all tests which takes longer than few seconds as performance and skip them

Right now we can’t run passing test suite anyway, so it’s better than nothing. After that when developer works on feature x and see some tests skipped he can look after them and fix them.

I'd like to switch to pytest. Nose seems to be a bit abandoned as last commit is from 2016 https://github.com/nose-devs/nose. Also pytest dependency injection is really powerful.
In general I think all tests should be passing under 5 minutes. Then we're good.

**Comment by andresriancho** [comment]
👏

**Comment by Q-back** [comment]
Done https://github.com/andresriancho/w3af/commit/02aed8190cb8872ad9502d94e4efed5535b8ee7f

**Comment by Q-back** [comment]
Done https://github.com/andresriancho/w3af/commit/02aed8190cb8872ad9502d94e4efed5535b8ee7f
