### ISSUE TITLE
./w3af_dependency_install.sh   error

### ISSUE THREAD

**Issue by michaellelt** [andresriancho/w3af#18451]
ERROR:Could not find a version that satisfies the requirement gitdb>=4.0.1(from gitdb2>=2.0.0->GitPython==2.1.3) (from versions:0.5.0,0.5.1,0.5.2,0.5.3,0.5.4,0.6.0,0.6.1,0.6.2,0.6.3,0.6.4)
ERROR:No matching distribution found for gitdb>=4.0.1 (from gitdb2>=2.0.2->GitPython==2.1.3)

**Comment by jaredbeck** [comment]
It looks like `gitdb` requires Python 3?

https://github.com/gitpython-developers/gitdb/blob/master/setup.py#L25

**Comment by michaellelt** [comment]
thanks a lot.

**Comment by Q-back** [comment]
fixed with https://github.com/andresriancho/w3af/pull/18446
