### ISSUE TITLE
SyntaxError multiple exception types must be parentisized

### ISSUE THREAD

**Issue by highrider0602** [andresriancho/w3af#18871]
└─# ./w3af_gui    
  File "/home/warewolf/Downloads/sec_files/w3af-1.6.49/./w3af_gui", line 52
    except Exception, e:
           ^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

This is the output i get when i run the gui, same thing for the console, I have searchhed the official website and the issues section here on github but can not find this issue anywhere. any help with this is much appreciated. thank you

**Comment by codders** [comment]
Hi @highrider0602 ,

The code for w3af is unmaintained and only runs against python2 (which is no longer a supported version of python). You can check out the updated project at https://github.com/w4af/w4af - the GUI isn't currently available on that project, but the CLI and API functions should work okay.

**Comment by highrider0602** [comment]
thnak you for the information
