### ISSUE TITLE
upgrade dependences requirement

### ISSUE THREAD

**Issue by blshkv** [andresriancho/w3af#2611]
Hello,

I've ported w3af to Pentoo Linux but it was pain. The main problem was the dependences issue. The stable version of w3af is using some unreleased (such as phply, which just has been released btw) software, and some really old packages such as lxml-2.3.2 or pdfminer-20110515 (both 3 years old).

It's hard to support that devil mixture of packages. Please keep them at descent versions.

Thank you.

**Comment by andresriancho** [comment]
These were updated in the latest `develop`

**Comment by blshkv** [comment]
please release a new version at some point so I could push it as well. Thank you.

**Comment by andresriancho** [comment]
Yes, I'm working on releasing a new version (at least merge develop into master), hopefully I'll be able to do it next week.
