### ISSUE TITLE
Install instructions for OS X 10.9.4

### ISSUE THREAD

**Issue by justinhartman** [andresriancho/w3af#4562]
Just a heads up that this is what worked for me to get the GUI running on 10.9.4 https://gist.github.com/justinhartman/3f951865dd50dd05ca22. You guys asked in the docs for us to notify you on what worked so here it is.

**Comment by andresriancho** [comment]
@justinhartman ping! I would really appreciate it if you could take the time to contribute to the macosx.py file .

Closing since this has been inactive for a loooong time. Feel free to send that PR at any time :+1:
