### ISSUE TITLE
Mac Installation not working

### ISSUE THREAD

**Issue by indera** [andresriancho/w3af#5641]
Steps 

<pre>
uname -a
Darwin MacBook-Pro.local 13.3.0 Darwin Kernel Version 13.3.0: Tue Jun  3 21:27:35 PDT 2014; root:xnu-2422.110.17~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,3 Darwin
</pre>

Checking installed packages
<pre>
for lib in clamd PyGithub GitPython pybloomfiltermmap esmre phply nltk chardet pdfminer futures pyOpenSSL lxml scapy-real guess-language cluster msgpack-python python-ntlm halberd darts.util.lru; do pip freeze | grep $lib; done
clamd==1.0.1
PyGithub==1.21.0
GitPython==0.3.2.RC1
pybloomfiltermmap==0.3.11
esmre==0.3.1
phply==0.9.1
nltk==2.0.4
chardet==2.1.1
pdfminer==20110515
futures==2.1.5
pyOpenSSL==0.13.1
lxml==2.3.2
scapy-real==2.2.0-dev
guess-language==0.2
cluster==1.1.1b3
msgpack-python==0.2.4
python-ntlm==1.0.1
halberd==0.2.4
darts.util.lru==0.5

</pre>

Looks like I have all I need, but

<pre>
./w3af_console
Your python installation needs the following modules to run w3af:
    clamd github git.util pybloomfilter esmre phply nltk chardet pdfminer concurrent.futures OpenSSL lxml scapy.config guess_language cluster msgpack ntlm Halberd darts.lib.utils

After installing any missing operating system packages, use pip to install the remaining modules:
    sudo pip install clamd==1.0.1 PyGithub==1.21.0 GitPython==0.3.2.RC1 pybloomfiltermmap==0.3.11 esmre==0.3.1 phply==0.9.1 nltk==2.0.4 chardet==2.1.1 pdfminer==20110515 futures==2.1.5 pyOpenSSL==0.13.1 lxml==2.3.2 scapy-real==2.2.0-dev guess-language==0.2 cluster==1.1.1b3 msgpack-python==0.2.4 python-ntlm==1.0.1 halberd==0.2.4 darts.util.lru==0.5

A script with these commands has been created for you at /var/folders/8l/c6jjdl5x4zd4msdzdqrtxt4w0000gn/T/w3af_dependency_install.sh

cat /var/folders/8l/c6jjdl5x4zd4msdzdqrtxt4w0000gn/T/w3af_dependency_install.sh
#!/bin/bash

sudo pip install clamd==1.0.1 PyGithub==1.21.0 GitPython==0.3.2.RC1 pybloomfiltermmap==0.3.11 esmre==0.3.1 phply==0.9.1 nltk==2.0.4 chardet==2.1.1 pdfminer==20110515 futures==2.1.5 pyOpenSSL==0.13.1 lxml==2.3.2 scapy-real==2.2.0-dev guess-language==0.2 cluster==1.1.1b3 msgpack-python==0.2.4 python-ntlm==1.0.1 halberd==0.2.4 darts.util.lru==0.5

</pre>

**Comment by andresriancho** [comment]
Closing since I never got a response
