### ISSUE TITLE
web_spider sslv3 handshake failure

### ISSUE THREAD

**Issue by andersonDadario** [andresriancho/w3af#5802]
The web_spider plugin got an error while requesting "https://dadario.com.br/blog/apple-entenda-o-vazamento-de-udids-parte-1/". Reason: "[Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure"

As servers mitigate POODLE attack (sslv3), the web_spider can't connect anymore. Need add support for TLSv1.2 TLSv1.1 TLSv1

**Comment by andresriancho** [comment]
Trying to fix this once again could you give me the output of running https://gist.github.com/andresriancho/77d1d163c9987966ce77 in your system please?

**Comment by andresriancho** [comment]
My output is:

```
[pablo:/home/pablo/pch/w3af] feature/poodle(+1/-1) ± python conn.py 
Traceback (most recent call last):
  File "conn.py", line 5, in <module>
    sock = ssl.wrap_socket(sock, None, None, ssl_version=ssl.PROTOCOL_TLSv1)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [Errno 1] _ssl.c:510: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure
[pablo:/home/pablo/pch/w3af] feature/poodle(+1/-1) 1 ± 
```

**Comment by andersonDadario** [comment]
Mine is:

$ python
>>> import socket
>>> import ssl
>>>
... sock = socket.create_connection(('dadario.com.br', 443))
>>> sock = ssl.wrap_socket(sock, None, None, ssl_version=ssl.PROTOCOL_TLSv1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [Errno 1] _ssl.c:510: error:14094410:SSL
routines:SSL3_READ_BYTES:sslv3 alert handshake failure

2015-01-30 22:39 GMT-02:00 Andres Riancho <notifications@github.com>:

> My output is:
>
> [pablo:/home/pablo/pch/w3af] feature/poodle(+1/-1) ± python conn.py
> Traceback (most recent call last):
>   File "conn.py", line 5, in <module>
>     sock = ssl.wrap_socket(sock, None, None, ssl_version=ssl.PROTOCOL_TLSv1)
>   File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
>     ciphers=ciphers)
>   File "/usr/lib/python2.7/ssl.py", line 243, in __init__
>     self.do_handshake()
>   File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLError: [Errno 1] _ssl.c:510: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure
> [pablo:/home/pablo/pch/w3af] feature/poodle(+1/-1) 1 ±
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andresriancho/w3af/issues/5802#issuecomment-72294861>.
>



-- 
*Anderson Dadario* <https://www.linkedin.com/in/andersondadario>@andersonmvd
<https://twitter.com/andersonmvd>http://dadario.com.br

**Comment by andresriancho** [comment]
@andersonDadario which OS and version on your workstation? (I know I asked this before, but not specifically for this test)

**Comment by andresriancho** [comment]
http://runnable.com/VM6q-SvfvRRn_GLj/output

**Comment by andresriancho** [comment]
Read somewhere that this could be because of SNI (requests module had this issue)

**Comment by andresriancho** [comment]
http://my.gauntlet.io/ has SSLv3 disabled and the test script works well against it

**Comment by andresriancho** [comment]
After some more tests:
 * It seems to be safe to say that: w3af (in feature/poodle branch at least) can scan a site that has sslv3 disabled
 * just checked and w3af (develop branch) can also scan gauntlet.io
 * the fix I added in feature/poodle doesn't seem to help (or break) anything related with ssl

This guides us in the direction of a SNI error, and not the initial assessment from Anderson about "As servers mitigate POODLE attack (sslv3), the web_spider can't connect anymore. Need add support for TLSv1.2 TLSv1.1 TLSv1"

**Comment by andresriancho** [comment]
* Python's ssl module implements SNI only [in late releases that most linux distributions don't have yet.](http://bugs.python.org/issue5639)
 * [pyOpenSSL does have SNI support](https://github.com/msabramo/pyOpenSSL/blob/master/examples/sni/client.py)
 * There is a [hack](https://pypi.python.org/pypi/ssl_sni/0.1) which I could use to fix my issue...

**Comment by andresriancho** [comment]
[Tested with a fix for SNI](https://gist.github.com/andresriancho/77d1d163c9987966ce77#comment-1384823)

**Comment by andersonDadario** [comment]
You're amazing. Congratulations for the fix :P

2015-02-01 22:18 GMT-02:00 Andres Riancho <notifications@github.com>:

> Tested with a fix for SNI
> <https://gist.github.com/andresriancho/77d1d163c9987966ce77#comment-1384823>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andresriancho/w3af/issues/5802#issuecomment-72393104>.
>



-- 
*Anderson Dadario* <https://www.linkedin.com/in/andersondadario>@andersonmvd
<https://twitter.com/andersonmvd>http://dadario.com.br

**Comment by andresriancho** [comment]
[Latest commit](https://github.com/andresriancho/w3af/commit/77c8f79f4aacfc4c77bd14c42188adc655c41cc7) has the following features:
 * Timeout works for SSL
 * Timeout works for HTTP
 * I can scan dadario.com.br site (SNI enabled)

Missing tests:
 * Can we still scan a site that doesn't have a valid certificate? (unittest)
 * Are the timeouts working as expected? (unittest)

**Comment by andresriancho** [comment]
https://github.com/pyca/pyopenssl/issues/168

**Comment by andresriancho** [comment]
Just need to make all tests pass at circleci and I'll merge this into develop

**Comment by andresriancho** [comment]
Fuc**** never ending story! Now httpretty doesn't support openssl so all my mocked tests which use https are failing! https://circleci.com/gh/andresriancho/w3af/tree/feature%2Fpoodle

**Comment by andresriancho** [comment]
https://github.com/gabrielfalcao/HTTPretty/pull/215
https://travis-ci.org/gabrielfalcao/HTTPretty

**Comment by andresriancho** [comment]
Much better but still not PASS:
 * https://circleci.com/gh/andresriancho/w3af/1346

**Comment by andresriancho** [comment]
Looks much better, only one test is failing :+1: 
https://circleci.com/gh/andresriancho/w3af/1352

**Comment by andresriancho** [comment]
All tests but the `test_rfi.py` are PASSing, I want to fix that one because my OCD won't let me sleep.

**Comment by andresriancho** [comment]
Fixed in https://github.com/andresriancho/w3af/commit/03eaf0bc51343358f550ad77698824e87dacd746

**Comment by andresriancho** [comment]
OMGWTFBBQ

**Comment by andersonmvd** [comment]
Nice job :)

*Anderson Dadario* <https://www.linkedin.com/in/andersondadario>@andersonmvd
<https://twitter.com/andersonmvd>
http://dadario.com.br

2015-02-04 19:08 GMT-02:00 Andres Riancho <notifications@github.com>:
