### ISSUE TITLE
web_spider endless loop

### ISSUE THREAD

**Issue by andersonDadario** [andresriancho/w3af#5834]
![image](https://cloud.githubusercontent.com/assets/801595/4791095/60a5e4a2-5dd9-11e4-8a60-cc8bbe6f85e6.png)

I looked at the web_spider plugin page [1], but there is no 'max deep level' to prevent endless loops such as the image above. Is there any option to prevent that I am missing?

Doubt: am I reporting errors at the right channel?

[1] http://w3af.org/plugins/crawl/web_spider

**Comment by andresriancho** [comment]
@andersonDadario did you confirm the fix for this issue? Closing, but if you find it again please re-open/ask me to re-open
