### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by pmzelech** [andresriancho/w3af#6148]
I ran the git and then the _gui , followed by running the command to install the missing contingencies (there were several)

Now, ./w3af_gui fails with a python2.7/dist-packages/openssl/ssl.so error of "undefined symbol: sslv2_method"

**Comment by andresriancho** [comment]
Sorry to answer so late, this issue simply slip through the cracks.

This doesn't seem to be a w3af related issue, it seems more like a ssl compilation problem. Google should have a good answer.

If you're able to link this issue to something specific in w3af please let me know.
