### ISSUE TITLE
UniCodeDecode Error: 'ascii' can't decode

### ISSUE THREAD

**Issue by ST2Labs** [andresriancho/w3af#6193]
Hi,

When run w3af with OWASP TOP TEN Profile modify like this:

target
set target 
back

plugins

grep ajax, click_jacking, analyze_cookies, directory_indexing, error_500, error_pages, hash_analysis, html_comments, path_disclosure, private_ip, strange_headers,xss_protection_header,strange_reason

infrastructure afd, allowed_methods, find_vhosts, fingerprint_WAF, fingerprint_os, fingerprint_version, hmap, php_eggs, server_status, server_header

crawl find_backdoors, find_captchas, phpinfo, robots_txt, web_spider, wordpress_fingerprint
crawl config web_spider 
set only_forward true
back
audit csrf, format_string, generic, htaccess_methods, os_commanding, sqli, ssi, ssl_certificate, un_ssl, xpath, xss, xst
 
output html_file, xml_file
output config html_file
set output_file ~/OwaspTOP.html
back
output config xml_file
set output_file ~/OwaspTOP.xml
back
back

http-settings
set timeout 15
set user_agent ACS Geko 6.0
back

misc-settings
set max_discovery_time 15
set fuzz_form_files false
back

start

exit

Not finished well for all test, almost I have the same error in output_plugin, here screeshot.
![w3af_error](https://cloud.githubusercontent.com/assets/9781565/5060926/327ff26c-6d78-11e4-95e5-c744922859cc.png)

Thanks!

**Comment by andresriancho** [comment]
Duplicates html output file - UnicodeDecodeError: 'utf8' codec can't decode byte #4219
