### ISSUE TITLE
w3af scan time > 24h

### ISSUE THREAD

**Issue by ST2Labs** [andresriancho/w3af#6723]
Version 1.6.0.5
SO: Debian

Problem:
Have to kill process to abort test because w3af is running more than 24h.
High CPU usage during test (80 - 95% CPU), this is a problem when test is running long time.
All test end with XML empty or incomplete.

Solutions (Maybe)
Autoreduce thread number if w3af detect a long website or its self are running long time. Maybe its more easy a config parameters number thread to be used.

Could be a great fix for XML generation, adds reason of finished scan, so we can know if XML is empty because w3af doesn't detect anything.

URL:
www.britanico.edu.pe / ASP
200.126.170.240:8888 / Php
www.unemi.edu.ec / Joomla maybe

Script:

target
set target X
back
plugins
grep ajax, click_jacking, analyze_cookies, directory_indexing, error_pages, hash_analysis, html_comments, path_disclosure, private_ip, strange_headers,xss_protection_header,strange_reason
infrastructure afd, allowed_methods, find_vhosts, fingerprint_WAF, fingerprint_os, hmap, php_eggs, server_status, server_header
crawl find_backdoors, find_captchas, phpinfo, robots_txt, web_spider, wordpress_fingerprint
crawl config web_spider
set only_forward true
back
audit csrf, format_string, generic, htaccess_methods, os_commanding, sqli, ssi, ssl_certificate, un_ssl, xpath, xss, xst
output html_file, xml_file
output config html_file
set output_file X.html
back
output config xml_file
set output_file X.xml
back
back
http-settings
set timeout 15
set user_agent ACS Geko 6.0
back
misc-settings
set max_discovery_time 15
set fuzz_form_files false
back
start
exit

**Comment by andresriancho** [comment]
This should be fixed with the latest code at `develop` which uses different processes with timeout to run the parsers. Closing, please re-open if you find this again (in any version after e424d20).

Please note that the fixes are only available in the develop branch, but I plan to merge that into master soon.
