### ISSUE TITLE
Error while installing w3af_console  ??

### ISSUE THREAD

**Issue by KrishnaDeepthiMallela** [andresriancho/w3af#7268]
While iam installing w3af_console it is showing me the following errors .Iam unable to find the solution..Can you help me to come out of this? 

spudi@ubuntu:~/w3af$ ./w3af_console
Your python installation needs the following modules to run w3af:
    git.util scapy.config

After installing any missing operating system packages, use pip to install the remaining modules:
    sudo pip install GitPython==0.3.2.RC1 scapy-real==2.2.0-dev

A script with these commands has been created for you at /tmp/w3af_dependency_install.sh

-----Even after Installing those modules it is saying that requirements already up-to-date

 spudi@ubuntu:~/w3af$ sudo pip install GitPython==0.3.2.RC1 scapy-real==2.2.0-dev[sudo] password for spudi: 
The directory '/home/spudi/.cache/pip/log' or its parent directory is not owned by the current user and the debug log has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/home/spudi/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/home/spudi/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.

Requirement already satisfied (use --upgrade to upgrade): GitPython==0.3.2.RC1 in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): scapy-real==2.2.0-dev in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): gitdb>=0.5.1 in /usr/local/lib/python2.7/dist-packages (from GitPython==0.3.2.RC1)
Requirement already satisfied (use --upgrade to upgrade): smmap>=0.8.5 in /usr/local/lib/python2.7/dist-packages (from gitdb>=0.5.1->GitPython==0.3.2.RC1)
spudi@ubuntu:~/w3af$ 

-----------Even if I use upgrade command it is showing the same result

spudi@ubuntu:~/w3af$ sudo pip install --upgrade GitPython==0.3.2.RC1
The directory '/home/spudi/.cache/pip/log' or its parent directory is not owned by the current user and the debug log has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/home/spudi/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/home/spudi/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
Requirement already up-to-date: GitPython==0.3.2.RC1 in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: gitdb>=0.5.1 in /usr/local/lib/python2.7/dist-packages (from GitPython==0.3.2.RC1)
Requirement already up-to-date: smmap>=0.8.5 in /usr/local/lib/python2.7/dist-packages (from gitdb>=0.5.1->GitPython==0.3.2.RC1)
spudi@ubuntu:~/w3af$ 

Can you please suggest me the solution?

**Comment by andresriancho** [comment]
Duplicates https://github.com/andresriancho/w3af/issues/7185 , please see comments there.
