### ISSUE TITLE
Missing package // Already installed

### ISSUE THREAD

**Issue by JacobLoff** [andresriancho/w3af#7649]
**ProductName: Mac OS X**
**ProductVersion: 10.10.1**
**BuildVersion: 14B25**
**Python 2.7.6**
_______________________
**./w3af_console**

Your python installation needs the following modules to run w3af:
    git.util scapy.config

After installing any missing operating system packages, use pip to install the remaining modules:
    sudo pip install GitPython==0.3.2.RC1 scapy-real==2.2.0-dev

A script with these commands has been created for you at */tmp/w3af_dependency_install.sh*

**./tmp/w3af_dependency_install.sh**

Requirement already satisfied (use --upgrade to upgrade): GitPython==0.3.2.RC1 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): scapy-real==2.2.0-dev in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): gitdb>=0.5.1 in /Library/Python/2.7/site-packages (from GitPython==0.3.2.RC1)
Requirement already satisfied (use --upgrade to upgrade): smmap>=0.8.5 in /Library/Python/2.7/site-packages (from gitdb>=0.5.1->GitPython==0.3.2.RC1)

**Comment by andresriancho** [comment]
Dup https://github.com/andresriancho/w3af/issues/7185
