### ISSUE TITLE
Vulnerabilities found in website while scanning with w3af

### ISSUE THREAD

**Issue by KrishnaDeepthiMallela** [andresriancho/w3af#7699]
In w3af, after finding the vulnerabilities(in results tab) how can we manually test that the website is suffering with that vulnerability.For Example,
I have tested some website with w3af and i found these vulnerabilities 
![image](https://cloud.githubusercontent.com/assets/8917491/5854663/357a8d34-a256-11e4-9232-5b91531dc1a8.png)
How can i be sure that the website is suffering with those vulnerabilities?

I would be so grateful if u provide me the answer.

**Comment by andresriancho** [comment]
@KrishnaDeepthiMallela well, to manually test for each vulnerability you need to:
 * Understand what the vulnerability is, for that I recommend searching through the owasp wiki
 * Then you can use https://www.owasp.org/index.php/OWASP_Testing_Guide_v4_Table_of_Contents
