### ISSUE TITLE
Security vulnerabilities

### ISSUE THREAD

**Issue by KrishnaDeepthiMallela** [andresriancho/w3af#7896]
Hi,

which tools are better to test a website whether it contains  top 10 vulnerabilities or not?
Currently Iam working with w3af.  I need another tool for testing security weakness.
I would be so grateful if you provide me the solution.

Thank you.

**Comment by andresriancho** [comment]
Discussions like this are better suited for a mailing list such as the ones listed at http://w3af.org/community

Also, if you ask in the w3af mailing list people will most likely be biased. Maybe ask somewhere else.-
