### ISSUE TITLE
console output plugin enabled, but warning message suggests it's not

### ISSUE THREAD

**Issue by maniqui** [andresriancho/w3af#8000]
On a pretty vanilla installation, while standing at commit 5b3c125.
Steps:

1. run "start" command, 
2. immediately, after command finishes, run it again. 

I get this output: 

```
w3af>>> startWarning: You disabled the console output plugin. If you start a 
new scan, the discovered vulnerabilities won't be printed to the console, we 
advise you to enable at least one output plugin in order to be able to actually
see the the scan output.
```

Problem is: when I check the output plugins, the "console" one is enabled.

**Comment by andresriancho** [comment]
@maniqui is working on this on his fork

**Comment by andresriancho** [comment]
Tried to repro, but can't. Do you remember the steps to repro this issue?

**Comment by andresriancho** [comment]
Will re-open if I get the details
