### ISSUE TITLE
Support - Installing w3af in Kali

### ISSUE THREAD

**Issue by graytips** [andresriancho/w3af#8283]
Unable to install w3af in kali - 1.1.0

Error: 
Your python installation needs the following modules to run w3af:
    git.util scapy.config

After installing any missing operating system packages, use pip to install the remaining modules:
    sudo pip install GitPython==0.3.2.RC1 scapy-real==2.2.0-dev
A script with these commands has been created for you at /tmp/w3af_dependency_install.sh

My system configurations are given below.

==============
lsb_release -a
No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux 1.1.0
Release:	1.1.0
Codename:	moto
==============
 
pip freeze | grep futures
futures==2.1.5

pip freeze | grep git
gitdb==0.6.4

==============

python --version
Python 2.7.3

==================
content of   /tmp/w3af_dependency_install.sh

#!/bin/bash
sudo pip install GitPython==0.3.2.RC1 scapy-real==2.2.0-dev

=================

Please support.
Shafeeque

**Comment by andresriancho** [comment]
should be fixed with the latest release I pushed yesterday to master.
