### ISSUE TITLE
End-user UX and GitHub ToS?

### ISSUE THREAD

**Issue by wireddown** [andresriancho/w3af#8412]
I have been trying to implement a way for my users who don't have GitHub accounts to report problems and suggest improvements, but so far have been unsuccessful.

I was happy to find your site and service, and I'm evaluating its fitness for my needs.

I have two questions:

1. What would my users' experience be? The [documentation](http://docs.w3af.org/en/latest/) is pretty dense, and it's hard for me to see what an end-user would see and do when they wanted to provide feedback. If I wanted a form on my site, so that I can control the look and feel, I'm not sure what I would need to do.
1. How does this service dovetail with the GitHub Terms of Service? My largest obstacle for implementing anonymous feedback has been Article A, sections 4 and 7 (below). Have you been able to receive guidance or permission from GitHub to implement your service account ( https://github.com/1d3df9903ad ), or do you use another approach that circumvents the single-user requirements entirely?

> **GitHub [Terms of Service](https://help.github.com/articles/github-terms-of-service/)**
>
> *A.4*
>
> Your login may only be used by one person - a single login shared by multiple people is not permitted. You may create separate logins for as many people as your plan allows.
>
> *A.7*
>
> One person or legal entity may not maintain more than one free account.

**Comment by andresriancho** [comment]
I believe that the code speaks for itself:
 * https://github.com/andresriancho/w3af/blob/master/w3af/core/controllers/easy_contribution/github_issues.py

We don't provide any service around it.

Nobody has ever complained about the service user.

**Comment by wireddown** [comment]
Ok, well, you're in good [anecdotal](https://yourlogicalfallacyis.com/anecdotal) company:

![Easier to ask for forgiveness](http://image.slidesharecdn.com/quotes-131212121856-phpapp02/95/75-motivational-quotes-for-entrepreneurs-36-638.jpg)

**Comment by andresriancho** [comment]
:+1: 

Feel free to ask any more questions at our IRC channel at http://w3af.org/community , I'm `__apr__`
