### ISSUE TITLE
Unable to install dependencies under a proxy connection

### ISSUE THREAD

**Issue by urwithajit9** [andresriancho/w3af#8414]
Hi, 
I am trying to install the dependencies for w3af but can't able to do so.
I am using an Ubuntu 12.4 OS under a proxy connection.
The error i am getting is 

Downloading/unpacking clamd
  Cannot fetch index base URL http://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement clamd
No distributions at all found for clamd
Storing complete log in /home/ajit/.pip/pip.log
Note:
1. DistributionNotFound: No distributions at all found for clamd (i already have installed clamav and it's daemon .

2. pip.log showing
Could not fetch URL http://pypi.python.org/simple/clamd: HTTP Error 403: Forbidden

**Comment by andresriancho** [comment]
@urwithajit9 this is not a w3af issue, please find how to use pip behind a proxy
