### ISSUE TITLE
MemoryError Kali (with 1.9G free RAM) scanning DVWA - 1.6.0.5 Kali package

### ISSUE THREAD

**Issue by vasubesimple** [andresriancho/w3af#8502]
The following error has been occurred during the scan when I use kali installed version, when ever the screen goes off this exception raised , can you please help me to fix this problem

```pytb
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/share/w3af/w3af/core/ui/gui/exception_handling/unhandled.py", line 44, in handle_crash
    exception = traceback.format_exception(_type, value, tb)
  File "/usr/lib/python2.7/traceback.py", line 141, in format_exception
    list = list + format_tb(tb, limit)
  File "/usr/lib/python2.7/traceback.py", line 76, in format_tb
    return format_list(extract_tb(tb, limit))
  File "/usr/lib/python2.7/traceback.py", line 100, in extract_tb
    linecache.checkcache(filename)
  File "/usr/lib/python2.7/linecache.py", line 60, in checkcache
    stat = os.stat(fullname)
MemoryError
```

**Comment by andresriancho** [comment]
May I close #8501 then?

**Comment by andresriancho** [comment]
Which w3af version are you using? What configuration? What target?

**Comment by vasubesimple** [comment]
This is the version  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6.0.5
target is dvwa , I am running it on Kali , I just update  w3af from kali  repository and when comes to #8501 , I installed a stable version from your repository but it generated that dependency error so I uninstall the kali version and installed it again "apt-get install w3af" . I think you can close that ticket . if you want me to test the repository again , I can do that and report it back it you

**Comment by andresriancho** [comment]
Thanks for the information, some more questions:
 * Target is DVWA, is that running on the same workstation that your Kali linux?
 * What configuration are you using? Could you save your configuration to a profile or [script](http://docs.w3af.org/en/latest/scripts.html) and share it here?
 * Are you running the scan from the console or GUI?
 * What's the output of `free -h` right after booting Kali?

**Comment by andresriancho** [comment]
This might have been solved in the latest release (1.6.45) to try it out do:

```
cd w3af
git checkout master
git pull
./w3af_console
```

#8501 shouldn't be an issue now (fixed in master)

**Comment by vasubesimple** [comment]
What's the output of free -h right after booting Kali?
free -h
             total       used       free     shared    buffers     cached
Mem:          3.9G       2.1G       1.9G         0B       227M       1.1G
-/+ buffers/cache:       827M       3.1G
Swap:           0B         0B         0B

Target is DVWA, is that running on the same workstation that your Kali
linux?

yes it is on the same machine ! running o my apache server port 80

Are you running the scan from the console or GUI?

 GUI

What configuration are you using? Could you save your configuration to a
profile or script <http://docs.w3af.org/en/latest/scripts.html> and share
it here?
what do you want exactly are you talking about my profile in the scan

thanks and regards
Vasu

**Comment by andresriancho** [comment]
@vasubesimple Thanks for all the info! With this I'm one step closer to reproduce the issue in my VM.

Regarding the scan profile, what need you to do is:
 * Open the w3af_gui
 * Click "Create a new profile" icon in the top menu, call it 8502
 * Configure all the plugins you use to reproduce this bug
 * Click "Save this configuration" icon
 * Copy the contents of the `~/.w3af/profiles/8502.pw3af` file to a gist/pastebin
 * Send me the link to the gist/pastebin

**Comment by andresriancho** [comment]
Also, if you've got the time, please try to run this scan with the latest w3af:

```
cd w3af
git checkout master
git pull
./w3af_console
```

**Comment by andresriancho** [comment]
Once I've got the `~/.w3af/profiles/8502.pw3af` file the plan is:
 - [ ] Get the latest Kali release
 - [ ] Build a VM with 4GB RAM
 - [ ] Install w3af
 - [ ] Copy the profile to the VM
 - [ ] Snapshot the VM
 - [ ] Scan DVWA using 1.6.0.5 without any special environment variables, just to verify it crashes
 - [ ] Scan DVWA using the latest from master
 - [ ] If master also fails, run scans using the profiling environment variables and analyze output

**Comment by vasubesimple** [comment]
Hello Andres,

Thanks for the suggestion, please check the screen shot of my scan with
your new w3af,
I launch w3af_gui scan, my scanner is running in the background but gui is
stopped responding after 20 mins. I work for an organization that is why I
couldn't share the config file?

Thanks and Regards
Vasu

**Comment by andresriancho** [comment]
There is no screenshot, could you upload it directly to https://github.com/andresriancho/w3af/issues/8502  instead of sending it via email?

**Comment by vasubesimple** [comment]
HI Andres,

please check this one I have 4.gb of RAM and I am running only w3af ! and
it crashed after one hour
Exception in thread OutputManager:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/share/w3af/w3af/core/controllers/output_manager.py", line 132,
in run
    apply(self._call_output_plugins_action, args, kwds)
  File "/usr/share/w3af/w3af/core/controllers/output_manager.py", line 247,
in _call_output_plugins_action
    from w3af.core.controllers.core_helpers.status import w3af_core_status
MemoryError

Thanks and Regards
Vasu

**Comment by andresriancho** [comment]
More tracebacks don't give me any information, if you want to help please send me the configuration file. You can remove any sensitive data from it, such as the target domain (which id DVWA anyways).

**Comment by vasubesimple** [comment]
https://gist.github.com/vasubesimple/71d9539f480419436ad7

here is the information that you have requested ! Thank , if you want I can provide the original config that I am scanning for may domains by deleting the sensitive info

**Comment by andresriancho** [comment]
Thanks for the info! It will really help with the debugging and fixing.

**Comment by andresriancho** [comment]
Solved in `develop` branch
