### ISSUE TITLE
Find hidden gateway payment confirmation page

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#8691]
## Contributor wanted

This issue is [easy](https://github.com/andresriancho/w3af/issues?q=is%3Aopen+is%3Aissue+label%3Aeasy) and looking for a contributor, just add a comment saying you'll do it's yours!

Not sure where to start from? Take a look at our [First steps as a contributor](https://github.com/andresriancho/w3af/wiki/First-steps-as-a-contributor) and [Contributing 101](https://github.com/andresriancho/w3af/wiki/Contributing-101) wiki pages.

Other interesting tasks which can be completed by new `w3af` contributors can be found [here](https://github.com/andresriancho/w3af/issues?q=is%3Aopen+is%3Aissue+label%3Aeasy).
## Task description

Port the [knowledge from this tool](https://github.com/wireghoul/presentations/blob/master/BHAsia2014/returnbrute.pl) into a w3af plugin. Description from the tool itself:

> Generate a list of potential confirmation pages to brute force with a tool 
> like wget/wfuzz/burp. Useful if you're pentesting a payement gateway that 
> uses a hidden payment confirmation page which is accessed by the payment 
> gateway and not intended for public access.

I'm worried about this generating requests that pykto already generates, should review the nikto db before adding all these, and also send the GET requests with `cache=True`

**Comment by pedromachuca** [comment]
Hello, 
It is my first contribution, I will try to resolve this.

**Comment by andresriancho** [comment]
Sounds good, go ahead. Thanks!

**Comment by pedromachuca** [comment]
Hello, I created a pull request for this issue: https://github.com/andresriancho/w3af/pull/17399

I hope I did not make a mistake during the process, anyway I waiting to hear what can I do better now.
