### ISSUE TITLE
GUI does not launch

### ISSUE THREAD

**Issue by michaelmauch** [andresriancho/w3af#9084]
I have installed w3af on a Mac today and I am not able to launch the GUI. Any idea what the issue might be?

Here is the terminal output that I get (below that you can find w3af-sysinfo and also w3af_console --version outputs):

MichasMBP:w3af mmauch$ sudo ./w3af_gui 

(process:539): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Starting w3af, running on:
  Python version: 2.7.6 (default, Sep  9 2014, 15:04:36) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
  GTK version: 2.24.0
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6.48
    Revision: 4e045fdfdb - 18 Mar 2015 01:12
    Branch: master
    Local changes: No
    Author: Andres Riancho and the w3af team.
Mar 24 14:26:53 MichasMBP.fritz.box python[539] <Error>: clip: empty path.
2015-03-24 14:26:53.738 Python[539:26258] *** Assertion failure in -[GdkQuartzWindow _setFrameworkScaleFactor:], /SourceCache/AppKit/AppKit-1344.72/AppKit.subproj/NSWindow.m:22056
2015-03-24 14:26:53.740 Python[539:26258] An uncaught exception was raised
2015-03-24 14:26:53.740 Python[539:26258] _setFrameworkScaleFactor called with non-nil _borderView
2015-03-24 14:26:53.740 Python[539:26258] (
	0   CoreFoundation                      0x00007fff92c7f66c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff9796176e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff92c7f44a +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x00007fff8bb493a9 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   AppKit                              0x00007fff8dc1d90a -[NSWindow(NSWindow_Scale) _setFrameworkScaleFactor:] + 163
	5   AppKit                              0x00007fff8dc1d4d6 -[NSWindow _commonInitFrame:styleMask:backing:defer:] + 172
	6   AppKit                              0x00007fff8dc1cdc6 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1477
	7   AppKit                              0x00007fff8dc1c7f6 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 45
	8   libgdk-quartz-2.0.0.dylib           0x0000000101e7731b gdk_window_set_decorations + 416
	9   libgtk-quartz-2.0.0.dylib           0x0000000101bce72a gtk_window_realize + 942
	10  libgobject-2.0.0.dylib              0x00000001014ba9f9 g_closure_invoke + 451
	11  libgobject-2.0.0.dylib              0x00000001014ce3a5 signal_emit_unlocked_R + 1580
	12  libgobject-2.0.0.dylib              0x00000001014d009f g_signal_emit_valist + 1669
	13  libgobject-2.0.0.dylib              0x00000001014d0582 g_signal_emit + 148
	14  libgtk-quartz-2.0.0.dylib           0x0000000101bc0ccf gtk_widget_realize + 219
	15  libgtk-quartz-2.0.0.dylib           0x0000000101bcfcc1 gtk_window_show + 160
	16  libgobject-2.0.0.dylib              0x00000001014ba9f9 g_closure_invoke + 451
	17  libgobject-2.0.0.dylib              0x00000001014ce3a5 signal_emit_unlocked_R + 1580
	18  libgobject-2.0.0.dylib              0x00000001014d009f g_signal_emit_valist + 1669
	19  libgobject-2.0.0.dylib              0x00000001014d0582 g_signal_emit + 148
	20  libgtk-quartz-2.0.0.dylib           0x0000000101bc19ee gtk_widget_show + 108
	21  _gtk.so                             0x000000010182b498 _wrap_gtk_widget_show_all + 37
	22  Python                              0x00000001007f59ed PyEval_EvalFrameEx + 14935
	23  Python                              0x00000001007f1d62 PyEval_EvalCodeEx + 1413
	24  Python                              0x000000010079630a PyFunction_SetClosure + 826
	25  Python                              0x00000001007782ac PyObject_Call + 99
	26  Python                              0x00000001007830cf PyMethod_New + 1210
	27  Python                              0x00000001007782ac PyObject_Call + 99
	28  Python                              0x00000001007bf3f4 _PyObject_SlotCompare + 5592
	29  Python                              0x00000001007bacfb _PyType_Lookup + 1386
	30  Python                              0x00000001007782ac PyObject_Call + 99
	31  Python                              0x00000001007f4c00 PyEval_EvalFrameEx + 11370
	32  Python                              0x00000001007f1d62 PyEval_EvalCodeEx + 1413
	33  Python                              0x000000010079630a PyFunction_SetClosure + 826
	34  Python                              0x00000001007782ac PyObject_Call + 99
	35  Python                              0x00000001007830cf PyMethod_New + 1210
	36  Python                              0x00000001007782ac PyObject_Call + 99
	37  Python                              0x00000001007bf3f4 _PyObject_SlotCompare + 5592
	38  Python                              0x00000001007bacfb _PyType_Lookup + 1386
	39  Python                              0x00000001007782ac PyObject_Call + 99
	40  Python                              0x00000001007f4c00 PyEval_EvalFrameEx + 11370
	41  Python                              0x00000001007f1d62 PyEval_EvalCodeEx + 1413
	42  Python                              0x00000001007f857d _PyEval_SliceIndex + 757
	43  Python                              0x00000001007f53e3 PyEval_EvalFrameEx + 13389
	44  Python                              0x00000001007f1d62 PyEval_EvalCodeEx + 1413
	45  Python                              0x00000001007f857d _PyEval_SliceIndex + 757
	46  Python                              0x00000001007f53e3 PyEval_EvalFrameEx + 13389
	47  Python                              0x00000001007f1d62 PyEval_EvalCodeEx + 1413
	48  Python                              0x00000001007f857d _PyEval_SliceIndex + 757
	49  Python                              0x00000001007f53e3 PyEval_EvalFrameEx + 13389
	50  Python                              0x00000001007f1d62 PyEval_EvalCodeEx + 1413
	51  Python                              0x00000001007f17d7 PyEval_EvalCode + 54
	52  Python                              0x00000001008117bd PyParser_ASTFromFile + 315
	53  Python                              0x0000000100811860 PyRun_FileExFlags + 133
	54  Python                              0x00000001008113fd PyRun_SimpleFileExFlags + 769
	55  Python                              0x0000000100822b23 Py_Main + 3051
	56  libdyld.dylib                       0x00007fff8c7525c9 start + 1
	57  ???                                 0x0000000000000002 0x0 + 2
)
2015-03-24 14:26:53.741 Python[539:26258] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '_setFrameworkScaleFactor called with non-nil _borderView'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff92c7f66c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff9796176e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff92c7f44a +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x00007fff8bb493a9 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   AppKit                              0x00007fff8dc1d90a -[NSWindow(NSWindow_Scale) _setFrameworkScaleFactor:] + 163
	5   AppKit                              0x00007fff8dc1d4d6 -[NSWindow _commonInitFrame:styleMask:backing:defer:] + 172
	6   AppKit                              0x00007fff8dc1cdc6 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1477
	7   AppKit                              0x00007fff8dc1c7f6 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 45
	8   libgdk-quartz-2.0.0.dylib           0x0000000101e7731b gdk_window_set_decorations + 416
	9   libgtk-quartz-2.0.0.dylib           0x0000000101bce72a gtk_window_realize + 942
	10  libgobject-2.0.0.dylib              0x00000001014ba9f9 g_closure_invoke + 451
	11  libgobject-2.0.0.dylib              0x00000001014ce3a5 signal_emit_unlocked_R + 1580
	12  libgobject-2.0.0.dylib              0x00000001014d009f g_signal_emit_valist + 1669
	13  libgobject-2.0.0.dylib              0x00000001014d0582 g_signal_emit + 148
	14  libgtk-quartz-2.0.0.dylib           0x0000000101bc0ccf gtk_widget_realize + 219
	15  libgtk-quartz-2.0.0.dylib           0x0000000101bcfcc1 gtk_window_show + 160
	16  libgobject-2.0.0.dylib              0x00000001014ba9f9 g_closure_invoke + 451
	17  libgobject-2.0.0.dylib              0x00000001014ce3a5 signal_emit_unlocked_R + 1580
	18  libgobject-2.0.0.dylib              0x00000001014d009f g_signal_emit_valist + 1669
	19  libgobject-2.0.0.dylib              0x00000001014d0582 g_signal_emit + 148
	20  libgtk-quartz-2.0.0.dylib           0x0000000101bc19ee gtk_widget_show + 108
	21  _gtk.so                             0x000000010182b498 _wrap_gtk_widget_show_all + 37
	22  Python                              0x00000001007f59ed PyEval_EvalFrameEx + 14935
	23  Python                              0x00000001007f1d62 PyEval_EvalCodeEx + 1413
	24  Python                              0x000000010079630a PyFunction_SetClosure + 826
	25  Python                              0x00000001007782ac PyObject_Call + 99
	26  Python                              0x00000001007830cf PyMethod_New + 1210
	27  Python                              0x00000001007782ac PyObject_Call + 99
	28  Python                              0x00000001007bf3f4 _PyObject_SlotCompare + 5592
	29  Python                              0x00000001007bacfb _PyType_Lookup + 1386
	30  Python                              0x00000001007782ac PyObject_Call + 99
	31  Python                              0x00000001007f4c00 PyEval_EvalFrameEx + 11370
	32  Python                              0x00000001007f1d62 PyEval_EvalCodeEx + 1413
	33  Python                              0x000000010079630a PyFunction_SetClosure + 826
	34  Python                              0x00000001007782ac PyObject_Call + 99
	35  Python                              0x00000001007830cf PyMethod_New + 1210
	36  Python                              0x00000001007782ac PyObject_Call + 99
	37  Python                              0x00000001007bf3f4 _PyObject_SlotCompare + 5592
	38  Python                              0x00000001007bacfb _PyType_Lookup + 1386
	39  Python                              0x00000001007782ac PyObject_Call + 99
	40  Python                              0x00000001007f4c00 PyEval_EvalFrameEx + 11370
	41  Python                              0x00000001007f1d62 PyEval_EvalCodeEx + 1413
	42  Python                              0x00000001007f857d _PyEval_SliceIndex + 757
	43  Python                              0x00000001007f53e3 PyEval_EvalFrameEx + 13389
	44  Python                              0x00000001007f1d62 PyEval_EvalCodeEx + 1413
	45  Python                              0x00000001007f857d _PyEval_SliceIndex + 757
	46  Python                              0x00000001007f53e3 PyEval_EvalFrameEx + 13389
	47  Python                              0x00000001007f1d62 PyEval_EvalCodeEx + 1413
	48  Python                              0x00000001007f857d _PyEval_SliceIndex + 757
	49  Python                              0x00000001007f53e3 PyEval_EvalFrameEx + 13389
	50  Python                              0x00000001007f1d62 PyEval_EvalCodeEx + 1413
	51  Python                              0x00000001007f17d7 PyEval_EvalCode + 54
	52  Python                              0x00000001008117bd PyParser_ASTFromFile + 315
	53  Python                              0x0000000100811860 PyRun_FileExFlags + 133
	54  Python                              0x00000001008113fd PyRun_SimpleFileExFlags + 769
	55  Python                              0x0000000100822b23 Py_Main + 3051
	56  libdyld.dylib                       0x00007fff8c7525c9 start + 1
	57  ???                                 0x0000000000000002 0x0 + 2
)
libc++abi.dylib: terminating with uncaught exception of type NSException

________

./w3af_console --version
w3af - Web Application Attack and Audit Framework
Version: 1.6.48
Revision: 4e045fdfdb - 18 Mar 2015 01:12
Branch: master
Local changes: No
Author: Andres Riancho and the w3af team.

_________

w3af-sysinfo:

Operating system
================
System: darwin - Distribution: ('', '', '') - Release: 14.1.0

Kernel version
==============
Darwin MichasMBP.fritz.box 14.1.0 Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64 x86_64

Python version
==============

pip version
===========
pip 6.0.8 from /Library/Python/2.7/site-packages (python 2.7)

pip freeze
==========
altgraph==0.10.2
bdist-mpkg==0.5.0
bonjour-py==0.3
chardet==2.1.1
clamd==1.0.1
cluster==1.1.1b3
darts.util.lru==0.5
esmre==0.3.1
futures==2.1.5
gitdb==0.6.4
GitPython==0.3.2rc1
guess-language==0.2
halberd==0.2.4
Jinja2==2.7.3
lxml==2.3.2
macholib==1.5.1
MarkupSafe==0.23
matplotlib==1.3.1
modulegraph==0.10.4
msgpack-python==0.4.4
ndg-httpsclient==0.3.3
nltk==3.0.1
numpy==1.8.0rc1
pdfminer==20140328
phply==0.9.1
ply==3.4
py2app==0.7.3
pyasn1==0.1.3
pybloomfiltermmap==0.3.11
PyGithub==1.21.0
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==0.13.1
pyparsing==2.0.1
python-dateutil==1.5
python-ntlm==1.0.1
pytz==2013.7
scapy-real==2.2.0.dev0
scipy==0.13.0b1
six==1.4.1
smmap==0.9.0
stopit==1.1.0
tblib==0.2.0
Twisted==13.2.0
xattr==0.6.4
xdot==0.6
zope.interface==4.1.1

Package list
============
altgraph==0.10.2
bdist-mpkg==0.5.0
bonjour-py==0.3
chardet==2.1.1
clamd==1.0.1
cluster==1.1.1b3
darts.util.lru==0.5
esmre==0.3.1
futures==2.1.5
gitdb==0.6.4
GitPython==0.3.2rc1
guess-language==0.2
halberd==0.2.4
Jinja2==2.7.3
lxml==2.3.2
macholib==1.5.1
MarkupSafe==0.23
matplotlib==1.3.1
modulegraph==0.10.4
msgpack-python==0.4.4
ndg-httpsclient==0.3.3
nltk==3.0.1
numpy==1.8.0rc1
pdfminer==20140328
phply==0.9.1
ply==3.4
py2app==0.7.3
pyasn1==0.1.3
pybloomfiltermmap==0.3.11
PyGithub==1.21.0
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==0.13.1
pyparsing==2.0.1
python-dateutil==1.5
python-ntlm==1.0.1
pytz==2013.7
scapy-real==2.2.0.dev0
scipy==0.13.0b1
six==1.4.1
smmap==0.9.0
stopit==1.1.0
tblib==0.2.0
Twisted==13.2.0
xattr==0.6.4
xdot==0.6
zope.interface==4.1.1

**Comment by andresriancho** [comment]
See https://github.com/andresriancho/w3af/issues/3953

**Comment by andresriancho** [comment]
Like #3953 says, this is 100% related to mac+specific library version.

I'm going to try a really long shot, if this works I can also go buy a lottery ticket, because it has the same chances of win:

 * Open ./w3af/core/ui/gui/splash.py
 * Find the line that says `self.set_decorated(False)` and comment it `#self.set_decorated(False)`
 * Try to open w3af_gui again

Let me know if it works

**Comment by michaelmauch** [comment]
It helped, I could see a GUI for a few seconds, and then it disappeared. Here is the next issue:

MichasMBP:w3af mmauch$ sudo ./w3af_gui 
Password:

(process:1576): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Starting w3af, running on:
  Python version: 2.7.6 (default, Sep  9 2014, 15:04:36) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
  GTK version: 2.24.0
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6.48
    Revision: 4e045fdfdb - 18 Mar 2015 01:12
    Branch: master
    Local changes: Yes
    Author: Andres Riancho and the w3af team.
Mar 24 15:50:33 MichasMBP.fritz.box python[1576] <Error>: clip: empty path.
Traceback (most recent call last):
  File "./w3af_gui", line 110, in <module>
    _main()
  File "./w3af_gui", line 106, in _main
    sys.exit(main())
  File "./w3af_gui", line 101, in main
    gui_main(profile, doupdate)
  File "/Users/mmauch/Software/w3af/w3af/w3af/core/ui/gui/main.py", line 931, in main
    MainApp(profile, do_upd)
  File "/Users/mmauch/Software/w3af/w3af/w3af/core/ui/gui/main.py", line 410, in __init__
    self.pcbody = pluginconfig.PluginConfigBody(self, self.w3af)
  File "/Users/mmauch/Software/w3af/w3af/w3af/core/ui/gui/pluginconfig.py", line 624, in __init__
    self.pan = self._buildpan()
  File "/Users/mmauch/Software/w3af/w3af/w3af/core/ui/gui/pluginconfig.py", line 644, in _buildpan
    self.w3af, "standard", self.config_panel)
  File "/Users/mmauch/Software/w3af/w3af/w3af/core/ui/gui/pluginconfig.py", line 245, in __init__
    if self._getEditablePlugin(plugin, plugintype):
  File "/Users/mmauch/Software/w3af/w3af/w3af/core/ui/gui/pluginconfig.py", line 301, in _getEditablePlugin
    plugin = self.w3af.plugins.get_plugin_inst(ptype, pname)
  File "/Users/mmauch/Software/w3af/w3af/w3af/core/controllers/core_helpers/plugins.py", line 247, in get_plugin_inst
    plugin_inst = factory('w3af.plugins.%s.%s' % (plugin_type, plugin_name))
  File "/Users/mmauch/Software/w3af/w3af/w3af/core/controllers/misc/factory.py", line 46, in factory
    raise BaseFrameworkException(msg % (module_name, ie))
BaseFrameworkException: There was an error while importing w3af.plugins.infrastructure.http_vs_https_dist: "No module named pcapy".

Mar 24 15:50:46 MichasMBP.fritz.box python[1576] <Error>: clip: empty path.

**Comment by andresriancho** [comment]
The pcapy issue is a missing dependency that you need to install, the previous was a really strange mac+w3af+pygtk issue that I just fixed with the commit+push

For the missing dependency check the previous issues that mention pcapy https://github.com/andresriancho/w3af/search?q=pcapy&type=Issues&utf8=%E2%9C%93
