### ISSUE TITLE
Cannot start w3af_gui on Ubuntu 14.04

### ISSUE THREAD

**Issue by Benjen** [andresriancho/w3af#9260]
I have just installed w3af however when I try to lauch it using the w3af_gui script I receive the following error:

from: can't read /var/mail/__future__
from: can't read /var/mail/w3af.core.ui.gui.dependency_check.dependency_check
./w3af_gui: 18: ./w3af_gui: USAGE_DOC: not found
./w3af_gui: 45: ./w3af_gui: Syntax error: "(" unexpected

My environment is as follows:
python = 2.7.6
pip = 6.0.8

**Comment by andresriancho** [comment]
it seems you're trying to execute it like a bash script. w3af_gui and w3af_console are python scripts. This works for me:

./w3af_gui
