### ISSUE TITLE
False positive related to c99shell.php @ find_backdoors

### ISSUE THREAD

**Issue by cpantel** [andresriancho/w3af#9284]
While scanning a drupal 7 site, w3af reported a c99shell.php candidate.

The problem is that the site is badly configured. When there is a *.php missing file, the site's "file not found" handler answers. When there is a *.* missing file, the apache's "file not found handler" answers.

To check this, I tried:

c99shell.php -> site error
c99shell2.php -> site error
any.php -> site error

c99shell.pl -> apache error
any.cgi -> apacher error

So, it seems that there is no c99shell.php backdoor.

I am using w3af 1.6.48 on ubuntu 12.04.5

Sorry I can not share the url.
Sorry I do not have time to check if this issue is already reported, neither propose a solution.

I think that it is a low priority issue.

Charly

**Comment by andresriancho** [comment]
Thanks for the bug report, quick question to better understand your issue. Are you seeing [this message](https://github.com/andresriancho/w3af/blob/master/w3af/plugins/crawl/find_backdoors.py#L125) or just something saying that w3af found a new URL?

**Comment by cpantel** [comment]
yes Andres, that message 
[timestamp] An HTTP response matching the web backdoor signature "c99shell" was found at: "http://DOMAIN/PATH/c99shell.php"; this could indicate that the server has been compromised. This vulnerability was found in the request with id ID.
many different paths.
¿Does c99shell.php have something special? This urls gave the same error page but are not listed as potential backdoors.

[timestamp] - http://DOMAIN/c99.php (request with id: ID)
[timestamp] - http://DOMAIN/c99_PSych0.php (request with id: ID)
[timestamp] - http://DOMAIN/c99_locus7s.php (request with id: ID)
[timestamp] - http://DOMAIN/c99_madnet.php (request with id: ID)
[timestamp] - http://DOMAIN/c99_w4cking.php (request with id: ID)

 
Carlos Pantelides

@dev4sec

http://seguridad-agile.blogspot.com/ 


     On Friday, April 3, 2015 5:18 PM, Andres Riancho <notifications@github.com> wrote:
   

 Thanks for the bug report, quick question to better understand your issue. Are you seeing this message or just something saying that w3af found a new URL?—

**Comment by andresriancho** [comment]
Ah! It was you! :+1: 

Which git revision are you using?

**Comment by andresriancho** [comment]
18 days ago I changed this plugin (a lot). https://github.com/andresriancho/w3af/commits/master/w3af/plugins/crawl/find_backdoors.py

**Comment by andresriancho** [comment]
Looks like this signatures are too generic and might match a 404:

```patch
+c99shell</title>
+c99shell
+C99Shell v
```

**Comment by cpantel** [comment]
today's clone, please do not do me turn off that slow virtual machine...
 Carlos Pantelides

@dev4sec

http://seguridad-agile.blogspot.com/ 


     On Friday, April 3, 2015 7:11 PM, Andres Riancho <notifications@github.com> wrote:
   

 Looks like this signatures are too generic and might match a 404:+c99shell</title>
+c99shell
+C99Shell v—

**Comment by cpantel** [comment]
ok, I will do it
version 1.6.48revision 4e045fdfdb 18 Mar 2015 01:12 Carlos Pantelides

@dev4sec

http://seguridad-agile.blogspot.com/ 


     On Friday, April 3, 2015 7:34 PM, Carlos Pantelides <carlos_pantelides@yahoo.com> wrote:
   

 today's clone, please do not do me turn off that slow virtual machine...
 Carlos Pantelides

@dev4sec

http://seguridad-agile.blogspot.com/ 


     On Friday, April 3, 2015 7:11 PM, Andres Riancho <notifications@github.com> wrote:
   

 Looks like this signatures are too generic and might match a 404:+c99shell</title>
+c99shell
+C99Shell v—

**Comment by cpantel** [comment]
sorry, I'm sitting on master, I'm an old coward conservative guy Carlos Pantelides

@dev4sec

http://seguridad-agile.blogspot.com/ 


     On Friday, April 3, 2015 7:40 PM, Carlos Pantelides <carlos_pantelides@yahoo.com> wrote:
   

 ok, I will do it
version 1.6.48revision 4e045fdfdb 18 Mar 2015 01:12 Carlos Pantelides

@dev4sec

http://seguridad-agile.blogspot.com/ 


     On Friday, April 3, 2015 7:34 PM, Carlos Pantelides <carlos_pantelides@yahoo.com> wrote:
   

 today's clone, please do not do me turn off that slow virtual machine...
 Carlos Pantelides

@dev4sec

http://seguridad-agile.blogspot.com/ 


     On Friday, April 3, 2015 7:11 PM, Andres Riancho <notifications@github.com> wrote:
   

 Looks like this signatures are too generic and might match a 404:+c99shell</title>
+c99shell
+C99Shell v—

**Comment by andresriancho** [comment]
Ok, the latest develop should have this issue fixed.
