### ISSUE TITLE
Malfunction

### ISSUE THREAD

**Issue by pkhadka56** [andresriancho/w3af#9322]
w3af - Web Application Attack and Audit Framework
Version: 1.6.46
Distribution: Kali Linux v1.1.0
Author: Andres Riancho and the w3af team.

Python 2.7.3

1. start w3af_console
    - plugins
    - crawl
    - crawl phpinfo
    - back
     - target
     - set target somesite.com (in my case I have setup one pentest2.com and changed my host in /etc/hosts)
     - back
     - start
     ..............
3. Interrupt the scan by pressing ctrl+C 
4. At this time if you type "start" then following message will be shown to you

"Warning: You disabled the console output plugin. If you start a new scan, the discovered vulnerabilities won't be printed to the console, we advise you to enable at least one output plugin in order to be able to actually see the the scan output."

5. After this if you enter or type anything else will do nothing

w3af>>> w3af>>> w3af>>> w3af>>> w3af>>> helpw3af>>> w3af>>>

![w3af](https://cloud.githubusercontent.com/assets/8862495/6996199/555cdb40-db98-11e4-83de-267eb9336900.png)

**Comment by andresriancho** [comment]
I think I've fixed this in the latest w3af in the develop branch. Could you please try to reproduce it?

```
git clone https://github.com/andresriancho/w3af.git
cd w3af
git checkout develop
./w3af_console
# install new dependencies
./w3af_console
# reproduce issue
```

**Comment by pkhadka56** [comment]
ok, can't reproduce it Version: 1.6.48
Thanks.
