### ISSUE TITLE
No license in root

### ISSUE THREAD

**Issue by DavidJFelix** [andresriancho/w3af#9353]
If this project is licensed under the GPLv2, it should feature a `LICENSE` file in the root of the directory which contains the full text of the GPLv2.

**Comment by andresriancho** [comment]
Not required by the GPL license, and:
 * https://github.com/andresriancho/w3af/blob/master/doc/GPL
 * All source code files have a header saying it's GPL

**Comment by DavidJFelix** [comment]
Didn't mean to imply it was a violation of the GPL, just meant that it might be friendlier for people passing through on github.
