### ISSUE TITLE
W3af not compiling pip installations

### ISSUE THREAD

**Issue by Artook** [andresriancho/w3af#9754]
I am trying to install w3af after download but after loading dependencies and starting /tmp/w3af_dependency/install.sh I get the pip loads but during compiling get an end error. 

 I am using Linux Mint 17.02.

 pip dependencies loaded:
Collecting esmre==0.3.1
  Using cached esmre-0.3.1.tar.gz
Collecting phply==0.9.1
  Using cached phply-0.9.1.tar.gz
Collecting stopit==1.1.0
  Using cached stopit-1.1.0.tar.gz
Collecting nltk==3.0.1
  Using cached nltk-3.0.1.tar.gz
Collecting chardet==2.1.1
  Using cached chardet-2.1.1.tar.gz
Collecting tblib==0.2.0
  Using cached tblib-0.2.0-py2-none-any.whl
Collecting pdfminer==20140328
  Using cached pdfminer-20140328.tar.gz
Collecting futures==2.1.5
  Using cached futures-2.1.5-py2.py3-none-any.whl
Collecting pyOpenSSL==0.13.1
  Using cached pyOpenSSL-0.13.1.tar.gz
Collecting ndg-httpsclient==0.3.3
  Using cached ndg_httpsclient-0.3.3.tar.gz
Collecting pyasn1==0.1.3
  Using cached pyasn1-0.1.3.tar.gz
Collecting lxml==2.3.2
  Using cached lxml-2.3.2.tar.gz
Collecting scapy-real==2.2.0-dev
  Using cached scapy-real-2.2.0-dev.tar.gz
Collecting guess-language==0.2
  Using cached guess-language-0.2.tar.gz
Collecting cluster==1.1.1b3
  Using cached cluster-1.1.1b3.tar.gz
Collecting msgpack-python==0.4.4
  Using cached msgpack-python-0.4.4.tar.gz
Collecting python-ntlm==1.0.1
  Using cached python-ntlm-1.0.1.tar.gz
Collecting halberd==0.2.4
  Using cached halberd-0.2.4.tar.gz
Collecting darts.util.lru==0.5
  Using cached darts.util.lru-0.5.tar.gz
Collecting Jinja2==2.7.3
  Using cached Jinja2-2.7.3.tar.gz
Collecting vulndb==0.0.17
  Using cached vulndb-0.0.17.tar.gz
Collecting markdown==2.6.1
  Using cached Markdown-2.6.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/dist-packages (from esmre==0.3.1)
Collecting ply (from phply==0.9.1)
  Using cached ply-3.6.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from tblib==0.2.0)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /usr/lib/python2.7/dist-packages (from Jinja2==2.7.3)
Installing collected packages: esmre, ply, phply, stopit, nltk, chardet, tblib, pdfminer, futures, pyOpenSSL, ndg-httpsclient, pyasn1, lxml, scapy-real, guess-language, cluster, msgpack-python, python-ntlm, halberd, darts.util.lru, Jinja2, vulndb, markdown

this is the error:
    Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-NBHshU/esmre/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-k39PX7-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-NBHshU/esmre
Any help is appreciated I have tried finding matches to linux Mint but no luck.
Artook.

**Comment by andresriancho** [comment]
Do you have a more detailed error? The "compile" error is not very detailed.

PS: This is not a w3af problem, but a mint/pip issue
