### ISSUE TITLE
No module named pdfpage

### ISSUE THREAD

**Issue by fcano** [andresriancho/w3af#9942]
Just installed w3af 1.6.51-0kali1 and when I try to execute it I get this error:

$ w3af
Something went wrong, w3af failed to start the output manager.
Exception: "There was an error while importing w3af.plugins.output.console: "No module named pdfpage"."

I searched pdfpage and I saw that it belogs to pdfminer. I tried to install it but I had it already installed.

**Comment by andresriancho** [comment]
* Could you send me the output of `pip freeze`?
 * Is this a "default" Kali installation or did you customize it?
 * Which Kali version are you using?

**Comment by andresriancho** [comment]
Closing, please re-open if you've got more info.
